//! Bulk operations for QuotationItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateQuotationItemDto;
use crate::application::service::QuotationItemService;
use crate::domain::entity::QuotationItem;

/// Bulk operation handler for QuotationItem entities.
///
/// Wraps `QuotationItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type QuotationItemBulkService = GenericBulkService<QuotationItem, CreateQuotationItemDto, QuotationItemService>;

// <<< CUSTOM
// END CUSTOM
