//! Bulk operations for SalesInvoiceItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalesInvoiceItemDto;
use crate::application::service::SalesInvoiceItemService;
use crate::domain::entity::SalesInvoiceItem;

/// Bulk operation handler for SalesInvoiceItem entities.
///
/// Wraps `SalesInvoiceItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalesInvoiceItemBulkService = GenericBulkService<SalesInvoiceItem, CreateSalesInvoiceItemDto, SalesInvoiceItemService>;

// <<< CUSTOM
// END CUSTOM
