//! Bulk operations for SalesPersonAllocation entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalesPersonAllocationDto;
use crate::application::service::SalesPersonAllocationService;
use crate::domain::entity::SalesPersonAllocation;

/// Bulk operation handler for SalesPersonAllocation entities.
///
/// Wraps `SalesPersonAllocationService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalesPersonAllocationBulkService = GenericBulkService<SalesPersonAllocation, CreateSalesPersonAllocationDto, SalesPersonAllocationService>;

// <<< CUSTOM
// END CUSTOM
