//! Bulk operations for SalesOrderItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalesOrderItemDto;
use crate::application::service::SalesOrderItemService;
use crate::domain::entity::SalesOrderItem;

/// Bulk operation handler for SalesOrderItem entities.
///
/// Wraps `SalesOrderItemService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalesOrderItemBulkService = GenericBulkService<SalesOrderItem, CreateSalesOrderItemDto, SalesOrderItemService>;

// <<< CUSTOM
// END CUSTOM
