//! Bulk operations for SalesInvoice entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericBulkService` — config, progress tracking, and
//! batch execution logic live in backbone-core.

use backbone_core::GenericBulkService;
pub use backbone_core::{BulkOperationConfig, BulkOperationProgress, BulkFailureMode, BulkItemResult, BulkOperationResult};

use crate::presentation::dto::CreateSalesInvoiceDto;
use crate::application::service::SalesInvoiceService;
use crate::domain::entity::SalesInvoice;

/// Bulk operation handler for SalesInvoice entities.
///
/// Wraps `SalesInvoiceService` with configurable batch size, concurrency,
/// and `ContinueOnError` / `AbortOnFirstError` failure modes.
pub type SalesInvoiceBulkService = GenericBulkService<SalesInvoice, CreateSalesInvoiceDto, SalesInvoiceService>;

// <<< CUSTOM
// END CUSTOM
