//! SalesInvoice DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SalesInvoice;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::GlPostingState;
use crate::domain::entity::SalesInvoiceStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SalesInvoice
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSalesInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_number")]
    pub invoice_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_order_id")]
    pub sales_order_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    pub status: SalesInvoiceStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "invoice_date")]
    pub invoice_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    #[serde(alias = "tax_rate")]
    pub tax_rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
    pub total: Decimal,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "receivable_account_id")]
    pub receivable_account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_output_account_id")]
    pub tax_output_account_id: Option<Uuid>,
    #[serde(alias = "posting_state")]
    pub posting_state: GlPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SalesInvoice
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSalesInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "invoice_number")]
    pub invoice_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_order_id")]
    pub sales_order_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    pub status: SalesInvoiceStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "invoice_date")]
    pub invoice_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    #[serde(alias = "tax_rate")]
    pub tax_rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
    pub total: Decimal,
    #[serde(alias = "outstanding_amount")]
    pub outstanding_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "receivable_account_id")]
    pub receivable_account_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "tax_output_account_id")]
    pub tax_output_account_id: Option<Uuid>,
    #[serde(alias = "posting_state")]
    pub posting_state: GlPostingState,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SalesInvoice
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSalesInvoiceDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_number")]
    pub invoice_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_order_id")]
    pub sales_order_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SalesInvoiceStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_date")]
    pub invoice_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "due_date")]
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_rate")]
    pub tax_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_amount")]
    pub tax_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "outstanding_amount")]
    pub outstanding_amount: Option<Decimal>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "receivable_account_id")]
    pub receivable_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_output_account_id")]
    pub tax_output_account_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posting_state")]
    pub posting_state: Option<GlPostingState>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "journal_id")]
    pub journal_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "accounting_post_id")]
    pub accounting_post_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "posted_at")]
    pub posted_at: Option<DateTime<Utc>>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchSalesInvoiceDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_number.is_some() || self.sales_order_id.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.customer_id.is_some() || self.status.is_some() || self.invoice_date.is_some() || self.due_date.is_some() || self.currency.is_some() || self.subtotal.is_some() || self.tax_rate.is_some() || self.tax_amount.is_some() || self.total.is_some() || self.outstanding_amount.is_some() || self.receivable_account_id.is_some() || self.tax_output_account_id.is_some() || self.posting_state.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.posted_at.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SalesInvoice entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub invoice_number: String,
    pub sales_order_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    pub status: SalesInvoiceStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub invoice_date: NaiveDate,
    pub due_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub outstanding_amount: Decimal,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub receivable_account_id: Uuid,
    pub tax_output_account_id: Option<Uuid>,
    pub posting_state: GlPostingState,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub posted_at: Option<DateTime<Utc>>,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SalesInvoice entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceListResponseDto {
    /// List of items
    pub items: Vec<SalesInvoiceResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SalesInvoiceListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SalesInvoiceResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceSummaryDto {
    pub id: Uuid,
    pub invoice_number: String,
    pub sales_order_id: Option<Uuid>,
    pub company_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SalesInvoice> for SalesInvoiceResponseDto {
    fn from(entity: SalesInvoice) -> Self {
        Self {
            id: entity.id,
            invoice_number: entity.invoice_number,
            sales_order_id: entity.sales_order_id,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            customer_id: entity.customer_id,
            status: entity.status,
            invoice_date: entity.invoice_date,
            due_date: entity.due_date,
            currency: entity.currency,
            subtotal: entity.subtotal,
            tax_rate: entity.tax_rate,
            tax_amount: entity.tax_amount,
            total: entity.total,
            outstanding_amount: entity.outstanding_amount,
            receivable_account_id: entity.receivable_account_id,
            tax_output_account_id: entity.tax_output_account_id,
            posting_state: entity.posting_state,
            journal_id: entity.journal_id,
            accounting_post_id: entity.accounting_post_id,
            posted_at: entity.posted_at,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<SalesInvoice> for SalesInvoiceSummaryDto {
    fn from(entity: SalesInvoice) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_number: entity.invoice_number,
            sales_order_id: entity.sales_order_id,
            company_id: entity.company_id,
            created_at,
        }
    }
}

impl From<CreateSalesInvoiceDto> for SalesInvoice {
    fn from(dto: CreateSalesInvoiceDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_number: dto.invoice_number,
            sales_order_id: dto.sales_order_id,
            company_id: dto.company_id,
            branch_id: dto.branch_id,
            customer_id: dto.customer_id,
            status: dto.status,
            invoice_date: dto.invoice_date,
            due_date: dto.due_date,
            currency: dto.currency,
            subtotal: dto.subtotal,
            tax_rate: dto.tax_rate,
            tax_amount: dto.tax_amount,
            total: dto.total,
            outstanding_amount: dto.outstanding_amount,
            receivable_account_id: dto.receivable_account_id,
            tax_output_account_id: dto.tax_output_account_id,
            posting_state: dto.posting_state,
            journal_id: dto.journal_id,
            accounting_post_id: dto.accounting_post_id,
            posted_at: dto.posted_at,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SalesInvoice> for SalesInvoiceResponseDto {
    fn from(entity: &SalesInvoice) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_number: entity.invoice_number.clone(),
            sales_order_id: entity.sales_order_id.clone(),
            company_id: entity.company_id.clone(),
            branch_id: entity.branch_id.clone(),
            customer_id: entity.customer_id.clone(),
            status: entity.status.clone(),
            invoice_date: entity.invoice_date.clone(),
            due_date: entity.due_date.clone(),
            currency: entity.currency.clone(),
            subtotal: entity.subtotal.clone(),
            tax_rate: entity.tax_rate.clone(),
            tax_amount: entity.tax_amount.clone(),
            total: entity.total.clone(),
            outstanding_amount: entity.outstanding_amount.clone(),
            receivable_account_id: entity.receivable_account_id.clone(),
            tax_output_account_id: entity.tax_output_account_id.clone(),
            posting_state: entity.posting_state.clone(),
            journal_id: entity.journal_id.clone(),
            accounting_post_id: entity.accounting_post_id.clone(),
            posted_at: entity.posted_at.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSalesInvoiceDto> for SalesInvoice {
    fn from_create_dto(dto: CreateSalesInvoiceDto) -> backbone_core::ServiceResult<Self> {
        Ok(SalesInvoice::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSalesInvoiceDto> for SalesInvoice {
    fn apply_update(mut self, dto: UpdateSalesInvoiceDto) -> backbone_core::ServiceResult<Self> {
        self.invoice_number = dto.invoice_number;
        self.sales_order_id = dto.sales_order_id;
        self.company_id = dto.company_id;
        self.branch_id = dto.branch_id;
        self.customer_id = dto.customer_id;
        self.status = dto.status;
        self.invoice_date = dto.invoice_date;
        self.due_date = dto.due_date;
        self.currency = dto.currency;
        self.subtotal = dto.subtotal;
        self.tax_rate = dto.tax_rate;
        self.tax_amount = dto.tax_amount;
        self.total = dto.total;
        self.outstanding_amount = dto.outstanding_amount;
        self.receivable_account_id = dto.receivable_account_id;
        self.tax_output_account_id = dto.tax_output_account_id;
        self.posting_state = dto.posting_state;
        self.journal_id = dto.journal_id;
        self.accounting_post_id = dto.accounting_post_id;
        self.posted_at = dto.posted_at;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SalesInvoice here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
