//! SalesInvoiceItem DTOs (Data Transfer Objects)
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SalesInvoiceItem;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SalesInvoiceItem
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSalesInvoiceItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_id")]
    pub invoice_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_order_item_id")]
    pub sales_order_item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "revenue_account_id")]
    pub revenue_account_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    #[serde(alias = "unit_price")]
    pub unit_price: Decimal,
    #[serde(alias = "line_discount")]
    pub line_discount: Decimal,
    #[serde(alias = "line_amount")]
    pub line_amount: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SalesInvoiceItem
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSalesInvoiceItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "invoice_id")]
    pub invoice_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "item_id")]
    pub item_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_order_item_id")]
    pub sales_order_item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "revenue_account_id")]
    pub revenue_account_id: Uuid,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub quantity: Decimal,
    #[serde(alias = "unit_price")]
    pub unit_price: Decimal,
    #[serde(alias = "line_discount")]
    pub line_discount: Decimal,
    #[serde(alias = "line_amount")]
    pub line_amount: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SalesInvoiceItem
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSalesInvoiceItemDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "invoice_id")]
    pub invoice_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "item_id")]
    pub item_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_order_item_id")]
    pub sales_order_item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "revenue_account_id")]
    pub revenue_account_id: Option<Uuid>,
    #[cfg_attr(feature = "validation", validate(length(max = 300)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "unit_price")]
    pub unit_price: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "line_discount")]
    pub line_discount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "line_amount")]
    pub line_amount: Option<Decimal>,
}

impl PatchSalesInvoiceItemDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.invoice_id.is_some() || self.company_id.is_some() || self.item_id.is_some() || self.sales_order_item_id.is_some() || self.revenue_account_id.is_some() || self.description.is_some() || self.quantity.is_some() || self.unit_price.is_some() || self.line_discount.is_some() || self.line_amount.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SalesInvoiceItem entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceItemResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub invoice_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub item_id: Uuid,
    pub sales_order_item_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub revenue_account_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_discount: Decimal,
    pub line_amount: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SalesInvoiceItem entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceItemListResponseDto {
    /// List of items
    pub items: Vec<SalesInvoiceItemResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SalesInvoiceItemListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SalesInvoiceItemResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesInvoiceItemSummaryDto {
    pub id: Uuid,
    pub invoice_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SalesInvoiceItem> for SalesInvoiceItemResponseDto {
    fn from(entity: SalesInvoiceItem) -> Self {
        Self {
            id: entity.id,
            invoice_id: entity.invoice_id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            sales_order_item_id: entity.sales_order_item_id,
            revenue_account_id: entity.revenue_account_id,
            description: entity.description,
            quantity: entity.quantity,
            unit_price: entity.unit_price,
            line_discount: entity.line_discount,
            line_amount: entity.line_amount,
            metadata: entity.metadata,
        }
    }
}

impl From<SalesInvoiceItem> for SalesInvoiceItemSummaryDto {
    fn from(entity: SalesInvoiceItem) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            invoice_id: entity.invoice_id,
            company_id: entity.company_id,
            item_id: entity.item_id,
            created_at,
        }
    }
}

impl From<CreateSalesInvoiceItemDto> for SalesInvoiceItem {
    fn from(dto: CreateSalesInvoiceItemDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            invoice_id: dto.invoice_id,
            company_id: dto.company_id,
            item_id: dto.item_id,
            sales_order_item_id: dto.sales_order_item_id,
            revenue_account_id: dto.revenue_account_id,
            description: dto.description,
            quantity: dto.quantity,
            unit_price: dto.unit_price,
            line_discount: dto.line_discount,
            line_amount: dto.line_amount,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SalesInvoiceItem> for SalesInvoiceItemResponseDto {
    fn from(entity: &SalesInvoiceItem) -> Self {
        Self {
            id: entity.id.clone(),
            invoice_id: entity.invoice_id.clone(),
            company_id: entity.company_id.clone(),
            item_id: entity.item_id.clone(),
            sales_order_item_id: entity.sales_order_item_id.clone(),
            revenue_account_id: entity.revenue_account_id.clone(),
            description: entity.description.clone(),
            quantity: entity.quantity.clone(),
            unit_price: entity.unit_price.clone(),
            line_discount: entity.line_discount.clone(),
            line_amount: entity.line_amount.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSalesInvoiceItemDto> for SalesInvoiceItem {
    fn from_create_dto(dto: CreateSalesInvoiceItemDto) -> backbone_core::ServiceResult<Self> {
        Ok(SalesInvoiceItem::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSalesInvoiceItemDto> for SalesInvoiceItem {
    fn apply_update(mut self, dto: UpdateSalesInvoiceItemDto) -> backbone_core::ServiceResult<Self> {
        self.invoice_id = dto.invoice_id;
        self.company_id = dto.company_id;
        self.item_id = dto.item_id;
        self.sales_order_item_id = dto.sales_order_item_id;
        self.revenue_account_id = dto.revenue_account_id;
        self.description = dto.description;
        self.quantity = dto.quantity;
        self.unit_price = dto.unit_price;
        self.line_discount = dto.line_discount;
        self.line_amount = dto.line_amount;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SalesInvoiceItem here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
