//! SalesOrder DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SalesOrder;
use crate::domain::entity::AuditMetadata;
use crate::domain::entity::SalesOrderStatus;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SalesOrder
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSalesOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "order_number")]
    pub order_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    pub status: SalesOrderStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "order_date")]
    pub order_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "delivery_date")]
    pub delivery_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    #[serde(alias = "tax_rate")]
    pub tax_rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
    pub total: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SalesOrder
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSalesOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(alias = "order_number")]
    pub order_number: String,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "company_id")]
    pub company_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "customer_id")]
    pub customer_id: Uuid,
    pub status: SalesOrderStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(alias = "order_date")]
    pub order_date: NaiveDate,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "delivery_date")]
    pub delivery_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    #[serde(alias = "tax_rate")]
    pub tax_rate: Decimal,
    #[serde(alias = "tax_amount")]
    pub tax_amount: Decimal,
    pub total: Decimal,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SalesOrder
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSalesOrderDto {
    #[cfg_attr(feature = "validation", validate(length(max = 40)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "order_number")]
    pub order_number: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "quotation_id")]
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "company_id")]
    pub company_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "branch_id")]
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "customer_id")]
    pub customer_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub status: Option<SalesOrderStatus>,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "order_date")]
    pub order_date: Option<NaiveDate>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "delivery_date")]
    pub delivery_date: Option<NaiveDate>,
    #[cfg_attr(feature = "validation", validate(length(max = 3)))]
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub currency: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub subtotal: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_rate")]
    pub tax_rate: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "tax_amount")]
    pub tax_amount: Option<Decimal>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub total: Option<Decimal>,
    #[cfg_attr(feature = "validation", validate(length(max = 1000)))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
}

impl PatchSalesOrderDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_number.is_some() || self.quotation_id.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.customer_id.is_some() || self.status.is_some() || self.order_date.is_some() || self.delivery_date.is_some() || self.currency.is_some() || self.subtotal.is_some() || self.tax_rate.is_some() || self.tax_amount.is_some() || self.total.is_some() || self.notes.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SalesOrder entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesOrderResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub order_number: String,
    pub quotation_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub customer_id: Uuid,
    pub status: SalesOrderStatus,
    #[cfg_attr(feature = "openapi", schema(example = "2024-01-01"))]
    pub order_date: NaiveDate,
    pub delivery_date: Option<NaiveDate>,
    #[cfg_attr(feature = "openapi", schema(example = "example"))]
    pub currency: String,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<String>,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SalesOrder entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesOrderListResponseDto {
    /// List of items
    pub items: Vec<SalesOrderResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SalesOrderListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SalesOrderResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesOrderSummaryDto {
    pub id: Uuid,
    pub order_number: String,
    pub quotation_id: Option<Uuid>,
    pub company_id: Uuid,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SalesOrder> for SalesOrderResponseDto {
    fn from(entity: SalesOrder) -> Self {
        Self {
            id: entity.id,
            order_number: entity.order_number,
            quotation_id: entity.quotation_id,
            company_id: entity.company_id,
            branch_id: entity.branch_id,
            customer_id: entity.customer_id,
            status: entity.status,
            order_date: entity.order_date,
            delivery_date: entity.delivery_date,
            currency: entity.currency,
            subtotal: entity.subtotal,
            tax_rate: entity.tax_rate,
            tax_amount: entity.tax_amount,
            total: entity.total,
            notes: entity.notes,
            metadata: entity.metadata,
        }
    }
}

impl From<SalesOrder> for SalesOrderSummaryDto {
    fn from(entity: SalesOrder) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_number: entity.order_number,
            quotation_id: entity.quotation_id,
            company_id: entity.company_id,
            created_at,
        }
    }
}

impl From<CreateSalesOrderDto> for SalesOrder {
    fn from(dto: CreateSalesOrderDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_number: dto.order_number,
            quotation_id: dto.quotation_id,
            company_id: dto.company_id,
            branch_id: dto.branch_id,
            customer_id: dto.customer_id,
            status: dto.status,
            order_date: dto.order_date,
            delivery_date: dto.delivery_date,
            currency: dto.currency,
            subtotal: dto.subtotal,
            tax_rate: dto.tax_rate,
            tax_amount: dto.tax_amount,
            total: dto.total,
            notes: dto.notes,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SalesOrder> for SalesOrderResponseDto {
    fn from(entity: &SalesOrder) -> Self {
        Self {
            id: entity.id.clone(),
            order_number: entity.order_number.clone(),
            quotation_id: entity.quotation_id.clone(),
            company_id: entity.company_id.clone(),
            branch_id: entity.branch_id.clone(),
            customer_id: entity.customer_id.clone(),
            status: entity.status.clone(),
            order_date: entity.order_date.clone(),
            delivery_date: entity.delivery_date.clone(),
            currency: entity.currency.clone(),
            subtotal: entity.subtotal.clone(),
            tax_rate: entity.tax_rate.clone(),
            tax_amount: entity.tax_amount.clone(),
            total: entity.total.clone(),
            notes: entity.notes.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSalesOrderDto> for SalesOrder {
    fn from_create_dto(dto: CreateSalesOrderDto) -> backbone_core::ServiceResult<Self> {
        Ok(SalesOrder::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSalesOrderDto> for SalesOrder {
    fn apply_update(mut self, dto: UpdateSalesOrderDto) -> backbone_core::ServiceResult<Self> {
        self.order_number = dto.order_number;
        self.quotation_id = dto.quotation_id;
        self.company_id = dto.company_id;
        self.branch_id = dto.branch_id;
        self.customer_id = dto.customer_id;
        self.status = dto.status;
        self.order_date = dto.order_date;
        self.delivery_date = dto.delivery_date;
        self.currency = dto.currency;
        self.subtotal = dto.subtotal;
        self.tax_rate = dto.tax_rate;
        self.tax_amount = dto.tax_amount;
        self.total = dto.total;
        self.notes = dto.notes;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SalesOrder here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
