//! SalesPersonAllocation DTOs (Data Transfer Objects)
//!
//! Auto-generated by metaphor-schema. Do not edit manually.
//!
//! DTOs provide a clean separation between domain entities and API
//! representations, with validation and OpenAPI documentation support.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc};
use rust_decimal::Decimal;

#[cfg(feature = "openapi")]
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

#[cfg(feature = "validation")]
use validator::Validate;

use crate::domain::entity::SalesPersonAllocation;
use crate::domain::entity::AuditMetadata;

// =============================================================================
// Create DTO
// =============================================================================

/// Request DTO for creating a new SalesPersonAllocation
///
/// Used in POST requests to create new entities.
/// Excludes auto-generated fields (id, created_at, updated_at, deleted_at).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct CreateSalesPersonAllocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "order_id")]
    pub order_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "sales_person_id")]
    pub sales_person_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_team_id")]
    pub sales_team_id: Option<Uuid>,
    #[serde(alias = "allocated_pct")]
    pub allocated_pct: Decimal,
}

// =============================================================================
// Update DTO
// =============================================================================

/// Request DTO for full update of a SalesPersonAllocation
///
/// Used in PUT requests for full entity replacement.
/// All fields are required (except auto-generated ones).
#[derive(Debug, Clone, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct UpdateSalesPersonAllocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "order_id")]
    pub order_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(alias = "sales_person_id")]
    pub sales_person_id: Uuid,
    #[serde(default, skip_serializing_if = "Option::is_none", alias = "sales_team_id")]
    pub sales_team_id: Option<Uuid>,
    #[serde(alias = "allocated_pct")]
    pub allocated_pct: Decimal,
}

// =============================================================================
// Patch DTO
// =============================================================================

/// Request DTO for partial update of a SalesPersonAllocation
///
/// Used in PATCH requests for partial updates.
/// All fields are optional - only provided fields will be updated.
#[derive(Debug, Clone, Default, Deserialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[cfg_attr(feature = "validation", derive(Validate))]
#[serde(rename_all = "camelCase")]
pub struct PatchSalesPersonAllocationDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "order_id")]
    pub order_id: Option<Uuid>,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_person_id")]
    pub sales_person_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "sales_team_id")]
    pub sales_team_id: Option<Uuid>,
    #[serde(skip_serializing_if = "Option::is_none", alias = "allocated_pct")]
    pub allocated_pct: Option<Decimal>,
}

impl PatchSalesPersonAllocationDto {
    /// Check if any field is set
    pub fn has_changes(&self) -> bool {
        self.order_id.is_some() || self.sales_person_id.is_some() || self.sales_team_id.is_some() || self.allocated_pct.is_some()
    }
}

// =============================================================================
// Response DTO
// =============================================================================

/// Response DTO for SalesPersonAllocation entity
///
/// Used in API responses for single entity.
/// Includes all fields including metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesPersonAllocationResponseDto {
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub order_id: Uuid,
    #[cfg_attr(feature = "openapi", schema(example = "550e8400-e29b-41d4-a716-446655440000"))]
    pub sales_person_id: Uuid,
    pub sales_team_id: Option<Uuid>,
    pub allocated_pct: Decimal,
    pub metadata: AuditMetadata,
}

// =============================================================================
// List Response DTO
// =============================================================================

/// Paginated list response for SalesPersonAllocation entities
///
/// Used in API responses for list endpoints.
/// Includes pagination metadata.
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesPersonAllocationListResponseDto {
    /// List of items
    pub items: Vec<SalesPersonAllocationResponseDto>,
    /// Total number of items (across all pages)
    pub total: u64,
    /// Current page number (1-indexed)
    pub page: u32,
    /// Number of items per page
    pub per_page: u32,
    /// Total number of pages
    pub total_pages: u32,
    /// Whether there is a next page
    pub has_next: bool,
    /// Whether there is a previous page
    pub has_prev: bool,
}

impl SalesPersonAllocationListResponseDto {
    /// Create a new list response from items and pagination info
    pub fn new(items: Vec<SalesPersonAllocationResponseDto>, total: u64, page: u32, per_page: u32) -> Self {
        let total_pages = if per_page > 0 {
            ((total as f64) / (per_page as f64)).ceil() as u32
        } else {
            0
        };
        Self {
            items,
            total,
            page,
            per_page,
            total_pages,
            has_next: page < total_pages,
            has_prev: page > 1,
        }
    }
}

/// Summary DTO for list views (compact version)
#[derive(Debug, Clone, Serialize)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
#[serde(rename_all = "camelCase")]
pub struct SalesPersonAllocationSummaryDto {
    pub id: Uuid,
    pub order_id: Uuid,
    pub sales_person_id: Uuid,
    pub sales_team_id: Option<Uuid>,
    pub created_at: Option<DateTime<Utc>>,
}

// =============================================================================
// Conversions
// =============================================================================

impl From<SalesPersonAllocation> for SalesPersonAllocationResponseDto {
    fn from(entity: SalesPersonAllocation) -> Self {
        Self {
            id: entity.id,
            order_id: entity.order_id,
            sales_person_id: entity.sales_person_id,
            sales_team_id: entity.sales_team_id,
            allocated_pct: entity.allocated_pct,
            metadata: entity.metadata,
        }
    }
}

impl From<SalesPersonAllocation> for SalesPersonAllocationSummaryDto {
    fn from(entity: SalesPersonAllocation) -> Self {
        let created_at = backbone_core::PersistentEntity::created_at(&entity);
        Self {
            id: entity.id,
            order_id: entity.order_id,
            sales_person_id: entity.sales_person_id,
            sales_team_id: entity.sales_team_id,
            created_at,
        }
    }
}

impl From<CreateSalesPersonAllocationDto> for SalesPersonAllocation {
    fn from(dto: CreateSalesPersonAllocationDto) -> Self {
        Self {
            id: Uuid::new_v4(),
            order_id: dto.order_id,
            sales_person_id: dto.sales_person_id,
            sales_team_id: dto.sales_team_id,
            allocated_pct: dto.allocated_pct,
            metadata: AuditMetadata::default(),
        }
    }
}

impl From<&SalesPersonAllocation> for SalesPersonAllocationResponseDto {
    fn from(entity: &SalesPersonAllocation) -> Self {
        Self {
            id: entity.id.clone(),
            order_id: entity.order_id.clone(),
            sales_person_id: entity.sales_person_id.clone(),
            sales_team_id: entity.sales_team_id.clone(),
            allocated_pct: entity.allocated_pct.clone(),
            metadata: entity.metadata.clone(),
        }
    }
}

impl backbone_core::FromCreateDto<CreateSalesPersonAllocationDto> for SalesPersonAllocation {
    fn from_create_dto(dto: CreateSalesPersonAllocationDto) -> backbone_core::ServiceResult<Self> {
        Ok(SalesPersonAllocation::from(dto))
    }
}

impl backbone_core::ApplyUpdateDto<UpdateSalesPersonAllocationDto> for SalesPersonAllocation {
    fn apply_update(mut self, dto: UpdateSalesPersonAllocationDto) -> backbone_core::ServiceResult<Self> {
        self.order_id = dto.order_id;
        self.sales_person_id = dto.sales_person_id;
        self.sales_team_id = dto.sales_team_id;
        self.allocated_pct = dto.allocated_pct;
        Ok(self)
    }
}

// =============================================================================
// Custom DTOs
// =============================================================================

// <<< CUSTOM DTOs
// Add custom DTOs specific to SalesPersonAllocation here.
// This section will be preserved during regeneration.
// >>> END CUSTOM DTOs
