//! Domain specifications
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Combinators (AND/OR/NOT) come from `backbone_core::Specification`.

pub use backbone_core::{Specification, AndSpecification, OrSpecification, NotSpecification};

pub mod quotation_specification;
pub mod quotation_item_specification;
pub mod sales_invoice_specification;
pub mod sales_invoice_item_specification;
pub mod sales_order_specification;
pub mod sales_order_item_specification;
pub mod sales_team_specification;
pub mod sales_person_allocation_specification;

// <<< CUSTOM
// END CUSTOM
