//! Domain policy for QuotationItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::QuotationItem;

/// Domain policy for QuotationItem — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<QuotationItem>` in the `// <<< CUSTOM` zone.
pub type QuotationItemDomainPolicy = PermitAllPolicy<QuotationItem>;

// <<< CUSTOM
// END CUSTOM
