//! Domain policy for SalesTeam aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! `DomainPolicy` enforces pure business invariants (state-based rules).
//! Identity-based rules live in `backbone_auth::ResourcePolicy`.

use backbone_core::PermitAllPolicy;
use crate::domain::entity::SalesTeam;

/// Domain policy for SalesTeam — permits all operations (no business invariants).
///
/// To add domain rules, replace this alias with a struct implementing
/// `backbone_core::DomainPolicy<SalesTeam>` in the `// <<< CUSTOM` zone.
pub type SalesTeamDomainPolicy = PermitAllPolicy<SalesTeam>;

// <<< CUSTOM
// END CUSTOM
