//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod quotation_service;
pub mod quotation_item_service;
pub mod sales_order_service;
pub mod sales_order_item_service;
// <<< CUSTOM
// Hand-authored (user-owned): domain events, the validated write path. (selling_gl + the invoice
// create/post chunks were removed when selling exited the invoice business — ADR-006.)
pub mod selling_events;
pub mod selling_cart_pricing;
pub mod selling_write_service;
// The write surface, chunked out of selling_write_service.rs. Each is an
// `impl SellingWriteService` block; the shared vocabulary (input structs, outcomes, errors,
// money/price helpers, the repository bag) stays in selling_write_service (so the
// `selling_write_service::{NewLine, ...}` import paths are unchanged).
pub mod selling_quotation;
pub mod selling_order;
pub mod selling_delivery_seam;
pub mod selling_invoice_seam;
// Reference consumer extension (extension-contract §5, second half) — a downstream rule on events.
pub mod consumer_credit_rule_custom;
// END CUSTOM
pub mod sales_team_service;
pub mod sales_person_allocation_service;

// <<< CUSTOM
// END CUSTOM

pub use quotation_service::QuotationService;
pub use quotation_item_service::QuotationItemService;
pub use sales_order_service::SalesOrderService;
pub use sales_order_item_service::SalesOrderItemService;
// <<< CUSTOM
pub use selling_events::{
    DeliveryRequestEnvelope, DeliveryRequestLine, InvoiceRequestEnvelope, InvoiceRequestLine,
    QuotationAccepted, SalesOrderConfirmed, SellingEvent, SellingEventSink,
};
pub use selling_cart_pricing::{
    CartPriceLine, CartPriceRequest, CartPricingError, CartPricingPort, PricedCart, PricedCartLine,
    PricedRewardLine,
};
pub use selling_write_service::{
    CartOrderLine, NewCartSalesOrder, NewLine, NewQuotation, NewSalesOrder, SellingError,
    SellingWriteService,
};
// END CUSTOM
pub use sales_team_service::SalesTeamService;
pub use sales_person_allocation_service::SalesPersonAllocationService;
// <<< CUSTOM
// END CUSTOM