//! Application services
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity service is a type alias over `GenericCrudService`.

pub mod error;
pub use error::{ServiceError, ServiceResult};

pub mod quotation_service;
pub mod quotation_item_service;
pub mod sales_invoice_service;
pub mod sales_invoice_item_service;
pub mod sales_order_service;
pub mod sales_order_item_service;
// <<< CUSTOM
// Hand-authored (user-owned): domain events, the outbound GL-posting port, the validated write path.
pub mod selling_events;
pub mod selling_gl;
pub mod selling_cart_pricing;
pub mod selling_write_service;
// Reference consumer extension (extension-contract §5, second half) — a downstream rule on events.
pub mod consumer_credit_rule_custom;
// END CUSTOM
pub mod sales_team_service;
pub mod sales_person_allocation_service;

// <<< CUSTOM
// END CUSTOM

pub use quotation_service::QuotationService;
pub use quotation_item_service::QuotationItemService;
pub use sales_invoice_service::SalesInvoiceService;
pub use sales_invoice_item_service::SalesInvoiceItemService;
pub use sales_order_service::SalesOrderService;
pub use sales_order_item_service::SalesOrderItemService;
// <<< CUSTOM
pub use selling_events::{
    DeliveryRequestEnvelope, DeliveryRequestLine, InvoiceRequestEnvelope, InvoiceRequestLine,
    QuotationAccepted, SalesInvoiceIssued, SalesInvoicePosted, SalesOrderConfirmed, SellingEvent,
    SellingEventSink,
};
pub use selling_gl::{
    AccountingPostEnvelope, GlPostAck, GlPostLine, GlPostRejected, GlPostSink,
};
pub use selling_cart_pricing::{
    CartPriceLine, CartPriceRequest, CartPricingError, CartPricingPort, PricedCart, PricedCartLine,
    PricedRewardLine,
};
pub use selling_write_service::{
    CartOrderLine, NewCartSalesOrder, NewLine, NewQuotation, NewSalesInvoice, NewSalesOrder,
    PostOutcome, SellingError, SellingWriteService,
};
// END CUSTOM
pub use sales_team_service::SalesTeamService;
pub use sales_person_allocation_service::SalesPersonAllocationService;
// <<< CUSTOM
// END CUSTOM