//! Application service for QuotationTemplate entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `quotation_template_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateQuotationTemplateDto, UpdateQuotationTemplateDto};
use crate::domain::entity::QuotationTemplate;
use crate::infrastructure::persistence::QuotationTemplateRepository;

/// Application service for QuotationTemplate entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `quotation_template_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct QuotationTemplateServiceCustom {
///     inner: Arc<QuotationTemplateService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type QuotationTemplateService = GenericCrudService<
    QuotationTemplate,
    CreateQuotationTemplateDto,
    UpdateQuotationTemplateDto,
    QuotationTemplateRepository,
>;

// <<< CUSTOM
// END CUSTOM
