//! Application service for SalesOrder entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Type alias over `GenericCrudService` — all CRUD logic lives in backbone-core.
//! For custom behaviour, create `sales_order_service_custom.rs` (preserved on regen).

use backbone_core::GenericCrudService;

use crate::presentation::dto::{CreateSalesOrderDto, UpdateSalesOrderDto};
use crate::domain::entity::SalesOrder;
use crate::infrastructure::persistence::SalesOrderRepository;

/// Application service for SalesOrder entities.
///
/// All 12 standard CRUD operations (list, create, get, update, patch,
/// soft_delete, restore, empty_trash, bulk_create, upsert, find_by_id,
/// list_deleted) are provided by `GenericCrudService`.
///
/// Custom extensions go in `sales_order_service_custom.rs`:
///
/// ```rust,ignore
/// pub struct SalesOrderServiceCustom {
///     inner: Arc<SalesOrderService>,
///     // add domain-specific dependencies here
/// }
/// ```
pub type SalesOrderService = GenericCrudService<
    SalesOrder,
    CreateSalesOrderDto,
    UpdateSalesOrderDto,
    SalesOrderRepository,
>;

// <<< CUSTOM
// END CUSTOM
