-- QuotationItem Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the selling.quotation_items table.
-- Customize this file to add your initial data.

-- INSERT INTO selling.quotation_items (
--     id,
--     quotation_id,
--     item_id,
--     description,
--     quantity,
--     unit_price,
--     line_discount,
--     line_amount,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO selling.quotation_items (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

