-- SalesPersonAllocation Seed Data
-- Generated by metaphor-schema
--
-- This file contains initial seed data for the selling.sales_person_allocations table.
-- Customize this file to add your initial data.

-- INSERT INTO selling.sales_person_allocations (
--     id,
--     order_id,
--     sales_person_id,
--     sales_team_id,
--     allocated_pct,
--     metadata
-- ) VALUES
-- (
--     -- Add values here
-- );

-- Example: Insert test data
-- Uncomment and modify the following for development/testing:

-- INSERT INTO selling.sales_person_allocations (id, created_at, updated_at) VALUES
--     (gen_random_uuid(), NOW(), NOW());

-- <<< CUSTOM SEED DATA >>>
-- Add your custom seed data below

