-- Migration: Create sales_orders table
-- Generated by metaphor-schema

-- Create sales_order_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_order_status') THEN
        CREATE TYPE sales_order_status AS ENUM ('draft', 'to_deliver', 'to_bill', 'to_deliver_and_bill', 'completed', 'closed', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.sales_orders (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_number TEXT NOT NULL,
    quotation_id UUID,
    company_id UUID NOT NULL,
    branch_id UUID,
    customer_id UUID NOT NULL,
    status sales_order_status NOT NULL DEFAULT 'draft',
    order_date DATE NOT NULL,
    delivery_date DATE,
    currency TEXT NOT NULL DEFAULT 'IDR',
    subtotal NUMERIC NOT NULL DEFAULT 0,
    tax_rate NUMERIC NOT NULL DEFAULT 0,
    tax_amount NUMERIC NOT NULL DEFAULT 0,
    total NUMERIC NOT NULL DEFAULT 0,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_orders_order_number ON selling.sales_orders (order_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_sales_orders_company_id_customer_id_status ON selling.sales_orders (company_id, customer_id, status);

CREATE INDEX IF NOT EXISTS idx_sales_orders_order_date ON selling.sales_orders (order_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_sales_orders_metadata_gin ON selling.sales_orders USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_sales_orders_metadata_deleted_at ON selling.sales_orders ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_sales_orders_metadata_created_at ON selling.sales_orders ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_sales_orders_metadata_updated_at ON selling.sales_orders ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.sales_orders_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_orders_insert_audit ON selling.sales_orders;
CREATE TRIGGER sales_orders_insert_audit BEFORE INSERT ON selling.sales_orders
    FOR EACH ROW EXECUTE FUNCTION selling.sales_orders_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_orders_update_audit ON selling.sales_orders;
CREATE TRIGGER sales_orders_update_audit BEFORE UPDATE ON selling.sales_orders
    FOR EACH ROW EXECUTE FUNCTION selling.sales_orders_audit_timestamp();
