-- Migration: Create sales_invoices table
-- Generated by metaphor-schema

-- Create sales_invoice_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_invoice_status') THEN
        CREATE TYPE sales_invoice_status AS ENUM ('draft', 'submitted', 'partially_paid', 'paid', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.sales_invoices (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    invoice_number TEXT NOT NULL,
    sales_order_id UUID,
    company_id UUID NOT NULL,
    branch_id UUID,
    customer_id UUID NOT NULL,
    status sales_invoice_status NOT NULL DEFAULT 'draft',
    invoice_date DATE NOT NULL,
    due_date DATE,
    currency TEXT NOT NULL DEFAULT 'IDR',
    subtotal NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (subtotal >= 0),
    tax_rate NUMERIC(9, 4) NOT NULL DEFAULT 0 CHECK (tax_rate >= 0),
    tax_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (tax_amount >= 0),
    total NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (total >= 0),
    outstanding_amount NUMERIC(18, 2) NOT NULL DEFAULT 0 CHECK (outstanding_amount >= 0),
    receivable_account_id UUID NOT NULL,
    tax_output_account_id UUID,
    posting_state gl_posting_state NOT NULL DEFAULT 'pending',
    journal_id UUID,
    accounting_post_id UUID,
    posted_at TIMESTAMPTZ,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_sales_invoices_invoice_number ON selling.sales_invoices (invoice_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_sales_invoices_company_id_customer_id_status ON selling.sales_invoices (company_id, customer_id, status);

CREATE INDEX IF NOT EXISTS idx_sales_invoices_posting_state ON selling.sales_invoices (posting_state);

CREATE INDEX IF NOT EXISTS idx_sales_invoices_invoice_date ON selling.sales_invoices (invoice_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_sales_invoices_metadata_gin ON selling.sales_invoices USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_sales_invoices_metadata_deleted_at ON selling.sales_invoices ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_sales_invoices_metadata_created_at ON selling.sales_invoices ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_sales_invoices_metadata_updated_at ON selling.sales_invoices ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.sales_invoices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_invoices_insert_audit ON selling.sales_invoices;
CREATE TRIGGER sales_invoices_insert_audit BEFORE INSERT ON selling.sales_invoices
    FOR EACH ROW EXECUTE FUNCTION selling.sales_invoices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_invoices_update_audit ON selling.sales_invoices;
CREATE TRIGGER sales_invoices_update_audit BEFORE UPDATE ON selling.sales_invoices
    FOR EACH ROW EXECUTE FUNCTION selling.sales_invoices_audit_timestamp();
