-- Migration: Create delivery_carriers table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.delivery_carriers (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    tracking_url_template TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_delivery_carriers_metadata_gin ON selling.delivery_carriers USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_delivery_carriers_metadata_deleted_at ON selling.delivery_carriers ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_delivery_carriers_metadata_created_at ON selling.delivery_carriers ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_delivery_carriers_metadata_updated_at ON selling.delivery_carriers ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.delivery_carriers_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS delivery_carriers_insert_audit ON selling.delivery_carriers;
CREATE TRIGGER delivery_carriers_insert_audit BEFORE INSERT ON selling.delivery_carriers
    FOR EACH ROW EXECUTE FUNCTION selling.delivery_carriers_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS delivery_carriers_update_audit ON selling.delivery_carriers;
CREATE TRIGGER delivery_carriers_update_audit BEFORE UPDATE ON selling.delivery_carriers
    FOR EACH ROW EXECUTE FUNCTION selling.delivery_carriers_audit_timestamp();
