-- Migration: Create quotations table
-- Generated by metaphor-schema

-- Create quotation_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quotation_status') THEN
        CREATE TYPE quotation_status AS ENUM ('draft', 'sent', 'accepted', 'ordered', 'rejected', 'expired', 'cancelled');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.quotations (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    quotation_number TEXT NOT NULL,
    company_id UUID NOT NULL,
    branch_id UUID,
    customer_id UUID NOT NULL,
    status quotation_status NOT NULL DEFAULT 'draft',
    quotation_date DATE NOT NULL,
    valid_until DATE,
    currency TEXT NOT NULL DEFAULT 'IDR',
    subtotal NUMERIC NOT NULL DEFAULT 0,
    tax_rate NUMERIC NOT NULL DEFAULT 0,
    tax_amount NUMERIC NOT NULL DEFAULT 0,
    total NUMERIC NOT NULL DEFAULT 0,
    notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_quotations_quotation_number ON selling.quotations (quotation_number) WHERE (metadata->>'deleted_at') IS NULL;

CREATE INDEX IF NOT EXISTS idx_quotations_company_id_customer_id_status ON selling.quotations (company_id, customer_id, status);

CREATE INDEX IF NOT EXISTS idx_quotations_quotation_date ON selling.quotations (quotation_date);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quotations_metadata_gin ON selling.quotations USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quotations_metadata_deleted_at ON selling.quotations ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quotations_metadata_created_at ON selling.quotations ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quotations_metadata_updated_at ON selling.quotations ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.quotations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quotations_insert_audit ON selling.quotations;
CREATE TRIGGER quotations_insert_audit BEFORE INSERT ON selling.quotations
    FOR EACH ROW EXECUTE FUNCTION selling.quotations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quotations_update_audit ON selling.quotations;
CREATE TRIGGER quotations_update_audit BEFORE UPDATE ON selling.quotations
    FOR EACH ROW EXECUTE FUNCTION selling.quotations_audit_timestamp();
