-- Migration: Create expense_reinvoice_links table
-- Generated by metaphor-schema

-- Create expense_reinvoice_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'expense_reinvoice_state') THEN
        CREATE TYPE expense_reinvoice_state AS ENUM ('pending', 'invoiced');
    END IF;
END
$$;

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.expense_reinvoice_links (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    expense_id UUID NOT NULL,
    amount NUMERIC(18, 2) NOT NULL CHECK (amount >= 0),
    state expense_reinvoice_state NOT NULL DEFAULT 'pending',
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_expense_reinvoice_links_order_id_expense_id ON selling.expense_reinvoice_links (order_id, expense_id) WHERE (metadata->>'deleted_at') IS NULL;

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_expense_reinvoice_links_metadata_gin ON selling.expense_reinvoice_links USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_expense_reinvoice_links_metadata_deleted_at ON selling.expense_reinvoice_links ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_expense_reinvoice_links_metadata_created_at ON selling.expense_reinvoice_links ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_expense_reinvoice_links_metadata_updated_at ON selling.expense_reinvoice_links ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.expense_reinvoice_links_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS expense_reinvoice_links_insert_audit ON selling.expense_reinvoice_links;
CREATE TRIGGER expense_reinvoice_links_insert_audit BEFORE INSERT ON selling.expense_reinvoice_links
    FOR EACH ROW EXECUTE FUNCTION selling.expense_reinvoice_links_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS expense_reinvoice_links_update_audit ON selling.expense_reinvoice_links;
CREATE TRIGGER expense_reinvoice_links_update_audit BEFORE UPDATE ON selling.expense_reinvoice_links
    FOR EACH ROW EXECUTE FUNCTION selling.expense_reinvoice_links_audit_timestamp();
