-- Migration: Create quotation_templates table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.quotation_templates (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    validity_days INTEGER NOT NULL DEFAULT 30,
    default_notes TEXT,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_quotation_templates_metadata_gin ON selling.quotation_templates USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_quotation_templates_metadata_deleted_at ON selling.quotation_templates ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_quotation_templates_metadata_created_at ON selling.quotation_templates ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_quotation_templates_metadata_updated_at ON selling.quotation_templates ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.quotation_templates_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quotation_templates_insert_audit ON selling.quotation_templates;
CREATE TRIGGER quotation_templates_insert_audit BEFORE INSERT ON selling.quotation_templates
    FOR EACH ROW EXECUTE FUNCTION selling.quotation_templates_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quotation_templates_update_audit ON selling.quotation_templates;
CREATE TRIGGER quotation_templates_update_audit BEFORE UPDATE ON selling.quotation_templates
    FOR EACH ROW EXECUTE FUNCTION selling.quotation_templates_audit_timestamp();
