-- ADR-0010 Decision A: direct company_id + FORCE RLS fence on the unfenced child tables.
--
-- The four child tables (quotation_items, sales_order_items, sales_invoice_items,
-- sales_person_allocations) previously had NO company_id and no RLS policy; reads/writes rode
-- the request-scoped connection but nothing in the DB actually fenced a line to its parent's
-- company. This adds a denormalized `company_id` (backfilled from each parent) and the
-- ADR-0008 invariant #1 policy:
--     company_id = NULLIF(current_setting('app.company_id', true), '')::uuid
-- The NULLIF is mandatory: an unset `app.company_id` reads as ''::text → NULL::uuid → the
-- predicate is `company_id = NULL` which is never true, so an unset scope sees zero rows.
--
-- Company is a LOGICAL FK only (matches the module's convention: every parent table carries
-- company_id as @exclude_from_foreign_key_check with NO DB constraint into organization).
-- Quotation.model.yaml's header is explicit: cross-module refs (customer/item/company/branch)
-- are logical. Adding a hard FK to organization.companies would diverge from the parents and
-- couple this module's migration to another module's schema provisioning order.
--
-- Sequence per table (idempotent where possible):
--   1. ADD COLUMN company_id UUID (nullable)
--   2. BACKFILL from parent via the child's parent FK
--   3. SET NOT NULL
--   4. ENABLE + FORCE ROW LEVEL SECURITY
--   5. CREATE POLICY … FOR ALL USING + WITH CHECK
--
-- Hand-written. NOT generated by metaphor-schema (do not regenerate).

-- ===========================================================================
-- 1. selling.quotation_items  (parent FK: quotation_id → selling.quotations.id)
-- ===========================================================================
ALTER TABLE selling.quotation_items ADD COLUMN IF NOT EXISTS company_id UUID;

UPDATE selling.quotation_items AS child
   SET company_id = parent.company_id
  FROM selling.quotations AS parent
 WHERE child.quotation_id = parent.id
   AND child.company_id IS NULL;

ALTER TABLE selling.quotation_items ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE selling.quotation_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE selling.quotation_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS quotation_items_company_isolation ON selling.quotation_items;
CREATE POLICY quotation_items_company_isolation ON selling.quotation_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

CREATE INDEX IF NOT EXISTS idx_quotation_items_company_id ON selling.quotation_items (company_id);

-- ===========================================================================
-- 2. selling.sales_order_items  (parent FK: order_id → selling.sales_orders.id)
-- ===========================================================================
ALTER TABLE selling.sales_order_items ADD COLUMN IF NOT EXISTS company_id UUID;

UPDATE selling.sales_order_items AS child
   SET company_id = parent.company_id
  FROM selling.sales_orders AS parent
 WHERE child.order_id = parent.id
   AND child.company_id IS NULL;

ALTER TABLE selling.sales_order_items ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE selling.sales_order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE selling.sales_order_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sales_order_items_company_isolation ON selling.sales_order_items;
CREATE POLICY sales_order_items_company_isolation ON selling.sales_order_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

CREATE INDEX IF NOT EXISTS idx_sales_order_items_company_id ON selling.sales_order_items (company_id);

-- ===========================================================================
-- 3. selling.sales_invoice_items  (parent FK: invoice_id → selling.sales_invoices.id)
-- ===========================================================================
ALTER TABLE selling.sales_invoice_items ADD COLUMN IF NOT EXISTS company_id UUID;

UPDATE selling.sales_invoice_items AS child
   SET company_id = parent.company_id
  FROM selling.sales_invoices AS parent
 WHERE child.invoice_id = parent.id
   AND child.company_id IS NULL;

ALTER TABLE selling.sales_invoice_items ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE selling.sales_invoice_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE selling.sales_invoice_items FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sales_invoice_items_company_isolation ON selling.sales_invoice_items;
CREATE POLICY sales_invoice_items_company_isolation ON selling.sales_invoice_items
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

CREATE INDEX IF NOT EXISTS idx_sales_invoice_items_company_id ON selling.sales_invoice_items (company_id);

-- ===========================================================================
-- 4. selling.sales_person_allocations  (parent FK: order_id → selling.sales_orders.id)
-- ===========================================================================
ALTER TABLE selling.sales_person_allocations ADD COLUMN IF NOT EXISTS company_id UUID;

UPDATE selling.sales_person_allocations AS child
   SET company_id = parent.company_id
  FROM selling.sales_orders AS parent
 WHERE child.order_id = parent.id
   AND child.company_id IS NULL;

ALTER TABLE selling.sales_person_allocations ALTER COLUMN company_id SET NOT NULL;

ALTER TABLE selling.sales_person_allocations ENABLE ROW LEVEL SECURITY;
ALTER TABLE selling.sales_person_allocations FORCE  ROW LEVEL SECURITY;
DROP POLICY IF EXISTS sales_person_allocations_company_isolation ON selling.sales_person_allocations;
CREATE POLICY sales_person_allocations_company_isolation ON selling.sales_person_allocations
    FOR ALL
    USING      (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid)
    WITH CHECK (company_id = NULLIF(current_setting('app.company_id', true), '')::uuid);

CREATE INDEX IF NOT EXISTS idx_sales_person_allocations_company_id ON selling.sales_person_allocations (company_id);
