-- Migration: Create sales_order_items table
-- Generated by metaphor-schema

CREATE SCHEMA IF NOT EXISTS selling;

CREATE TABLE IF NOT EXISTS selling.sales_order_items (
    id UUID NOT NULL DEFAULT gen_random_uuid(),
    order_id UUID NOT NULL,
    item_id UUID NOT NULL,
    description TEXT,
    quantity NUMERIC NOT NULL,
    unit_price NUMERIC NOT NULL,
    line_discount NUMERIC NOT NULL DEFAULT 0,
    line_amount NUMERIC NOT NULL DEFAULT 0,
    billed_qty NUMERIC NOT NULL DEFAULT 0,
    delivered_qty NUMERIC NOT NULL DEFAULT 0,
    metadata JSONB NOT NULL DEFAULT '{"created_at":null,"updated_at":null,"deleted_at":null,"created_by":null,"updated_by":null,"deleted_by":null}'::jsonb,
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS idx_sales_order_items_order_id ON selling.sales_order_items (order_id);

-- GIN index for audit metadata JSONB queries
CREATE INDEX IF NOT EXISTS idx_sales_order_items_metadata_gin ON selling.sales_order_items USING GIN (metadata);
CREATE INDEX IF NOT EXISTS idx_sales_order_items_metadata_deleted_at ON selling.sales_order_items ((metadata->>'deleted_at'));
CREATE INDEX IF NOT EXISTS idx_sales_order_items_metadata_created_at ON selling.sales_order_items ((metadata->>'created_at'));
CREATE INDEX IF NOT EXISTS idx_sales_order_items_metadata_updated_at ON selling.sales_order_items ((metadata->>'updated_at'));

-- Triggers for automatic metadata timestamp management
-- Automatically sets created_at on INSERT and updated_at on UPDATE

-- Function to set metadata->'created_at' on INSERT
CREATE OR REPLACE FUNCTION selling.sales_order_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_order_items_insert_audit ON selling.sales_order_items;
CREATE TRIGGER sales_order_items_insert_audit BEFORE INSERT ON selling.sales_order_items
    FOR EACH ROW EXECUTE FUNCTION selling.sales_order_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_order_items_update_audit ON selling.sales_order_items;
CREATE TRIGGER sales_order_items_update_audit BEFORE UPDATE ON selling.sales_order_items
    FOR EACH ROW EXECUTE FUNCTION selling.sales_order_items_audit_timestamp();

-- Inline foreign key constraints (forward + self refs)
ALTER TABLE selling.sales_order_items ADD CONSTRAINT fk_sales_order_items_order_id FOREIGN KEY (order_id) REFERENCES selling.sales_orders (id);
