-- Enum types for selling module
-- Generated by metaphor-schema

-- Create quotation_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quotation_status') THEN
        CREATE TYPE quotation_status AS ENUM ('draft', 'sent', 'accepted', 'ordered', 'rejected', 'expired', 'cancelled');
    END IF;
END
$$;

-- Create sales_invoice_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_invoice_status') THEN
        CREATE TYPE sales_invoice_status AS ENUM ('draft', 'submitted', 'partially_paid', 'paid', 'cancelled');
    END IF;
END
$$;

-- Create gl_posting_state enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'gl_posting_state') THEN
        CREATE TYPE gl_posting_state AS ENUM ('pending', 'posted', 'failed');
    END IF;
END
$$;

-- Create sales_order_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_order_status') THEN
        CREATE TYPE sales_order_status AS ENUM ('draft', 'to_deliver', 'to_bill', 'to_deliver_and_bill', 'completed', 'closed', 'cancelled');
    END IF;
END
$$;

