-- Enum types for selling module
-- Generated by metaphor-schema

-- Create quotation_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'quotation_status') THEN
        CREATE TYPE quotation_status AS ENUM ('draft', 'sent', 'accepted', 'ordered', 'rejected', 'expired', 'cancelled');
    END IF;
END
$$;

-- Create sales_order_status enum type
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'sales_order_status') THEN
        CREATE TYPE sales_order_status AS ENUM ('draft', 'to_deliver', 'to_bill', 'to_deliver_and_bill', 'completed', 'closed', 'cancelled');
    END IF;
END
$$;

