-- Audit Triggers Migration for selling module
-- Generated by metaphor-schema
--
-- This migration adds automatic timestamp management triggers
-- to all tables with audit metadata fields.
--
-- Triggers automatically set:
--   - metadata->'created_at' on INSERT
--   - metadata->'updated_at' on INSERT and UPDATE

-- ==============================================================================
-- Table: Quotation (selling.quotations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.quotations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quotations_insert_audit ON selling.quotations;
CREATE TRIGGER quotations_insert_audit BEFORE INSERT ON selling.quotations
    FOR EACH ROW EXECUTE FUNCTION selling.quotations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quotations_update_audit ON selling.quotations;
CREATE TRIGGER quotations_update_audit BEFORE UPDATE ON selling.quotations
    FOR EACH ROW EXECUTE FUNCTION selling.quotations_audit_timestamp();

-- ==============================================================================
-- Table: QuotationItem (selling.quotation_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.quotation_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS quotation_items_insert_audit ON selling.quotation_items;
CREATE TRIGGER quotation_items_insert_audit BEFORE INSERT ON selling.quotation_items
    FOR EACH ROW EXECUTE FUNCTION selling.quotation_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS quotation_items_update_audit ON selling.quotation_items;
CREATE TRIGGER quotation_items_update_audit BEFORE UPDATE ON selling.quotation_items
    FOR EACH ROW EXECUTE FUNCTION selling.quotation_items_audit_timestamp();

-- ==============================================================================
-- Table: SalesInvoice (selling.sales_invoices)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.sales_invoices_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_invoices_insert_audit ON selling.sales_invoices;
CREATE TRIGGER sales_invoices_insert_audit BEFORE INSERT ON selling.sales_invoices
    FOR EACH ROW EXECUTE FUNCTION selling.sales_invoices_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_invoices_update_audit ON selling.sales_invoices;
CREATE TRIGGER sales_invoices_update_audit BEFORE UPDATE ON selling.sales_invoices
    FOR EACH ROW EXECUTE FUNCTION selling.sales_invoices_audit_timestamp();

-- ==============================================================================
-- Table: SalesInvoiceItem (selling.sales_invoice_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.sales_invoice_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_invoice_items_insert_audit ON selling.sales_invoice_items;
CREATE TRIGGER sales_invoice_items_insert_audit BEFORE INSERT ON selling.sales_invoice_items
    FOR EACH ROW EXECUTE FUNCTION selling.sales_invoice_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_invoice_items_update_audit ON selling.sales_invoice_items;
CREATE TRIGGER sales_invoice_items_update_audit BEFORE UPDATE ON selling.sales_invoice_items
    FOR EACH ROW EXECUTE FUNCTION selling.sales_invoice_items_audit_timestamp();

-- ==============================================================================
-- Table: SalesOrder (selling.sales_orders)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.sales_orders_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_orders_insert_audit ON selling.sales_orders;
CREATE TRIGGER sales_orders_insert_audit BEFORE INSERT ON selling.sales_orders
    FOR EACH ROW EXECUTE FUNCTION selling.sales_orders_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_orders_update_audit ON selling.sales_orders;
CREATE TRIGGER sales_orders_update_audit BEFORE UPDATE ON selling.sales_orders
    FOR EACH ROW EXECUTE FUNCTION selling.sales_orders_audit_timestamp();

-- ==============================================================================
-- Table: SalesOrderItem (selling.sales_order_items)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.sales_order_items_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_order_items_insert_audit ON selling.sales_order_items;
CREATE TRIGGER sales_order_items_insert_audit BEFORE INSERT ON selling.sales_order_items
    FOR EACH ROW EXECUTE FUNCTION selling.sales_order_items_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_order_items_update_audit ON selling.sales_order_items;
CREATE TRIGGER sales_order_items_update_audit BEFORE UPDATE ON selling.sales_order_items
    FOR EACH ROW EXECUTE FUNCTION selling.sales_order_items_audit_timestamp();

-- ==============================================================================
-- Table: SalesTeam (selling.sales_teams)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.sales_teams_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_teams_insert_audit ON selling.sales_teams;
CREATE TRIGGER sales_teams_insert_audit BEFORE INSERT ON selling.sales_teams
    FOR EACH ROW EXECUTE FUNCTION selling.sales_teams_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_teams_update_audit ON selling.sales_teams;
CREATE TRIGGER sales_teams_update_audit BEFORE UPDATE ON selling.sales_teams
    FOR EACH ROW EXECUTE FUNCTION selling.sales_teams_audit_timestamp();

-- ==============================================================================
-- Table: SalesPersonAllocation (selling.sales_person_allocations)
-- ==============================================================================

-- Function to set metadata timestamps
CREATE OR REPLACE FUNCTION selling.sales_person_allocations_audit_timestamp() RETURNS trigger AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{created_at}', to_jsonb(NOW()));
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    ELSIF TG_OP = 'UPDATE' THEN
        NEW.metadata = jsonb_set(NEW.metadata::jsonb, '{updated_at}', to_jsonb(NOW()));
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to set timestamps on INSERT
DROP TRIGGER IF EXISTS sales_person_allocations_insert_audit ON selling.sales_person_allocations;
CREATE TRIGGER sales_person_allocations_insert_audit BEFORE INSERT ON selling.sales_person_allocations
    FOR EACH ROW EXECUTE FUNCTION selling.sales_person_allocations_audit_timestamp();

-- Trigger to set updated_at on UPDATE
DROP TRIGGER IF EXISTS sales_person_allocations_update_audit ON selling.sales_person_allocations;
CREATE TRIGGER sales_person_allocations_update_audit BEFORE UPDATE ON selling.sales_person_allocations
    FOR EACH ROW EXECUTE FUNCTION selling.sales_person_allocations_audit_timestamp();

