//! Domain events for DeliveryCarrier entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::DeliveryCarrier;

/// Domain events for DeliveryCarrier — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<DeliveryCarrier>)` variant.
pub type DeliveryCarrierEvent = CrudEvent<DeliveryCarrier>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for DeliveryCarrier events.
pub type DeliveryCarrierEventPublisher = Arc<dyn CrudEventPublisher<DeliveryCarrier> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopDeliveryCarrierEventPublisher = NoOpCrudEventPublisher<DeliveryCarrier>;
