//! Event handler trait for DeliveryCarrier events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::DeliveryCarrierEvent;

/// Event handler for DeliveryCarrier events.
/// Implement this trait to react to DeliveryCarrier lifecycle events.
pub trait DeliveryCarrierEventHandler: EventHandler<DeliveryCarrierEvent> {}
