//! Domain events for ExpenseReinvoiceLink entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::ExpenseReinvoiceLink;

/// Domain events for ExpenseReinvoiceLink — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<ExpenseReinvoiceLink>)` variant.
pub type ExpenseReinvoiceLinkEvent = CrudEvent<ExpenseReinvoiceLink>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for ExpenseReinvoiceLink events.
pub type ExpenseReinvoiceLinkEventPublisher = Arc<dyn CrudEventPublisher<ExpenseReinvoiceLink> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopExpenseReinvoiceLinkEventPublisher = NoOpCrudEventPublisher<ExpenseReinvoiceLink>;
