//! Event handler trait for QuotationTemplate events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QuotationTemplateEvent;

/// Event handler for QuotationTemplate events.
/// Implement this trait to react to QuotationTemplate lifecycle events.
pub trait QuotationTemplateEventHandler: EventHandler<QuotationTemplateEvent> {}
