//! Event handler trait for QuotationItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::QuotationItemEvent;

/// Event handler for QuotationItem events.
/// Implement this trait to react to QuotationItem lifecycle events.
pub trait QuotationItemEventHandler: EventHandler<QuotationItemEvent> {}
