//! Domain events for QuotationItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::QuotationItem;

/// Domain events for QuotationItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<QuotationItem>)` variant.
pub type QuotationItemEvent = CrudEvent<QuotationItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for QuotationItem events.
pub type QuotationItemEventPublisher = Arc<dyn CrudEventPublisher<QuotationItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQuotationItemEventPublisher = NoOpCrudEventPublisher<QuotationItem>;
