//! Domain events for Quotation entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::Quotation;

/// Domain events for Quotation — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<Quotation>)` variant.
pub type QuotationEvent = CrudEvent<Quotation>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for Quotation events.
pub type QuotationEventPublisher = Arc<dyn CrudEventPublisher<Quotation> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopQuotationEventPublisher = NoOpCrudEventPublisher<Quotation>;
