//! Domain events for SalesOrderItem entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalesOrderItem;

/// Domain events for SalesOrderItem — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalesOrderItem>)` variant.
pub type SalesOrderItemEvent = CrudEvent<SalesOrderItem>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalesOrderItem events.
pub type SalesOrderItemEventPublisher = Arc<dyn CrudEventPublisher<SalesOrderItem> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalesOrderItemEventPublisher = NoOpCrudEventPublisher<SalesOrderItem>;
