//! Event handler trait for SalesInvoice events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalesInvoiceEvent;

/// Event handler for SalesInvoice events.
/// Implement this trait to react to SalesInvoice lifecycle events.
pub trait SalesInvoiceEventHandler: EventHandler<SalesInvoiceEvent> {}
