//! Event handler trait for SalesPersonAllocation events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalesPersonAllocationEvent;

/// Event handler for SalesPersonAllocation events.
/// Implement this trait to react to SalesPersonAllocation lifecycle events.
pub trait SalesPersonAllocationEventHandler: EventHandler<SalesPersonAllocationEvent> {}
