//! Event handler trait for SalesInvoiceItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalesInvoiceItemEvent;

/// Event handler for SalesInvoiceItem events.
/// Implement this trait to react to SalesInvoiceItem lifecycle events.
pub trait SalesInvoiceItemEventHandler: EventHandler<SalesInvoiceItemEvent> {}
