//! Event handler trait for SalesOrderItem events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalesOrderItemEvent;

/// Event handler for SalesOrderItem events.
/// Implement this trait to react to SalesOrderItem lifecycle events.
pub trait SalesOrderItemEventHandler: EventHandler<SalesOrderItemEvent> {}
