//! Domain events for SalesOrder entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalesOrder;

/// Domain events for SalesOrder — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalesOrder>)` variant.
pub type SalesOrderEvent = CrudEvent<SalesOrder>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalesOrder events.
pub type SalesOrderEventPublisher = Arc<dyn CrudEventPublisher<SalesOrder> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalesOrderEventPublisher = NoOpCrudEventPublisher<SalesOrder>;
