//! Domain events for SalesInvoice entity
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::CrudEvent;
use crate::domain::entity::SalesInvoice;

/// Domain events for SalesInvoice — type alias over the generic CrudEvent.
///
/// To add entity-specific events, replace this alias with a wrapper
/// enum containing a `Crud(CrudEvent<SalesInvoice>)` variant.
pub type SalesInvoiceEvent = CrudEvent<SalesInvoice>;

// <<< CUSTOM
// END CUSTOM

use backbone_messaging::{CrudEventPublisher, NoOpCrudEventPublisher};
use std::sync::Arc;

/// Publisher alias for SalesInvoice events.
pub type SalesInvoiceEventPublisher = Arc<dyn CrudEventPublisher<SalesInvoice> + Send + Sync>;

/// No-op publisher — discards events silently (useful in tests).
pub type NoopSalesInvoiceEventPublisher = NoOpCrudEventPublisher<SalesInvoice>;
