//! Event handler trait for SalesTeam events
//!
//! Generated by metaphor-schema. Do not edit manually.

use backbone_messaging::EventHandler;
use super::SalesTeamEvent;

/// Event handler for SalesTeam events.
/// Implement this trait to react to SalesTeam lifecycle events.
pub trait SalesTeamEventHandler: EventHandler<SalesTeamEvent> {}
