//! DeliveryCarrier seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial DeliveryCarrier data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// DELIVERYCARRIER SEEDER
// ============================================================================

/// Seeder for delivery_carrier
pub struct SeedDeliveryCarrierSeeder;

impl SeedDeliveryCarrierSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedDeliveryCarrierSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedDeliveryCarrierSeeder {
    fn name(&self) -> &'static str {
        "SeedDeliveryCarrierSeeder"
    }

    fn order(&self) -> i32 {
        1
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if selling.delivery_carriers table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM selling.delivery_carriers")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/delivery_carrier_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM selling.delivery_carriers")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
