//! ExpenseReinvoiceLink seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial ExpenseReinvoiceLink data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// EXPENSEREINVOICELINK SEEDER
// ============================================================================

/// Seeder for expense_reinvoice_link
pub struct SeedExpenseReinvoiceLinkSeeder;

impl SeedExpenseReinvoiceLinkSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedExpenseReinvoiceLinkSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedExpenseReinvoiceLinkSeeder {
    fn name(&self) -> &'static str {
        "SeedExpenseReinvoiceLinkSeeder"
    }

    fn order(&self) -> i32 {
        2
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if selling.expense_reinvoice_links table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM selling.expense_reinvoice_links")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/expense_reinvoice_link_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM selling.expense_reinvoice_links")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>
