//! Database seeders for the selling module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides seed data for initial database setup.
//! Seeders can be run via the seeder binary or CLI.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

mod quotation_seeder;
mod quotation_item_seeder;
mod sales_invoice_seeder;
mod sales_invoice_item_seeder;
mod sales_order_seeder;
mod sales_order_item_seeder;
mod sales_team_seeder;
mod sales_person_allocation_seeder;

pub use quotation_seeder::SeedQuotationSeeder;
pub use quotation_item_seeder::SeedQuotationItemSeeder;
pub use sales_invoice_seeder::SeedSalesInvoiceSeeder;
pub use sales_invoice_item_seeder::SeedSalesInvoiceItemSeeder;
pub use sales_order_seeder::SeedSalesOrderSeeder;
pub use sales_order_item_seeder::SeedSalesOrderItemSeeder;
pub use sales_team_seeder::SeedSalesTeamSeeder;
pub use sales_person_allocation_seeder::SeedSalesPersonAllocationSeeder;

// ============================================================================
// SEEDER TRAIT
// ============================================================================

/// Trait for database seeders
#[async_trait]
pub trait Seeder {
    /// Get the name of this seeder
    fn name(&self) -> &'static str;

    /// Get the order in which this seeder should run
    fn order(&self) -> i32;

    /// Check if this seeder should run (e.g., check if data already exists)
    async fn should_run(&self, pool: &PgPool) -> Result<bool>;

    /// Run the seeder
    async fn run(&self, pool: &PgPool) -> Result<()>;

    /// Rollback the seeder (optional)
    async fn rollback(&self, _pool: &PgPool) -> Result<()> {
        Ok(())
    }
}

// ============================================================================
// SEEDER TYPE
// ============================================================================

/// Type of seeder
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SeederType {
    /// Reference data (required for application to function)
    Reference,
    /// Initial production data
    Production,
    /// Development/testing data
    Development,
    /// Test data (for automated tests)
    Test,
// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here.
}

// ============================================================================
// CUSTOM SEEDERS
// ============================================================================

// <<< CUSTOM SEEDERS START >>>
// Add custom seeders here
// <<< CUSTOM SEEDERS END >>>
