//! SalesPersonAllocation seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SalesPersonAllocation data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SALESPERSONALLOCATION SEEDER
// ============================================================================

/// Seeder for sales_person_allocation
pub struct SeedSalesPersonAllocationSeeder;

impl SeedSalesPersonAllocationSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSalesPersonAllocationSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSalesPersonAllocationSeeder {
    fn name(&self) -> &'static str {
        "SeedSalesPersonAllocationSeeder"
    }

    fn order(&self) -> i32 {
        8
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if selling.sales_person_allocations table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM selling.sales_person_allocations")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/sales_person_allocation_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM selling.sales_person_allocations")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

