//! SalesOrderItem seeder
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Seeds initial SalesOrderItem data into the database.

use anyhow::Result;
use async_trait::async_trait;
use sqlx::PgPool;

use super::Seeder;

// ============================================================================
// SALESORDERITEM SEEDER
// ============================================================================

/// Seeder for sales_order_item
pub struct SeedSalesOrderItemSeeder;

impl SeedSalesOrderItemSeeder {
    pub fn new() -> Self {
        Self
    }
}

impl Default for SeedSalesOrderItemSeeder {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl Seeder for SeedSalesOrderItemSeeder {
    fn name(&self) -> &'static str {
        "SeedSalesOrderItemSeeder"
    }

    fn order(&self) -> i32 {
        6
    }

    async fn should_run(&self, pool: &PgPool) -> Result<bool> {
        // Check if selling.sales_order_items table has any data
        let count: (i64,) = sqlx::query_as("SELECT COUNT(*) FROM selling.sales_order_items")
            .fetch_one(pool)
            .await?;
        Ok(count.0 == 0)
    }

    async fn run(&self, pool: &PgPool) -> Result<()> {
        // Run the SQL seed file
        let sql = include_str!("../../migrations/seeds/sales_order_item_seed.sql");
        sqlx::raw_sql(sql).execute(pool).await?;
        Ok(())
    }

    async fn rollback(&self, pool: &PgPool) -> Result<()> {
        sqlx::query("DELETE FROM selling.sales_order_items")
            .execute(pool)
            .await?;
        Ok(())
    }
}

// ============================================================================
// CUSTOM SEED DATA
// ============================================================================

// <<< CUSTOM SEED DATA START >>>
// Add custom seed data methods here
// <<< CUSTOM SEED DATA END >>>

