//! Repository trait for QuotationItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the QuotationItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::QuotationItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuotationItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QuotationItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QuotationItemPaginatedResult {
    pub data: Vec<QuotationItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuotationItemFilter {
    pub quotation_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub description: Option<String>,
}

impl QuotationItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.quotation_id.is_some() || self.item_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for QuotationItem aggregate
///
/// This trait defines the persistence contract for QuotationItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QuotationItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quotation_item entity
    async fn save(&self, entity: &QuotationItem) -> Result<QuotationItem>;

    /// Find quotation_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<QuotationItem>>;

    /// Find all quotation_item entities
    async fn find_all(&self) -> Result<Vec<QuotationItem>>;

    /// Update quotation_item by ID
    async fn update(&self, id: &str, entity: &QuotationItem) -> Result<Option<QuotationItem>>;

    /// Delete quotation_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quotation_item with pagination
    async fn list(&self, params: QuotationItemPaginationParams) -> Result<QuotationItemPaginatedResult>;

    /// List quotation_item with pagination and filters
    async fn list_with_filters(&self, params: QuotationItemPaginationParams, filters: QuotationItemFilter) -> Result<QuotationItemPaginatedResult>;

    /// Count all quotation_item entities
    async fn count(&self) -> Result<u64>;

    /// Count quotation_item entities matching filters
    async fn count_with_filters(&self, filters: QuotationItemFilter) -> Result<u64>;

    /// Check if quotation_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quotation_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quotation_item by ID
    async fn restore(&self, id: &str) -> Result<Option<QuotationItem>>;

    /// List soft-deleted quotation_item entities
    async fn list_deleted(&self, params: QuotationItemPaginationParams) -> Result<QuotationItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quotation_item entities
    async fn bulk_save(&self, entities: &[QuotationItem]) -> Result<Vec<QuotationItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
