//! Repository trait for Quotation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the Quotation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{Quotation, QuotationStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuotationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl QuotationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct QuotationPaginatedResult {
    pub data: Vec<Quotation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct QuotationFilter {
    pub quotation_number: Option<String>,
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub status: Option<QuotationStatus>,
    pub currency: Option<String>,
    pub notes: Option<String>,
}

impl QuotationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.quotation_number.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.customer_id.is_some() || self.status.is_some() || self.currency.is_some() || self.notes.is_some()
    }
}

/// Repository trait for Quotation aggregate
///
/// This trait defines the persistence contract for Quotation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait QuotationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new quotation entity
    async fn save(&self, entity: &Quotation) -> Result<Quotation>;

    /// Find quotation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<Quotation>>;

    /// Find all quotation entities
    async fn find_all(&self) -> Result<Vec<Quotation>>;

    /// Update quotation by ID
    async fn update(&self, id: &str, entity: &Quotation) -> Result<Option<Quotation>>;

    /// Delete quotation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List quotation with pagination
    async fn list(&self, params: QuotationPaginationParams) -> Result<QuotationPaginatedResult>;

    /// List quotation with pagination and filters
    async fn list_with_filters(&self, params: QuotationPaginationParams, filters: QuotationFilter) -> Result<QuotationPaginatedResult>;

    /// Count all quotation entities
    async fn count(&self) -> Result<u64>;

    /// Count quotation entities matching filters
    async fn count_with_filters(&self, filters: QuotationFilter) -> Result<u64>;

    /// Check if quotation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete quotation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted quotation by ID
    async fn restore(&self, id: &str) -> Result<Option<Quotation>>;

    /// List soft-deleted quotation entities
    async fn list_deleted(&self, params: QuotationPaginationParams) -> Result<QuotationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save quotation entities
    async fn bulk_save(&self, entities: &[Quotation]) -> Result<Vec<Quotation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
