//! Repository trait for SalesInvoice aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalesInvoice aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{SalesInvoice, GlPostingState, SalesInvoiceStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesInvoicePaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalesInvoicePaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalesInvoicePaginatedResult {
    pub data: Vec<SalesInvoice>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesInvoiceFilter {
    pub invoice_number: Option<String>,
    pub sales_order_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub status: Option<SalesInvoiceStatus>,
    pub currency: Option<String>,
    pub receivable_account_id: Option<Uuid>,
    pub tax_output_account_id: Option<Uuid>,
    pub posting_state: Option<GlPostingState>,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
    pub notes: Option<String>,
}

impl SalesInvoiceFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.invoice_number.is_some() || self.sales_order_id.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.customer_id.is_some() || self.status.is_some() || self.currency.is_some() || self.receivable_account_id.is_some() || self.tax_output_account_id.is_some() || self.posting_state.is_some() || self.journal_id.is_some() || self.accounting_post_id.is_some() || self.notes.is_some()
    }
}

/// Repository trait for SalesInvoice aggregate
///
/// This trait defines the persistence contract for SalesInvoice entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalesInvoiceRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new sales_invoice entity
    async fn save(&self, entity: &SalesInvoice) -> Result<SalesInvoice>;

    /// Find sales_invoice by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalesInvoice>>;

    /// Find all sales_invoice entities
    async fn find_all(&self) -> Result<Vec<SalesInvoice>>;

    /// Update sales_invoice by ID
    async fn update(&self, id: &str, entity: &SalesInvoice) -> Result<Option<SalesInvoice>>;

    /// Delete sales_invoice by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List sales_invoice with pagination
    async fn list(&self, params: SalesInvoicePaginationParams) -> Result<SalesInvoicePaginatedResult>;

    /// List sales_invoice with pagination and filters
    async fn list_with_filters(&self, params: SalesInvoicePaginationParams, filters: SalesInvoiceFilter) -> Result<SalesInvoicePaginatedResult>;

    /// Count all sales_invoice entities
    async fn count(&self) -> Result<u64>;

    /// Count sales_invoice entities matching filters
    async fn count_with_filters(&self, filters: SalesInvoiceFilter) -> Result<u64>;

    /// Check if sales_invoice exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete sales_invoice by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted sales_invoice by ID
    async fn restore(&self, id: &str) -> Result<Option<SalesInvoice>>;

    /// List soft-deleted sales_invoice entities
    async fn list_deleted(&self, params: SalesInvoicePaginationParams) -> Result<SalesInvoicePaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save sales_invoice entities
    async fn bulk_save(&self, entities: &[SalesInvoice]) -> Result<Vec<SalesInvoice>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
