//! Repository trait for SalesTeam aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalesTeam aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SalesTeam;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesTeamPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalesTeamPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalesTeamPaginatedResult {
    pub data: Vec<SalesTeam>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesTeamFilter {
    pub company_id: Option<Uuid>,
    pub name: Option<String>,
    pub description: Option<String>,
}

impl SalesTeamFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.company_id.is_some() || self.name.is_some() || self.description.is_some()
    }
}

/// Repository trait for SalesTeam aggregate
///
/// This trait defines the persistence contract for SalesTeam entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalesTeamRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new sales_team entity
    async fn save(&self, entity: &SalesTeam) -> Result<SalesTeam>;

    /// Find sales_team by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalesTeam>>;

    /// Find all sales_team entities
    async fn find_all(&self) -> Result<Vec<SalesTeam>>;

    /// Update sales_team by ID
    async fn update(&self, id: &str, entity: &SalesTeam) -> Result<Option<SalesTeam>>;

    /// Delete sales_team by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List sales_team with pagination
    async fn list(&self, params: SalesTeamPaginationParams) -> Result<SalesTeamPaginatedResult>;

    /// List sales_team with pagination and filters
    async fn list_with_filters(&self, params: SalesTeamPaginationParams, filters: SalesTeamFilter) -> Result<SalesTeamPaginatedResult>;

    /// Count all sales_team entities
    async fn count(&self) -> Result<u64>;

    /// Count sales_team entities matching filters
    async fn count_with_filters(&self, filters: SalesTeamFilter) -> Result<u64>;

    /// Check if sales_team exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete sales_team by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted sales_team by ID
    async fn restore(&self, id: &str) -> Result<Option<SalesTeam>>;

    /// List soft-deleted sales_team entities
    async fn list_deleted(&self, params: SalesTeamPaginationParams) -> Result<SalesTeamPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save sales_team entities
    async fn bulk_save(&self, entities: &[SalesTeam]) -> Result<Vec<SalesTeam>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
