//! Repository trait for SalesOrder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalesOrder aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::{SalesOrder, SalesOrderStatus};

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesOrderPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalesOrderPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalesOrderPaginatedResult {
    pub data: Vec<SalesOrder>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesOrderFilter {
    pub order_number: Option<String>,
    pub quotation_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub branch_id: Option<Uuid>,
    pub customer_id: Option<Uuid>,
    pub status: Option<SalesOrderStatus>,
    pub currency: Option<String>,
    pub notes: Option<String>,
}

impl SalesOrderFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_number.is_some() || self.quotation_id.is_some() || self.company_id.is_some() || self.branch_id.is_some() || self.customer_id.is_some() || self.status.is_some() || self.currency.is_some() || self.notes.is_some()
    }
}

/// Repository trait for SalesOrder aggregate
///
/// This trait defines the persistence contract for SalesOrder entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalesOrderRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new sales_order entity
    async fn save(&self, entity: &SalesOrder) -> Result<SalesOrder>;

    /// Find sales_order by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalesOrder>>;

    /// Find all sales_order entities
    async fn find_all(&self) -> Result<Vec<SalesOrder>>;

    /// Update sales_order by ID
    async fn update(&self, id: &str, entity: &SalesOrder) -> Result<Option<SalesOrder>>;

    /// Delete sales_order by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List sales_order with pagination
    async fn list(&self, params: SalesOrderPaginationParams) -> Result<SalesOrderPaginatedResult>;

    /// List sales_order with pagination and filters
    async fn list_with_filters(&self, params: SalesOrderPaginationParams, filters: SalesOrderFilter) -> Result<SalesOrderPaginatedResult>;

    /// Count all sales_order entities
    async fn count(&self) -> Result<u64>;

    /// Count sales_order entities matching filters
    async fn count_with_filters(&self, filters: SalesOrderFilter) -> Result<u64>;

    /// Check if sales_order exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete sales_order by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted sales_order by ID
    async fn restore(&self, id: &str) -> Result<Option<SalesOrder>>;

    /// List soft-deleted sales_order entities
    async fn list_deleted(&self, params: SalesOrderPaginationParams) -> Result<SalesOrderPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save sales_order entities
    async fn bulk_save(&self, entities: &[SalesOrder]) -> Result<Vec<SalesOrder>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
