//! Repository trait for SalesInvoiceItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalesInvoiceItem aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SalesInvoiceItem;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesInvoiceItemPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalesInvoiceItemPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalesInvoiceItemPaginatedResult {
    pub data: Vec<SalesInvoiceItem>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesInvoiceItemFilter {
    pub invoice_id: Option<Uuid>,
    pub item_id: Option<Uuid>,
    pub sales_order_item_id: Option<Uuid>,
    pub revenue_account_id: Option<Uuid>,
    pub description: Option<String>,
}

impl SalesInvoiceItemFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.invoice_id.is_some() || self.item_id.is_some() || self.sales_order_item_id.is_some() || self.revenue_account_id.is_some() || self.description.is_some()
    }
}

/// Repository trait for SalesInvoiceItem aggregate
///
/// This trait defines the persistence contract for SalesInvoiceItem entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalesInvoiceItemRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new sales_invoice_item entity
    async fn save(&self, entity: &SalesInvoiceItem) -> Result<SalesInvoiceItem>;

    /// Find sales_invoice_item by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalesInvoiceItem>>;

    /// Find all sales_invoice_item entities
    async fn find_all(&self) -> Result<Vec<SalesInvoiceItem>>;

    /// Update sales_invoice_item by ID
    async fn update(&self, id: &str, entity: &SalesInvoiceItem) -> Result<Option<SalesInvoiceItem>>;

    /// Delete sales_invoice_item by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List sales_invoice_item with pagination
    async fn list(&self, params: SalesInvoiceItemPaginationParams) -> Result<SalesInvoiceItemPaginatedResult>;

    /// List sales_invoice_item with pagination and filters
    async fn list_with_filters(&self, params: SalesInvoiceItemPaginationParams, filters: SalesInvoiceItemFilter) -> Result<SalesInvoiceItemPaginatedResult>;

    /// Count all sales_invoice_item entities
    async fn count(&self) -> Result<u64>;

    /// Count sales_invoice_item entities matching filters
    async fn count_with_filters(&self, filters: SalesInvoiceItemFilter) -> Result<u64>;

    /// Check if sales_invoice_item exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete sales_invoice_item by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted sales_invoice_item by ID
    async fn restore(&self, id: &str) -> Result<Option<SalesInvoiceItem>>;

    /// List soft-deleted sales_invoice_item entities
    async fn list_deleted(&self, params: SalesInvoiceItemPaginationParams) -> Result<SalesInvoiceItemPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save sales_invoice_item entities
    async fn bulk_save(&self, entities: &[SalesInvoiceItem]) -> Result<Vec<SalesInvoiceItem>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
