//! Repository trait for SalesPersonAllocation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This trait defines the repository contract for the SalesPersonAllocation aggregate.
//! Implementation is in the infrastructure layer.

use async_trait::async_trait;
use anyhow::Result;
use uuid::Uuid;

use crate::domain::entity::SalesPersonAllocation;

/// Pagination parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesPersonAllocationPaginationParams {
    pub page: u32,
    pub per_page: u32,
}

impl SalesPersonAllocationPaginationParams {
    pub fn new(page: u32, per_page: u32) -> Self {
        Self { page, per_page }
    }

    pub fn offset(&self) -> u64 {
        ((self.page.saturating_sub(1)) * self.per_page) as u64
    }

    pub fn limit(&self) -> u64 {
        self.per_page as u64
    }
}

/// Paginated result for list queries
#[derive(Debug, Clone)]
pub struct SalesPersonAllocationPaginatedResult {
    pub data: Vec<SalesPersonAllocation>,
    pub total: u64,
    pub page: u32,
    pub per_page: u32,
}

/// Filter parameters for list queries
#[derive(Debug, Clone, Default)]
pub struct SalesPersonAllocationFilter {
    pub order_id: Option<Uuid>,
    pub company_id: Option<Uuid>,
    pub sales_person_id: Option<Uuid>,
    pub sales_team_id: Option<Uuid>,
}

impl SalesPersonAllocationFilter {
    /// Check if any filter is set
    pub fn has_filters(&self) -> bool {
        self.order_id.is_some() || self.company_id.is_some() || self.sales_person_id.is_some() || self.sales_team_id.is_some()
    }
}

/// Repository trait for SalesPersonAllocation aggregate
///
/// This trait defines the persistence contract for SalesPersonAllocation entities.
/// Implementations should be in the infrastructure layer.
#[async_trait]
pub trait SalesPersonAllocationRepository: Send + Sync {

    // =========================================================================
    // Core CRUD Operations
    // =========================================================================

    /// Save a new sales_person_allocation entity
    async fn save(&self, entity: &SalesPersonAllocation) -> Result<SalesPersonAllocation>;

    /// Find sales_person_allocation by ID
    async fn find_by_id(&self, id: &str) -> Result<Option<SalesPersonAllocation>>;

    /// Find all sales_person_allocation entities
    async fn find_all(&self) -> Result<Vec<SalesPersonAllocation>>;

    /// Update sales_person_allocation by ID
    async fn update(&self, id: &str, entity: &SalesPersonAllocation) -> Result<Option<SalesPersonAllocation>>;

    /// Delete sales_person_allocation by ID
    async fn delete(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Pagination
    // =========================================================================

    /// List sales_person_allocation with pagination
    async fn list(&self, params: SalesPersonAllocationPaginationParams) -> Result<SalesPersonAllocationPaginatedResult>;

    /// List sales_person_allocation with pagination and filters
    async fn list_with_filters(&self, params: SalesPersonAllocationPaginationParams, filters: SalesPersonAllocationFilter) -> Result<SalesPersonAllocationPaginatedResult>;

    /// Count all sales_person_allocation entities
    async fn count(&self) -> Result<u64>;

    /// Count sales_person_allocation entities matching filters
    async fn count_with_filters(&self, filters: SalesPersonAllocationFilter) -> Result<u64>;

    /// Check if sales_person_allocation exists by ID
    async fn exists(&self, id: &str) -> Result<bool>;

    // =========================================================================
    // Soft Delete Operations
    // =========================================================================

    /// Soft delete sales_person_allocation by ID
    async fn soft_delete(&self, id: &str) -> Result<bool>;

    /// Restore soft-deleted sales_person_allocation by ID
    async fn restore(&self, id: &str) -> Result<Option<SalesPersonAllocation>>;

    /// List soft-deleted sales_person_allocation entities
    async fn list_deleted(&self, params: SalesPersonAllocationPaginationParams) -> Result<SalesPersonAllocationPaginatedResult>;

    /// Empty trash (permanently delete all soft-deleted entities)
    async fn empty_trash(&self) -> Result<u64>;

    // =========================================================================
    // Bulk Operations
    // =========================================================================

    /// Bulk save sales_person_allocation entities
    async fn bulk_save(&self, entities: &[SalesPersonAllocation]) -> Result<Vec<SalesPersonAllocation>>;

    /// Bulk delete by IDs
    async fn bulk_delete(&self, ids: &[&str]) -> Result<u64>;
}
