//! Repository for DeliveryCarrier entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for the hand-written carrier-master SQL (registry only — create/update/list
//! plus the company-scoped existence probe the order create/set-delivery paths validate against;
//! 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DeliveryCarrier, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::DeliveryCarrier;

/// Table name for DeliveryCarrier entities
pub const TABLE_NAME: &str = "selling.delivery_carriers";

/// Repository for DeliveryCarrier entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DeliveryCarrierRepository(
    backbone_orm::GenericCrudRepository<DeliveryCarrier, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DeliveryCarrierRepository {
    type Target = backbone_orm::GenericCrudRepository<DeliveryCarrier, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DeliveryCarrierRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One delivery-carrier row as the write service and its read DTO consume it.
pub struct DeliveryCarrierRow {
    pub id: Uuid,
    pub company_id: Uuid,
    pub name: String,
    pub active: bool,
    pub tracking_url_template: Option<String>,
}

/// Hand-written DeliveryCarrier SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl DeliveryCarrierRepository {
    /// Insert one carrier master row. Returns the raw `sqlx::Error` deliberately: the caller
    /// inspects it for a unique violation on (company_id, name) to turn a duplicate live name
    /// into a domain error (the pre-read catches the common case; the partial unique index
    /// backs the race).
    pub async fn insert_carrier(
        &self,
        pool: &PgPool,
        id: Uuid,
        company_id: Uuid,
        name: &str,
        tracking_url_template: Option<&str>,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO selling.delivery_carriers (id, company_id, name, active, tracking_url_template)
                   VALUES ($1,$2,$3,true,$4)"#,
            )
            .bind(id).bind(company_id).bind(name).bind(tracking_url_template),
        ).await?;
        Ok(())
    }

    /// Read one carrier, company-scoped: another company's (or an unknown) carrier id simply
    /// isn't found. This is the pre-read the order create / set-delivery paths validate the
    /// carrier against — never rely on the FK violation's 500 for a wrong id.
    pub async fn find_carrier(
        &self,
        pool: &PgPool,
        carrier_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<DeliveryCarrierRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, company_id, name, active, tracking_url_template
                   FROM selling.delivery_carriers
                   WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(carrier_id).bind(company_id),
        ).await?;
        Ok(row.map(|r| DeliveryCarrierRow {
            id: r.get("id"),
            company_id: r.get("company_id"),
            name: r.get("name"),
            active: r.get("active"),
            tracking_url_template: r.get("tracking_url_template"),
        }))
    }

    /// Read one LIVE carrier by (company, name) — the duplicate pre-read behind
    /// `create_delivery_carrier`. Soft-deleted names are reusable, so the read ignores them
    /// (mirroring the partial unique index).
    pub async fn find_carrier_by_name(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        name: &str,
    ) -> Result<Option<DeliveryCarrierRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, company_id, name, active, tracking_url_template
                   FROM selling.delivery_carriers
                   WHERE company_id=$1 AND name=$2 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(company_id).bind(name),
        ).await?;
        Ok(row.map(|r| DeliveryCarrierRow {
            id: r.get("id"),
            company_id: r.get("company_id"),
            name: r.get("name"),
            active: r.get("active"),
            tracking_url_template: r.get("tracking_url_template"),
        }))
    }

    /// List a company's carriers (name order), optionally active-only.
    pub async fn list_carriers(
        &self,
        pool: &PgPool,
        company_id: Uuid,
        active_only: bool,
    ) -> Result<Vec<DeliveryCarrierRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, company_id, name, active, tracking_url_template
                   FROM selling.delivery_carriers
                   WHERE company_id=$1 AND (metadata->>'deleted_at') IS NULL
                     AND (NOT $2 OR active)
                   ORDER BY name"#,
            )
            .bind(company_id).bind(active_only),
        ).await?;
        Ok(rows.iter().map(|r| DeliveryCarrierRow {
            id: r.get("id"),
            company_id: r.get("company_id"),
            name: r.get("name"),
            active: r.get("active"),
            tracking_url_template: r.get("tracking_url_template"),
        }).collect())
    }

    /// Guarded patch of a carrier's master fields. `None` keeps the stored value for
    /// name/active; for `tracking_url_template` the `template_provided` flag distinguishes
    /// "not asked" from "set to NULL" (a patch can clear the template). Takes the caller's
    /// transaction connection (the caller binds the company on it). Returns `false` when the
    /// guarded statement matched no live carrier of this company.
    pub async fn update_carrier(
        &self,
        conn: &mut sqlx::PgConnection,
        carrier_id: Uuid,
        company_id: Uuid,
        name: Option<&str>,
        active: Option<bool>,
        template_provided: bool,
        tracking_url_template: Option<&str>,
    ) -> Result<bool, sqlx::Error> {
        let result = sqlx::query(
            r#"UPDATE selling.delivery_carriers
               SET name = COALESCE($3, name),
                   active = COALESCE($4, active),
                   tracking_url_template = CASE WHEN $5 THEN $6 ELSE tracking_url_template END
               WHERE id=$1 AND company_id=$2 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(carrier_id).bind(company_id).bind(name).bind(active)
        .bind(template_provided).bind(tracking_url_template)
        .execute(conn)
        .await?;
        Ok(result.rows_affected() > 0)
    }
}

backbone_core::impl_crud_repository!(DeliveryCarrierRepository, DeliveryCarrier, soft_delete);
