//! Repository for DeliveryCarrier entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for the hand-written carrier-master SQL (registry only — create/update/list
//! plus the existence probe the order create/set-delivery paths validate against;
//! 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<DeliveryCarrier, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::{PgPool, Row};
use uuid::Uuid;

// The optional-row read and write twins ride the org-scope module; the all-rows read twin
// lives only in the legacy `company_scope` module. Their connection discipline is the
// request-dedicated connection when the composing service bound one, plain pool otherwise.
// The legacy task-local branch is never taken: this module sets no legacy scope of its own
// (ADR-0029).
use backbone_orm::company_scope::fetch_all_rows_scoped;
use backbone_orm::org_scope;

use crate::domain::entity::DeliveryCarrier;

/// Table name for DeliveryCarrier entities
pub const TABLE_NAME: &str = "selling.delivery_carriers";

/// Repository for DeliveryCarrier entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct DeliveryCarrierRepository(
    backbone_orm::GenericCrudRepository<DeliveryCarrier, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for DeliveryCarrierRepository {
    type Target = backbone_orm::GenericCrudRepository<DeliveryCarrier, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl DeliveryCarrierRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// One delivery-carrier row as the write service and its read DTO consume it.
pub struct DeliveryCarrierRow {
    pub id: Uuid,
    pub name: String,
    pub active: bool,
    pub tracking_url_template: Option<String>,
}

/// Hand-written DeliveryCarrier SQL. Lives here (not in the write service) per the module's
/// 4-layer rule: services orchestrate and own the unit of work, repositories hold the SQL.
impl DeliveryCarrierRepository {
    /// Insert one carrier master row. Returns the raw `sqlx::Error` deliberately: the caller
    /// inspects it for a unique violation on the name to turn a duplicate live name into a
    /// domain error (the pre-read catches the common case; the decorator's per-unit unique
    /// backs the race under a composed tenancy).
    pub async fn insert_carrier(
        &self,
        pool: &PgPool,
        id: Uuid,
        name: &str,
        tracking_url_template: Option<&str>,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"INSERT INTO selling.delivery_carriers (id, name, active, tracking_url_template)
                   VALUES ($1,$2,true,$3)"#,
            )
            .bind(id).bind(name).bind(tracking_url_template),
        ).await?;
        Ok(())
    }

    /// Read one carrier: a foreign (under a composed decorator) or unknown carrier id simply
    /// isn't found. This is the pre-read the order create / set-delivery paths validate the
    /// carrier against — never rely on the FK violation's 500 for a wrong id.
    pub async fn find_carrier(
        &self,
        pool: &PgPool,
        carrier_id: Uuid,
    ) -> Result<Option<DeliveryCarrierRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, name, active, tracking_url_template
                   FROM selling.delivery_carriers
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(carrier_id),
        ).await?;
        Ok(row.map(|r| Self::project(&r)))
    }

    /// Read one LIVE carrier by name — the duplicate pre-read behind
    /// `create_delivery_carrier`. Soft-deleted names are reusable, so the read ignores them
    /// (mirroring the decorator's per-unit partial unique).
    pub async fn find_carrier_by_name(
        &self,
        pool: &PgPool,
        name: &str,
    ) -> Result<Option<DeliveryCarrierRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, name, active, tracking_url_template
                   FROM selling.delivery_carriers
                   WHERE name=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(name),
        ).await?;
        Ok(row.map(|r| Self::project(&r)))
    }

    /// List the carriers (name order), optionally active-only. Under a composed tenancy
    /// decorator the request's fence scopes the read; an undecorated deployment lists all.
    pub async fn list_carriers(
        &self,
        pool: &PgPool,
        active_only: bool,
    ) -> Result<Vec<DeliveryCarrierRow>, sqlx::Error> {
        let rows = fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, name, active, tracking_url_template
                   FROM selling.delivery_carriers
                   WHERE (metadata->>'deleted_at') IS NULL
                     AND (NOT $1 OR active)
                   ORDER BY name"#,
            )
            .bind(active_only),
        ).await?;
        Ok(rows.iter().map(|r| Self::project(r)).collect())
    }

    /// Guarded patch of a carrier's master fields. `None` keeps the stored value for
    /// name/active; for `tracking_url_template` the `template_provided` flag distinguishes
    /// "not asked" from "set to NULL" (a patch can clear the template). Takes the caller's
    /// transaction connection (the caller relays the ambient org scope onto it). Returns
    /// `false` when the guarded statement matched no live carrier.
    pub async fn update_carrier(
        &self,
        conn: &mut sqlx::PgConnection,
        carrier_id: Uuid,
        name: Option<&str>,
        active: Option<bool>,
        template_provided: bool,
        tracking_url_template: Option<&str>,
    ) -> Result<bool, sqlx::Error> {
        let result = sqlx::query(
            r#"UPDATE selling.delivery_carriers
               SET name = COALESCE($2, name),
                   active = COALESCE($3, active),
                   tracking_url_template = CASE WHEN $4 THEN $5 ELSE tracking_url_template END
               WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
        )
        .bind(carrier_id).bind(name).bind(active)
        .bind(template_provided).bind(tracking_url_template)
        .execute(conn)
        .await?;
        Ok(result.rows_affected() > 0)
    }

    /// The row projection shared by the reads above.
    fn project(r: &sqlx::postgres::PgRow) -> DeliveryCarrierRow {
        DeliveryCarrierRow {
            id: r.get("id"),
            name: r.get("name"),
            active: r.get("active"),
            tracking_url_template: r.get("tracking_url_template"),
        }
    }
}

backbone_core::impl_crud_repository!(DeliveryCarrierRepository, DeliveryCarrier, soft_delete);
