//! Repository for QuotationItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written QuotationItem SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<QuotationItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::QuotationItem;

/// Table name for QuotationItem entities
pub const TABLE_NAME: &str = "selling.quotation_items";

/// Repository for QuotationItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QuotationItemRepository(
    backbone_orm::GenericCrudRepository<QuotationItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QuotationItemRepository {
    type Target = backbone_orm::GenericCrudRepository<QuotationItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QuotationItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a quotation-line insert writes.
///
/// Mirrors the raw column shape rather than the `QuotationItem` entity: `line_amount` is already
/// server-computed by the write service's `price_document` and is stored, not re-derived.
/// `invoice_policy` binds as `&str` with a DB-side `::invoice_policy` cast (hand-written SQL never
/// decodes/encodes the custom enum in Rust — the fleet's enum-bind lesson).
pub struct NewQuotationItemRow<'a> {
    pub id: Uuid,
    pub quotation_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub description: Option<&'a str>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_discount: Decimal,
    pub line_amount: Decimal,
    pub invoice_policy: &'a str,
    pub is_downpayment: bool,
}

/// One quotation line as `convert_quotation_to_order` copies it. `line_amount` is deliberately absent:
/// the new order re-prices from (qty, price, discount) rather than trusting the quotation's total.
/// The invoicing policy + downpayment flag ride along — conversion preserves the billing intent.
pub struct QuotationLineRow {
    pub item_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_discount: Decimal,
    pub invoice_policy: String,
    pub is_downpayment: bool,
}

/// One quotation line as the invoice-status read model loads it (policy + flags surfaced for what
/// conversion will carry onto the order).
pub struct InvoicePolicyLineRow {
    pub id: Uuid,
    pub item_id: Uuid,
    pub invoice_policy: String,
    pub is_downpayment: bool,
    pub quantity: Decimal,
}

/// Hand-written QuotationItem SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl QuotationItemRepository {
    /// Insert one quotation line.
    ///
    /// Takes the CALLER'S connection so the line commits in the SAME transaction as its header. The
    /// caller binds the company on that connection (`bind_company_on`) before calling — don't re-bind.
    pub async fn insert_line(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewQuotationItemRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO selling.quotation_items
                (id, quotation_id, company_id, item_id, description, quantity, unit_price,
                 line_discount, line_amount, invoice_policy, is_downpayment)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::invoice_policy,$11)"#,
        )
        .bind(l.id).bind(l.quotation_id).bind(l.company_id).bind(l.item_id).bind(l.description)
        .bind(l.quantity).bind(l.unit_price).bind(l.line_discount).bind(l.line_amount)
        .bind(l.invoice_policy).bind(l.is_downpayment)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read a quotation's lines for `convert_quotation_to_order`.
    ///
    /// ID-only: no company argument, so this read rides the REQUEST-dedicated connection carrying the
    /// caller's `app.company_id` — RLS fences it (ADR-0008).
    pub async fn list_for_conversion(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Vec<QuotationLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT item_id, description, quantity, unit_price, line_discount,
                          invoice_policy::text AS pol, is_downpayment
                   FROM selling.quotation_items WHERE quotation_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(rows.iter().map(|r| QuotationLineRow {
            item_id: r.get("item_id"),
            description: r.get("description"),
            quantity: r.get("quantity"),
            unit_price: r.get("unit_price"),
            line_discount: r.get("line_discount"),
            invoice_policy: r.get("pol"),
            is_downpayment: r.get("is_downpayment"),
        }).collect())
    }

    /// Read a quotation's lines for the invoice-status read model. Quotation lines carry no
    /// watermarks — this surfaces the policy + downpayment flags conversion will carry. ID-only,
    /// same scoping as [`Self::list_for_conversion`].
    pub async fn list_policy_rows(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Vec<InvoicePolicyLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT id, item_id, invoice_policy::text AS pol, is_downpayment, quantity
                   FROM selling.quotation_items
                   WHERE quotation_id=$1 AND (metadata->>'deleted_at') IS NULL ORDER BY id"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(rows.iter().map(|r| InvoicePolicyLineRow {
            id: r.get("id"),
            item_id: r.get("item_id"),
            invoice_policy: r.get("pol"),
            is_downpayment: r.get("is_downpayment"),
            quantity: r.get("quantity"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(QuotationItemRepository, QuotationItem, soft_delete);
