//! Repository for Quotation entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written Quotation SQL statement (4-layer rule: services
//! orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Quotation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::Quotation;

/// Table name for Quotation entities
pub const TABLE_NAME: &str = "selling.quotations";

/// Repository for Quotation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QuotationRepository(
    backbone_orm::GenericCrudRepository<Quotation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QuotationRepository {
    type Target = backbone_orm::GenericCrudRepository<Quotation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QuotationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a quotation-header insert writes.
///
/// Mirrors the raw column shape rather than the `Quotation` entity: the money columns are already
/// server-computed by the write service's `price_document`, and `status` is not a parameter at all —
/// the statement pins `'draft'::quotation_status` so a new quotation can only ever start as a draft.
pub struct NewQuotationRow<'a> {
    pub id: Uuid,
    pub quotation_number: &'a str,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub quotation_date: chrono::NaiveDate,
    pub valid_until: Option<chrono::NaiveDate>,
    pub currency: &'a str,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<&'a str>,
}

/// The `accept_quotation` guard's projection — who the now-accepted quotation belongs to.
pub struct AcceptedQuotationRow {
    pub company_id: Uuid,
    pub customer_id: Uuid,
}

/// The quotation header `convert_quotation_to_order` copies from. `status` is read as `::text` so a
/// quotation in a state this build does not know about fails the `accepted` check rather than
/// panicking in a decode.
pub struct QuotationConversionRow {
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub currency: String,
    pub tax_rate: Decimal,
    pub status: String,
}

/// Hand-written Quotation SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl QuotationRepository {
    /// Insert a draft quotation header.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as ONE unit. The caller binds
    /// the company on that connection (`bind_company_on`) before calling — don't re-bind here. The
    /// explicit `company_id` bind stays as defense-in-depth behind the RLS fence (ADR-0008).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate quotation number into a domain error.
    pub async fn insert_draft(
        &self,
        conn: &mut sqlx::PgConnection,
        q: &NewQuotationRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO selling.quotations
                (id, quotation_number, company_id, branch_id, customer_id, status, quotation_date,
                 valid_until, currency, subtotal, tax_rate, tax_amount, total, notes)
               VALUES ($1,$2,$3,$4,$5,'draft'::quotation_status,$6,$7,$8,$9,$10,$11,$12,$13)"#,
        )
        .bind(q.id).bind(q.quotation_number).bind(q.company_id).bind(q.branch_id).bind(q.customer_id)
        .bind(q.quotation_date).bind(q.valid_until).bind(q.currency)
        .bind(q.subtotal).bind(q.tax_rate).bind(q.tax_amount).bind(q.total).bind(q.notes)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Accept a quotation (draft/sent → accepted), returning who it belongs to. `Ok(None)` = no
    /// quotation of this company is in an acceptable state, which is also how a wrong-tenant id looks.
    ///
    /// A write outside any transaction: takes the pool and runs `fetch_optional_row_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))` — the
    /// company is on the parameter. The explicit `company_id=$2` filter stays as defense-in-depth.
    pub async fn accept(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<AcceptedQuotationRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations SET status='accepted'::quotation_status
                   WHERE id=$1 AND company_id=$2 AND status = ANY(ARRAY['draft','sent']::quotation_status[])
                     AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id, customer_id"#,
            )
            .bind(quotation_id).bind(company_id),
        ).await?;
        Ok(row.map(|r| AcceptedQuotationRow {
            company_id: r.get("company_id"),
            customer_id: r.get("customer_id"),
        }))
    }

    /// Read the header `convert_quotation_to_order` copies into the new order.
    ///
    /// ID-only: no company argument to scope from up front, so this read rides the REQUEST-dedicated
    /// connection (established by `company_auth`), which carries the caller's `app.company_id` — RLS
    /// fences the lookup so another company's quotation simply isn't found.
    pub async fn find_conversion_source(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Option<QuotationConversionRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, branch_id, customer_id, currency, tax_rate, status::text AS st
                   FROM selling.quotations WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(row.map(|r| QuotationConversionRow {
            company_id: r.get("company_id"),
            branch_id: r.get("branch_id"),
            customer_id: r.get("customer_id"),
            currency: r.get("currency"),
            tax_rate: r.get("tax_rate"),
            status: r.get("st"),
        }))
    }

    /// Mark a quotation `ordered` once its sales order exists. ID-only, same scoping as
    /// [`Self::find_conversion_source`].
    pub async fn mark_ordered(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations SET status='ordered'::quotation_status WHERE id=$1"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(QuotationRepository, Quotation, soft_delete);
