//! Repository for Quotation entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written Quotation SQL statement (4-layer rule: services
//! orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<Quotation, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

// The optional-row read/write twins ride the org-scope module; their connection discipline
// is the request-dedicated connection when the composing service bound one, plain pool
// otherwise. The legacy task-local branch is never taken: this module sets no legacy scope
// of its own (ADR-0029).
use backbone_orm::org_scope;

use crate::domain::entity::Quotation;

/// Table name for Quotation entities
pub const TABLE_NAME: &str = "selling.quotations";

/// Repository for Quotation entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct QuotationRepository(
    backbone_orm::GenericCrudRepository<Quotation, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for QuotationRepository {
    type Target = backbone_orm::GenericCrudRepository<Quotation, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl QuotationRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a quotation-header insert writes.
///
/// Mirrors the raw column shape rather than the `Quotation` entity: the money columns are already
/// server-computed by the write service's `price_document`, and `status` is not a parameter at all —
/// the statement pins `'draft'::quotation_status` so a new quotation can only ever start as a draft.
pub struct NewQuotationRow<'a> {
    pub id: Uuid,
    pub quotation_number: &'a str,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub quotation_date: chrono::NaiveDate,
    pub valid_until: Option<chrono::NaiveDate>,
    pub currency: &'a str,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<&'a str>,
    pub opportunity_id: Option<Uuid>,
    pub status_reason: Option<&'a str>,
}

/// The `accept_quotation` guard's projection — who the now-accepted quotation belongs to.
pub struct AcceptedQuotationRow {
    pub customer_id: Uuid,
}

/// The post-refusal classification read: what state the quotation is in. `status` is read as
/// `::text` so an unknown state fails the state checks rather than panicking in a decode.
pub struct QuotationStatusRow {
    pub status: String,
}

/// The quotation header the invoice-status read model surfaces.
pub struct QuotationInvoiceHeaderRow {
    pub quotation_number: String,
    pub status: String,
}

/// The quotation header `convert_quotation_to_order` copies from. `status` is read as `::text` so a
/// quotation in a state this build does not know about fails the `accepted` check rather than
/// panicking in a decode.
pub struct QuotationConversionRow {
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub currency: String,
    pub tax_rate: Decimal,
    pub status: String,
}

/// Hand-written Quotation SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl QuotationRepository {
    /// Insert a draft quotation header.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as ONE unit. The caller
    /// relays the ambient org scope onto that connection (`org_scope::bind_org_scope_on`) before
    /// calling — don't re-bind here.
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate quotation number into a domain error.
    pub async fn insert_draft(
        &self,
        conn: &mut sqlx::PgConnection,
        q: &NewQuotationRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO selling.quotations
                (id, quotation_number, branch_id, customer_id, status, quotation_date,
                 valid_until, currency, subtotal, tax_rate, tax_amount, total, notes,
                 opportunity_id, status_reason)
               VALUES ($1,$2,$3,$4,'draft'::quotation_status,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14)"#,
        )
        .bind(q.id).bind(q.quotation_number).bind(q.branch_id).bind(q.customer_id)
        .bind(q.quotation_date).bind(q.valid_until).bind(q.currency)
        .bind(q.subtotal).bind(q.tax_rate).bind(q.tax_amount).bind(q.total).bind(q.notes)
        .bind(q.opportunity_id).bind(q.status_reason)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Accept a quotation (draft/sent → accepted), returning who it belongs to. `Ok(None)` = no
    /// quotation in an acceptable state — under a composed tenancy decorator that is also how a
    /// foreign id looks (no existence leak; ADR-0029).
    ///
    /// A write outside any transaction: takes the pool and runs `org_scope::fetch_optional_row_scoped`
    /// so the read rides the request-dedicated connection when the composing service bound one
    /// (carrying the decorator's fence variables), plainly on the pool otherwise.
    pub async fn accept(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Option<AcceptedQuotationRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations SET status='accepted'::quotation_status
                   WHERE id=$1 AND status = ANY(ARRAY['draft','sent']::quotation_status[])
                     AND (metadata->>'deleted_at') IS NULL
                   RETURNING customer_id"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(row.map(|r| AcceptedQuotationRow {
            customer_id: r.get("customer_id"),
        }))
    }

    /// Read the header `convert_quotation_to_order` copies into the new order.
    ///
    /// ID-only: no tenant argument. `org_scope::fetch_optional_row_scoped` rides the
    /// request-dedicated connection when the composing service bound one (carrying the
    /// decorator's fence variables), plainly on the pool otherwise (ADR-0029).
    pub async fn find_conversion_source(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Option<QuotationConversionRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT branch_id, customer_id, currency, tax_rate, status::text AS st
                   FROM selling.quotations WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(row.map(|r| QuotationConversionRow {
            branch_id: r.get("branch_id"),
            customer_id: r.get("customer_id"),
            currency: r.get("currency"),
            tax_rate: r.get("tax_rate"),
            status: r.get("st"),
        }))
    }

    /// Mark a quotation `ordered` once its sales order exists. ID-only, same scoping as
    /// [`Self::find_conversion_source`].
    pub async fn mark_ordered(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations SET status='ordered'::quotation_status WHERE id=$1"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(())
    }

    // -- quotation state machine (guarded single-statement flips; the WHERE clause IS the guard) --

    /// Send a quotation (draft → sent). `Ok(None)` = no draft quotation with that id — under a
    /// composed tenancy decorator that is also how a foreign id looks (no existence leak).
    pub async fn send(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let n = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations SET status='sent'::quotation_status
                   WHERE id=$1 AND status='draft'::quotation_status
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(n.rows_affected() > 0)
    }

    /// Return a quotation to draft (sent/cancelled/rejected → draft), clearing any recorded
    /// rejection/cancellation reason. `ordered` is deliberately absent from the state array — a
    /// confirmed order must never be reset.
    pub async fn redraft(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<bool, sqlx::Error> {
        let n = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations
                   SET status='draft'::quotation_status, status_reason=NULL
                   WHERE id=$1
                     AND status = ANY(ARRAY['sent','cancelled','rejected']::quotation_status[])
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(n.rows_affected() > 0)
    }

    /// Reject a quotation (sent → rejected), persisting the optional reason.
    pub async fn reject(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
        reason: Option<&str>,
    ) -> Result<bool, sqlx::Error> {
        let n = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations
                   SET status='rejected'::quotation_status, status_reason=$2
                   WHERE id=$1 AND status='sent'::quotation_status
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id).bind(reason),
        ).await?;
        Ok(n.rows_affected() > 0)
    }

    /// Cancel a quotation (draft/sent/accepted → cancelled), persisting the optional reason.
    /// `ordered` is deliberately absent from the state array — an order was derived from it.
    pub async fn cancel(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
        reason: Option<&str>,
    ) -> Result<bool, sqlx::Error> {
        let n = org_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.quotations
                   SET status='cancelled'::quotation_status, status_reason=$2
                   WHERE id=$1
                     AND status = ANY(ARRAY['draft','sent','accepted']::quotation_status[])
                     AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id).bind(reason),
        ).await?;
        Ok(n.rows_affected() > 0)
    }

    /// Read a quotation's current status — the post-refusal classification read that turns a
    /// failed guarded flip into a precise error. `Ok(None)` = not found (under a composed
    /// decorator also a foreign id).
    pub async fn find_status(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Option<QuotationStatusRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT status::text AS st FROM selling.quotations
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(row.map(|r| QuotationStatusRow { status: r.get("st") }))
    }

    /// Read the quotation header the invoice-status read model surfaces. ID-only — same scoping
    /// as [`Self::find_conversion_source`].
    pub async fn find_invoice_status_header(
        &self,
        pool: &PgPool,
        quotation_id: Uuid,
    ) -> Result<Option<QuotationInvoiceHeaderRow>, sqlx::Error> {
        let row = org_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT quotation_number, status::text AS st FROM selling.quotations
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(quotation_id),
        ).await?;
        Ok(row.map(|r| QuotationInvoiceHeaderRow {
            quotation_number: r.get("quotation_number"),
            status: r.get("st"),
        }))
    }
}

backbone_core::impl_crud_repository!(QuotationRepository, Quotation, soft_delete);
