//! Repository for SalesInvoiceItem entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below hold the hand-written SalesInvoiceItem SQL (4-layer rule: services orchestrate, repos hold SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalesInvoiceItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::SalesInvoiceItem;

/// Table name for SalesInvoiceItem entities
pub const TABLE_NAME: &str = "selling.sales_invoice_items";

/// Repository for SalesInvoiceItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalesInvoiceItemRepository(
    backbone_orm::GenericCrudRepository<SalesInvoiceItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalesInvoiceItemRepository {
    type Target = backbone_orm::GenericCrudRepository<SalesInvoiceItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalesInvoiceItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row an invoice-line insert writes.
///
/// Mirrors the raw column shape rather than the `SalesInvoiceItem` entity: `line_amount` is already
/// server-computed by the write service's `price_document`. `sales_order_item_id` is `None` for a
/// directly-raised invoice and `Some` when raised from an order — that link is what lets posting
/// advance the order line's `billed_qty`.
pub struct NewSalesInvoiceItemRow<'a> {
    pub id: Uuid,
    pub invoice_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub sales_order_item_id: Option<Uuid>,
    pub revenue_account_id: Option<Uuid>,
    pub description: Option<&'a str>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_discount: Decimal,
    pub line_amount: Decimal,
}

/// One invoice line's revenue credit — what `build_revenue_post` groups by income account.
pub struct InvoiceRevenueLineRow {
    pub revenue_account_id: Uuid,
    pub line_amount: Decimal,
}

/// Hand-written SalesInvoiceItem SQL. Lives here (not in the write service) per the module's 4-layer rule.
impl SalesInvoiceItemRepository {
    /// Insert one invoice line.
    ///
    /// Takes the CALLER'S connection so the line commits in the SAME transaction as its header. The
    /// caller binds the company on that connection (`bind_company_on`) before calling — don't re-bind.
    pub async fn insert_line(
        &self,
        conn: &mut sqlx::PgConnection,
        l: &NewSalesInvoiceItemRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO selling.sales_invoice_items
                (id, invoice_id, company_id, item_id, sales_order_item_id, revenue_account_id, description,
                 quantity, unit_price, line_discount, line_amount)
               VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)"#,
        )
        .bind(l.id).bind(l.invoice_id).bind(l.company_id).bind(l.item_id).bind(l.sales_order_item_id)
        .bind(l.revenue_account_id).bind(l.description)
        .bind(l.quantity).bind(l.unit_price).bind(l.line_discount).bind(l.line_amount)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read an invoice's lines as revenue credits.
    ///
    /// ID-only: no company argument, so this read rides the REQUEST-dedicated connection carrying the
    /// caller's `app.company_id` — RLS fences it (ADR-0008).
    pub async fn list_revenue_lines(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Vec<InvoiceRevenueLineRow>, sqlx::Error> {
        let rows = company_scope::fetch_all_rows_scoped(
            pool,
            sqlx::query(
                r#"SELECT revenue_account_id, line_amount FROM selling.sales_invoice_items
                   WHERE invoice_id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_id),
        ).await?;
        Ok(rows.iter().map(|r| InvoiceRevenueLineRow {
            revenue_account_id: r.get("revenue_account_id"),
            line_amount: r.get("line_amount"),
        }).collect())
    }
}

backbone_core::impl_crud_repository!(SalesInvoiceItemRepository, SalesInvoiceItem, soft_delete);
