//! Repository for SalesOrderItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalesOrderItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SalesOrderItem;

/// Table name for SalesOrderItem entities
pub const TABLE_NAME: &str = "selling.sales_order_items";

/// Repository for SalesOrderItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalesOrderItemRepository(
    backbone_orm::GenericCrudRepository<SalesOrderItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalesOrderItemRepository {
    type Target = backbone_orm::GenericCrudRepository<SalesOrderItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalesOrderItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SalesOrderItemRepository, SalesOrderItem, soft_delete);
