//! Repository for SalesOrder entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written SalesOrder header SQL statement (4-layer rule: services
//! orchestrate and own the unit of work, repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalesOrder, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::SalesOrder;

/// Table name for SalesOrder entities
pub const TABLE_NAME: &str = "selling.sales_orders";

/// Repository for SalesOrder entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalesOrderRepository(
    backbone_orm::GenericCrudRepository<SalesOrder, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalesOrderRepository {
    type Target = backbone_orm::GenericCrudRepository<SalesOrder, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalesOrderRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a sales-order-header insert writes.
///
/// Mirrors the raw column shape rather than the `SalesOrder` entity: the money columns are already
/// server-computed by the write service's `price_document`, and `status` is not a parameter — the
/// statement pins `'draft'::sales_order_status` so a new order can only ever start as a draft.
pub struct NewSalesOrderRow<'a> {
    pub id: Uuid,
    pub order_number: &'a str,
    pub quotation_id: Option<Uuid>,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub order_date: chrono::NaiveDate,
    pub delivery_date: Option<chrono::NaiveDate>,
    pub currency: &'a str,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<&'a str>,
}

/// The `confirm_sales_order` guard's projection — what the `SalesOrderConfirmed` event carries.
pub struct ConfirmedOrderRow {
    pub company_id: Uuid,
    pub customer_id: Uuid,
    pub total: Decimal,
    pub currency: String,
}

/// The exported `SalesOrderRef`'s columns.
pub struct SalesOrderRefRow {
    pub customer_id: Uuid,
    pub company_id: Uuid,
    pub total: Decimal,
    pub currency: String,
}

/// The order header `create_invoice_from_order` copies into the invoice.
pub struct InvoiceSourceOrderRow {
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub currency: String,
    pub tax_rate: Decimal,
}

/// The order header the two fulfillment envelopes (`build_delivery_request` /
/// `build_invoice_request`) are built from. `status` is read as `::text` so an unknown state fails
/// the draft check rather than panicking in a decode.
pub struct OrderFulfillmentHeaderRow {
    pub company_id: Uuid,
    pub customer_id: Uuid,
    pub currency: String,
    pub status: String,
}

/// Hand-written SalesOrder SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl SalesOrderRepository {
    /// Insert a draft sales-order header.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as ONE unit. The caller binds
    /// the company on that connection (`bind_company_on`) before calling — don't re-bind here. The
    /// explicit `company_id` bind stays as defense-in-depth behind the RLS fence (ADR-0008).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate order number into a domain error.
    pub async fn insert_draft(
        &self,
        conn: &mut sqlx::PgConnection,
        o: &NewSalesOrderRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO selling.sales_orders
                (id, order_number, quotation_id, company_id, branch_id, customer_id, status,
                 order_date, delivery_date, currency, subtotal, tax_rate, tax_amount, total, notes)
               VALUES ($1,$2,$3,$4,$5,$6,'draft'::sales_order_status,$7,$8,$9,$10,$11,$12,$13,$14)"#,
        )
        .bind(o.id).bind(o.order_number).bind(o.quotation_id).bind(o.company_id).bind(o.branch_id)
        .bind(o.customer_id).bind(o.order_date).bind(o.delivery_date).bind(o.currency)
        .bind(o.subtotal).bind(o.tax_rate).bind(o.tax_amount).bind(o.total).bind(o.notes)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Confirm a draft order (draft → to_deliver_and_bill), returning what the event needs. `Ok(None)`
    /// = no draft order of this company with that id, which is also how a wrong-tenant id looks — so
    /// this does not leak whether the id exists.
    ///
    /// A write outside any transaction: takes the pool and runs `fetch_optional_row_scoped` so the RLS
    /// fence (ADR-0008) applies. The caller wraps this in `with_company_scope(Some(company_id))` — the
    /// company is on the parameter. The explicit `company_id=$2` filter stays as defense-in-depth.
    pub async fn confirm(
        &self,
        pool: &PgPool,
        order_id: Uuid,
        company_id: Uuid,
    ) -> Result<Option<ConfirmedOrderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.sales_orders SET status='to_deliver_and_bill'::sales_order_status
                   WHERE id=$1 AND company_id=$2 AND status='draft'::sales_order_status AND (metadata->>'deleted_at') IS NULL
                   RETURNING company_id, customer_id, total, currency"#,
            )
            .bind(order_id).bind(company_id),
        ).await?;
        Ok(row.map(|r| ConfirmedOrderRow {
            company_id: r.get("company_id"),
            customer_id: r.get("customer_id"),
            total: r.get("total"),
            currency: r.get("currency"),
        }))
    }

    /// Read the exported `SalesOrderRef`'s columns.
    ///
    /// ID-only: no company argument to scope from up front, so this read rides the REQUEST-dedicated
    /// connection (established by `company_auth`), which carries the caller's `app.company_id` — RLS
    /// fences the lookup so another company's order simply isn't found.
    pub async fn find_ref(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<Option<SalesOrderRefRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT customer_id, company_id, total, currency FROM selling.sales_orders
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(order_id),
        ).await?;
        Ok(row.map(|r| SalesOrderRefRow {
            customer_id: r.get("customer_id"),
            company_id: r.get("company_id"),
            total: r.get("total"),
            currency: r.get("currency"),
        }))
    }

    /// Read the order header `create_invoice_from_order` copies from. ID-only, same scoping as
    /// [`Self::find_ref`]; the caller binds THIS order's company onto the invoice transaction after.
    pub async fn find_invoice_source(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<Option<InvoiceSourceOrderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, branch_id, customer_id, currency, tax_rate
                   FROM selling.sales_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(order_id),
        ).await?;
        Ok(row.map(|r| InvoiceSourceOrderRow {
            company_id: r.get("company_id"),
            branch_id: r.get("branch_id"),
            customer_id: r.get("customer_id"),
            currency: r.get("currency"),
            tax_rate: r.get("tax_rate"),
        }))
    }

    /// Read the order header behind both fulfillment envelopes. ID-only, same scoping as
    /// [`Self::find_ref`].
    pub async fn find_fulfillment_header(
        &self,
        pool: &PgPool,
        order_id: Uuid,
    ) -> Result<Option<OrderFulfillmentHeaderRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT company_id, customer_id, currency, status::text AS st
                   FROM selling.sales_orders WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(order_id),
        ).await?;
        Ok(row.map(|r| OrderFulfillmentHeaderRow {
            company_id: r.get("company_id"),
            customer_id: r.get("customer_id"),
            currency: r.get("currency"),
            status: r.get("st"),
        }))
    }

    /// Advance an in-flight order's status to `next` (the recomputed watermark state). The
    /// `status = ANY(...)` gate is the invariant: only a confirmed order moves — draft/closed/cancelled
    /// are left alone. `next` binds as `&str` with a DB-side `::sales_order_status` cast, so a value
    /// outside the enum fails as a DB error rather than silently writing something else.
    ///
    /// ID-only: no company argument — inherits the caller's scope (see `recompute_order_status`).
    pub async fn advance_status(
        &self,
        pool: &PgPool,
        order_id: Uuid,
        next: &str,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.sales_orders SET status=$2::sales_order_status
                   WHERE id=$1 AND status = ANY(ARRAY['to_deliver','to_bill','to_deliver_and_bill']::sales_order_status[])"#,
            )
            .bind(order_id).bind(next),
        ).await?;
        Ok(())
    }
}

backbone_core::impl_crud_repository!(SalesOrderRepository, SalesOrder, soft_delete);
