//! Repository for SalesInvoiceItem entities
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalesInvoiceItem, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use sqlx::PgPool;

use crate::domain::entity::SalesInvoiceItem;

/// Table name for SalesInvoiceItem entities
pub const TABLE_NAME: &str = "selling.sales_invoice_items";

/// Repository for SalesInvoiceItem entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalesInvoiceItemRepository(
    backbone_orm::GenericCrudRepository<SalesInvoiceItem, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalesInvoiceItemRepository {
    type Target = backbone_orm::GenericCrudRepository<SalesInvoiceItem, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalesInvoiceItemRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

backbone_core::impl_crud_repository!(SalesInvoiceItemRepository, SalesInvoiceItem, soft_delete);
