//! Repository for SalesInvoice entities
//!
//! Originally generated by metaphor-schema; now **user-owned** — this exact path is declared under
//! `user_owned` in `metaphor.codegen.yaml`, so the generator skips it wholesale. The custom methods
//! below are the home for every hand-written SalesInvoice header SQL statement — including the GL
//! posting-state transitions (4-layer rule: services orchestrate and own the unit of work,
//! repositories hold the SQL).
//!
//! Thin newtype over `backbone_orm::GenericCrudRepository<SalesInvoice, backbone_orm::SoftDelete>`.
//! All standard CRUD methods are available via `Deref`.

use anyhow::Result;
use rust_decimal::Decimal;
use sqlx::{PgPool, Row};
use uuid::Uuid;

use backbone_orm::company_scope;

use crate::domain::entity::SalesInvoice;

/// Table name for SalesInvoice entities
pub const TABLE_NAME: &str = "selling.sales_invoices";

/// Repository for SalesInvoice entities.
///
/// All standard CRUD, soft-delete, pagination, and bulk methods are
/// provided automatically via `Deref` to `backbone_orm::GenericCrudRepository`.
pub struct SalesInvoiceRepository(
    backbone_orm::GenericCrudRepository<SalesInvoice, backbone_orm::SoftDelete>,
);

impl std::ops::Deref for SalesInvoiceRepository {
    type Target = backbone_orm::GenericCrudRepository<SalesInvoice, backbone_orm::SoftDelete>;
    fn deref(&self) -> &Self::Target { &self.0 }
}

impl SalesInvoiceRepository {
    /// Create a new repository instance.
    pub fn new(pool: PgPool) -> Self {
        Self(backbone_orm::GenericCrudRepository::new(pool, TABLE_NAME))
    }
}

/// The exact row a sales-invoice-header insert writes.
///
/// Mirrors the raw column shape rather than the `SalesInvoice` entity. Three columns are pinned by
/// the statement rather than passed: `status` = `'draft'`, `posting_state` = `'pending'`, and
/// `outstanding_amount` = 0 — a fresh invoice is unposted, so nothing is owed until the GL acks and
/// [`Self::reconcile_posted`] sets `outstanding_amount = total`.
pub struct NewSalesInvoiceRow<'a> {
    pub id: Uuid,
    pub invoice_number: &'a str,
    pub sales_order_id: Option<Uuid>,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub invoice_date: chrono::NaiveDate,
    pub due_date: Option<chrono::NaiveDate>,
    pub currency: &'a str,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub receivable_account_id: Uuid,
    pub tax_output_account_id: Option<Uuid>,
    pub notes: Option<&'a str>,
}

/// The invoice header `build_revenue_post` builds the GL envelope from.
pub struct InvoicePostSourceRow {
    pub invoice_number: String,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub invoice_date: chrono::NaiveDate,
    pub currency: String,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub receivable_account_id: Uuid,
    pub tax_output_account_id: Option<Uuid>,
}

/// `post_sales_invoice`'s idempotency short-circuit probe. `posting_state` is read as `::text` so an
/// unknown state falls through to a re-post attempt rather than panicking in a decode; the journal /
/// post ids are `Option` because they are only set once the GL has acked.
pub struct InvoicePostingStateRow {
    pub posting_state: String,
    pub journal_id: Option<Uuid>,
    pub accounting_post_id: Option<Uuid>,
}

/// Hand-written SalesInvoice SQL. Lives here (not in the write service) per the module's 4-layer rule:
/// services orchestrate and own the unit of work, repositories hold the SQL.
impl SalesInvoiceRepository {
    /// Insert a draft, unposted sales-invoice header.
    ///
    /// Takes the CALLER'S connection so the header and its lines commit as ONE unit. The caller binds
    /// the company on that connection (`bind_company_on`) before calling — don't re-bind here. The
    /// explicit `company_id` bind stays as defense-in-depth behind the RLS fence (ADR-0008).
    ///
    /// Returns the raw `sqlx::Error` deliberately: the caller inspects it for a unique violation to
    /// turn a duplicate invoice number into a domain error.
    pub async fn insert_draft(
        &self,
        conn: &mut sqlx::PgConnection,
        inv: &NewSalesInvoiceRow<'_>,
    ) -> Result<(), sqlx::Error> {
        sqlx::query(
            r#"INSERT INTO selling.sales_invoices
                (id, invoice_number, sales_order_id, company_id, branch_id, customer_id, status,
                 invoice_date, due_date, currency, subtotal, tax_rate, tax_amount, total,
                 outstanding_amount, receivable_account_id, tax_output_account_id, posting_state, notes)
               VALUES ($1,$2,$3,$4,$5,$6,'draft'::sales_invoice_status,$7,$8,$9,$10,$11,$12,$13,
                       0,$14,$15,'pending'::gl_posting_state,$16)"#,
        )
        .bind(inv.id).bind(inv.invoice_number).bind(inv.sales_order_id).bind(inv.company_id)
        .bind(inv.branch_id).bind(inv.customer_id).bind(inv.invoice_date).bind(inv.due_date)
        .bind(inv.currency).bind(inv.subtotal).bind(inv.tax_rate).bind(inv.tax_amount).bind(inv.total)
        .bind(inv.receivable_account_id).bind(inv.tax_output_account_id).bind(inv.notes)
        .execute(conn)
        .await?;
        Ok(())
    }

    /// Read the invoice header behind the revenue posting envelope.
    ///
    /// ID-only: no company argument to scope from up front, so this read rides the REQUEST-dedicated
    /// connection (established by `company_auth`), which carries the caller's `app.company_id` — RLS
    /// fences the lookup so another company's invoice simply isn't found. Under an EVENT or a job the
    /// caller must wrap this in `with_company_scope(Some(company_id))` or it fails closed.
    pub async fn find_post_source(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Option<InvoicePostSourceRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT invoice_number, company_id, branch_id, customer_id, invoice_date, currency,
                          subtotal, tax_amount, total, receivable_account_id, tax_output_account_id
                   FROM selling.sales_invoices
                   WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_id),
        ).await?;
        Ok(row.map(|r| InvoicePostSourceRow {
            invoice_number: r.get("invoice_number"),
            company_id: r.get("company_id"),
            branch_id: r.get("branch_id"),
            customer_id: r.get("customer_id"),
            invoice_date: r.get("invoice_date"),
            currency: r.get("currency"),
            tax_amount: r.get("tax_amount"),
            total: r.get("total"),
            receivable_account_id: r.get("receivable_account_id"),
            tax_output_account_id: r.get("tax_output_account_id"),
        }))
    }

    /// Probe an invoice's GL posting state — `post_sales_invoice`'s already-posted short-circuit.
    /// ID-only, same scoping as [`Self::find_post_source`].
    pub async fn find_posting_state(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Option<InvoicePostingStateRow>, sqlx::Error> {
        let row = company_scope::fetch_optional_row_scoped(
            pool,
            sqlx::query(
                r#"SELECT posting_state::text AS ps, journal_id, accounting_post_id
                   FROM selling.sales_invoices WHERE id=$1 AND (metadata->>'deleted_at') IS NULL"#,
            )
            .bind(invoice_id),
        ).await?;
        Ok(row.map(|r| InvoicePostingStateRow {
            posting_state: r.get("ps"),
            journal_id: r.get("journal_id"),
            accounting_post_id: r.get("accounting_post_id"),
        }))
    }

    /// Reconcile an invoice from the GL's ack: posted + submitted, carrying the journal/post ids, and
    /// `outstanding_amount = total` (the debt becomes real only once the revenue is booked).
    ///
    /// The `posting_state <> 'posted'` clause is a once-only gate — defense-in-depth beside
    /// accounting's own partial unique index, which is the authoritative arbiter of double posts.
    ///
    /// ID-only — inherits the caller's scope (`post_sales_invoice`).
    pub async fn reconcile_posted(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
        journal_id: Uuid,
        post_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.sales_invoices
                   SET posting_state='posted'::gl_posting_state,
                       status='submitted'::sales_invoice_status,
                       journal_id=$2, accounting_post_id=$3, posted_at=now(),
                       outstanding_amount=total
                   WHERE id=$1 AND posting_state <> 'posted'::gl_posting_state"#,
            )
            .bind(invoice_id).bind(journal_id).bind(post_id),
        ).await?;
        Ok(())
    }

    /// Record that the GL rejected this invoice's post (audit/retry). ID-only — inherits the caller's
    /// scope (`post_sales_invoice`).
    pub async fn mark_post_failed(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<(), sqlx::Error> {
        company_scope::execute_scoped(
            pool,
            sqlx::query(
                r#"UPDATE selling.sales_invoices SET posting_state='failed'::gl_posting_state WHERE id=$1"#,
            )
            .bind(invoice_id),
        ).await?;
        Ok(())
    }

    /// Read an invoice's total for the `SalesInvoicePosted` event. ID-only — inherits the caller's
    /// scope (`post_sales_invoice`).
    pub async fn fetch_total(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Decimal, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT total FROM selling.sales_invoices WHERE id=$1")
                .bind(invoice_id),
        ).await
    }

    /// Read the order an invoice was raised from, if any (`None` = a direct invoice). ID-only —
    /// inherits the caller's scope (`post_sales_invoice`, via `advance_billing_watermarks`).
    pub async fn fetch_sales_order_id(
        &self,
        pool: &PgPool,
        invoice_id: Uuid,
    ) -> Result<Option<Uuid>, sqlx::Error> {
        company_scope::fetch_one_scalar_scoped(
            pool,
            sqlx::query_scalar("SELECT sales_order_id FROM selling.sales_invoices WHERE id=$1")
                .bind(invoice_id),
        ).await
    }
}

backbone_core::impl_crud_repository!(SalesInvoiceRepository, SalesInvoice, soft_delete);
