//! Validator for DeliveryCarrier entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<DeliveryCarrier>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::DeliveryCarrier;

/// Validator type alias for DeliveryCarrier entities.
pub type DeliveryCarrierValidator = EntityValidator<DeliveryCarrier>;

/// Build a validator for DeliveryCarrier with all schema-defined field rules.
pub fn delivery_carrier_validator() -> DeliveryCarrierValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &DeliveryCarrier| &e.name))
        .rule(OptionalNotBlank::new("tracking_url_template", |e: &DeliveryCarrier| e.tracking_url_template.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
