//! Validator for SalesPersonAllocation entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalesPersonAllocation>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative};
use crate::domain::entity::SalesPersonAllocation;

/// Validator type alias for SalesPersonAllocation entities.
pub type SalesPersonAllocationValidator = EntityValidator<SalesPersonAllocation>;

/// Build a validator for SalesPersonAllocation with all schema-defined field rules.
pub fn sales_person_allocation_validator() -> SalesPersonAllocationValidator {
    EntityValidator::new()
    // <<< CUSTOM RULES
    // END CUSTOM RULES
        // No schema-derived rules — add custom rules above.
}

// <<< CUSTOM
// END CUSTOM
