//! Validator for SalesTeam entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalesTeam>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{OptionalNotBlank, RequiredString};
use crate::domain::entity::SalesTeam;

/// Validator type alias for SalesTeam entities.
pub type SalesTeamValidator = EntityValidator<SalesTeam>;

/// Build a validator for SalesTeam with all schema-defined field rules.
pub fn sales_team_validator() -> SalesTeamValidator {
    EntityValidator::new()
        .rule(RequiredString::new("name", |e: &SalesTeam| &e.name))
        .rule(OptionalNotBlank::new("description", |e: &SalesTeam| e.description.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
