//! Validator for SalesOrder entity
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Returns an `EntityValidator<SalesOrder>` pre-loaded with schema-derived
//! field rules. Extend in the `// <<< CUSTOM` zone.

use backbone_core::{EntityValidator, ValidationErrors, ValidationError};
use backbone_core::{NonNegative, OptionalNotBlank, RequiredString};
use crate::domain::entity::SalesOrder;

/// Validator type alias for SalesOrder entities.
pub type SalesOrderValidator = EntityValidator<SalesOrder>;

/// Build a validator for SalesOrder with all schema-defined field rules.
pub fn sales_order_validator() -> SalesOrderValidator {
    EntityValidator::new()
        .rule(RequiredString::new("order_number", |e: &SalesOrder| &e.order_number))
        .rule(RequiredString::new("currency", |e: &SalesOrder| &e.currency))
        .rule(OptionalNotBlank::new("notes", |e: &SalesOrder| e.notes.as_deref()))
    // <<< CUSTOM RULES
    // END CUSTOM RULES
}

// <<< CUSTOM
// END CUSTOM
