//! Domain Entities
//!
//! Generated by metaphor-schema. Do not edit manually.

pub mod quotation;
pub mod quotation_item;
pub mod sales_invoice;
pub mod sales_invoice_item;
pub mod sales_order;
pub mod sales_order_item;
pub mod sales_team;
pub mod sales_person_allocation;
pub mod quotation_status;
pub mod sales_invoice_status;
pub mod gl_posting_state;
pub mod sales_order_status;

// Re-exports
pub use quotation::Quotation;
pub use quotation::QuotationBuilder;
pub use quotation::QuotationId;
pub use quotation_item::QuotationItem;
pub use quotation_item::QuotationItemBuilder;
pub use quotation_item::QuotationItemId;
pub use sales_invoice::SalesInvoice;
pub use sales_invoice::SalesInvoiceBuilder;
pub use sales_invoice::SalesInvoiceId;
pub use sales_invoice_item::SalesInvoiceItem;
pub use sales_invoice_item::SalesInvoiceItemBuilder;
pub use sales_invoice_item::SalesInvoiceItemId;
pub use sales_order::SalesOrder;
pub use sales_order::SalesOrderBuilder;
pub use sales_order::SalesOrderId;
pub use sales_order_item::SalesOrderItem;
pub use sales_order_item::SalesOrderItemBuilder;
pub use sales_order_item::SalesOrderItemId;
pub use sales_team::SalesTeam;
pub use sales_team::SalesTeamBuilder;
pub use sales_team::SalesTeamId;
pub use sales_person_allocation::SalesPersonAllocation;
pub use sales_person_allocation::SalesPersonAllocationBuilder;
pub use sales_person_allocation::SalesPersonAllocationId;
pub use quotation_status::QuotationStatus;
pub use sales_invoice_status::SalesInvoiceStatus;
pub use gl_posting_state::GlPostingState;
pub use sales_order_status::SalesOrderStatus;

// ==========================================================================
// Entity Trait
// ==========================================================================

use std::fmt::Debug;

/// Trait for domain entities
///
/// All generated entities implement this trait, providing
/// a common interface for working with domain objects.
pub trait Entity: Debug + Clone {
    /// The type of the entity's unique identifier
    type Id: Debug + Clone + PartialEq;

    /// Get the entity's unique identifier
    fn entity_id(&self) -> &Self::Id;

    /// Get the entity type name
    fn entity_type() -> &'static str;
}

// ==========================================================================
// Audit Metadata
// ==========================================================================

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;
#[cfg(feature = "openapi")]
use utoipa::ToSchema;

/// Audit metadata stored as JSONB in the database
///
/// This struct consolidates audit fields (timestamps and actors) into a single
/// JSONB column for efficient storage and flexible querying.
#[derive(Debug, Clone, Default, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "openapi", derive(ToSchema))]
pub struct AuditMetadata {
    /// Timestamp when the record was created
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was last updated
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_at: Option<DateTime<Utc>>,

    /// Timestamp when the record was soft-deleted
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_at: Option<DateTime<Utc>>,

    /// User ID who created the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Uuid>,

    /// User ID who last updated the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub updated_by: Option<Uuid>,

    /// User ID who deleted the record
    #[serde(skip_serializing_if = "Option::is_none")]
    pub deleted_by: Option<Uuid>,
}

impl AuditMetadata {
    /// Create new audit metadata with created_at set to now
    pub fn new() -> Self {
        Self {
            created_at: Some(Utc::now()),
            ..Default::default()
        }
    }

    /// Create with creator ID
    pub fn with_creator(creator_id: Uuid) -> Self {
        Self {
            created_at: Some(Utc::now()),
            created_by: Some(creator_id),
            ..Default::default()
        }
    }

    /// Touch the record (update updated_at)
    pub fn touch(&mut self) {
        self.updated_at = Some(Utc::now());
    }

    /// Touch with updater ID
    pub fn touch_by(&mut self, updater_id: Uuid) {
        self.updated_at = Some(Utc::now());
        self.updated_by = Some(updater_id);
    }

    /// Soft delete the record
    pub fn soft_delete(&mut self) {
        self.deleted_at = Some(Utc::now());
    }

    /// Soft delete with deleter ID
    pub fn soft_delete_by(&mut self, deleter_id: Uuid) {
        self.deleted_at = Some(Utc::now());
        self.deleted_by = Some(deleter_id);
    }

    /// Restore a soft-deleted record
    pub fn restore(&mut self) {
        self.deleted_at = None;
        self.deleted_by = None;
    }

    /// Check if record is deleted
    pub fn is_deleted(&self) -> bool {
        self.deleted_at.is_some()
    }

    /// Check if record is active (not deleted)
    pub fn is_active(&self) -> bool {
        self.deleted_at.is_none()
    }
}
