//! Auth configuration for QuotationItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<QuotationItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QuotationItemService;
use crate::domain::entity::QuotationItem;

/// Permission string constants for QuotationItem operations.
pub mod permissions {
    pub const LIST:        &str = "quotation_item:list";
    pub const READ:        &str = "quotation_item:read";
    pub const CREATE:      &str = "quotation_item:create";
    pub const UPDATE:      &str = "quotation_item:update";
    pub const DELETE:      &str = "quotation_item:delete";
    pub const RESTORE:     &str = "quotation_item:restore";
    pub const TRASH:       &str = "quotation_item:trash";
    pub const EMPTY_TRASH: &str = "quotation_item:empty_trash";
    pub const BULK_CREATE: &str = "quotation_item:bulk_create";
    pub const UPSERT:      &str = "quotation_item:upsert";
}

/// Resource policy for QuotationItem — maps CRUD actions to permission strings.
pub struct QuotationItemPolicy;

#[async_trait]
impl ResourcePolicy<QuotationItem> for QuotationItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &QuotationItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for QuotationItem handlers.
///
/// Wraps `QuotationItemService` and checks `QuotationItemPolicy` before delegating.
pub type QuotationItemGuard = PermissionGuard<QuotationItem>;

/// Service-integrated permission guard for QuotationItem (for use in generated handlers).
pub type QuotationItemServiceGuard = ServicePermissionGuard<QuotationItem, QuotationItemService, QuotationItemPolicy>;

// <<< CUSTOM
// END CUSTOM
