//! Auth configuration for Quotation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<Quotation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::QuotationService;
use crate::domain::entity::Quotation;

/// Permission string constants for Quotation operations.
pub mod permissions {
    pub const LIST:        &str = "quotation:list";
    pub const READ:        &str = "quotation:read";
    pub const CREATE:      &str = "quotation:create";
    pub const UPDATE:      &str = "quotation:update";
    pub const DELETE:      &str = "quotation:delete";
    pub const RESTORE:     &str = "quotation:restore";
    pub const TRASH:       &str = "quotation:trash";
    pub const EMPTY_TRASH: &str = "quotation:empty_trash";
    pub const BULK_CREATE: &str = "quotation:bulk_create";
    pub const UPSERT:      &str = "quotation:upsert";
}

/// Resource policy for Quotation — maps CRUD actions to permission strings.
pub struct QuotationPolicy;

#[async_trait]
impl ResourcePolicy<Quotation> for QuotationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &Quotation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for Quotation handlers.
///
/// Wraps `QuotationService` and checks `QuotationPolicy` before delegating.
pub type QuotationGuard = PermissionGuard<Quotation>;

/// Service-integrated permission guard for Quotation (for use in generated handlers).
pub type QuotationServiceGuard = ServicePermissionGuard<Quotation, QuotationService, QuotationPolicy>;

// <<< CUSTOM
// END CUSTOM
