//! Auth configuration for SalesOrderItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalesOrderItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalesOrderItemService;
use crate::domain::entity::SalesOrderItem;

/// Permission string constants for SalesOrderItem operations.
pub mod permissions {
    pub const LIST:        &str = "sales_order_item:list";
    pub const READ:        &str = "sales_order_item:read";
    pub const CREATE:      &str = "sales_order_item:create";
    pub const UPDATE:      &str = "sales_order_item:update";
    pub const DELETE:      &str = "sales_order_item:delete";
    pub const RESTORE:     &str = "sales_order_item:restore";
    pub const TRASH:       &str = "sales_order_item:trash";
    pub const EMPTY_TRASH: &str = "sales_order_item:empty_trash";
    pub const BULK_CREATE: &str = "sales_order_item:bulk_create";
    pub const UPSERT:      &str = "sales_order_item:upsert";
}

/// Resource policy for SalesOrderItem — maps CRUD actions to permission strings.
pub struct SalesOrderItemPolicy;

#[async_trait]
impl ResourcePolicy<SalesOrderItem> for SalesOrderItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalesOrderItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalesOrderItem handlers.
///
/// Wraps `SalesOrderItemService` and checks `SalesOrderItemPolicy` before delegating.
pub type SalesOrderItemGuard = PermissionGuard<SalesOrderItem>;

/// Service-integrated permission guard for SalesOrderItem (for use in generated handlers).
pub type SalesOrderItemServiceGuard = ServicePermissionGuard<SalesOrderItem, SalesOrderItemService, SalesOrderItemPolicy>;

// <<< CUSTOM
// END CUSTOM
