//! Auth configuration for SalesInvoiceItem handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalesInvoiceItem>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalesInvoiceItemService;
use crate::domain::entity::SalesInvoiceItem;

/// Permission string constants for SalesInvoiceItem operations.
pub mod permissions {
    pub const LIST:        &str = "sales_invoice_item:list";
    pub const READ:        &str = "sales_invoice_item:read";
    pub const CREATE:      &str = "sales_invoice_item:create";
    pub const UPDATE:      &str = "sales_invoice_item:update";
    pub const DELETE:      &str = "sales_invoice_item:delete";
    pub const RESTORE:     &str = "sales_invoice_item:restore";
    pub const TRASH:       &str = "sales_invoice_item:trash";
    pub const EMPTY_TRASH: &str = "sales_invoice_item:empty_trash";
    pub const BULK_CREATE: &str = "sales_invoice_item:bulk_create";
    pub const UPSERT:      &str = "sales_invoice_item:upsert";
}

/// Resource policy for SalesInvoiceItem — maps CRUD actions to permission strings.
pub struct SalesInvoiceItemPolicy;

#[async_trait]
impl ResourcePolicy<SalesInvoiceItem> for SalesInvoiceItemPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalesInvoiceItem,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalesInvoiceItem handlers.
///
/// Wraps `SalesInvoiceItemService` and checks `SalesInvoiceItemPolicy` before delegating.
pub type SalesInvoiceItemGuard = PermissionGuard<SalesInvoiceItem>;

/// Service-integrated permission guard for SalesInvoiceItem (for use in generated handlers).
pub type SalesInvoiceItemServiceGuard = ServicePermissionGuard<SalesInvoiceItem, SalesInvoiceItemService, SalesInvoiceItemPolicy>;

// <<< CUSTOM
// END CUSTOM
