//! Auth configuration for SalesTeam handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalesTeam>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalesTeamService;
use crate::domain::entity::SalesTeam;

/// Permission string constants for SalesTeam operations.
pub mod permissions {
    pub const LIST:        &str = "sales_team:list";
    pub const READ:        &str = "sales_team:read";
    pub const CREATE:      &str = "sales_team:create";
    pub const UPDATE:      &str = "sales_team:update";
    pub const DELETE:      &str = "sales_team:delete";
    pub const RESTORE:     &str = "sales_team:restore";
    pub const TRASH:       &str = "sales_team:trash";
    pub const EMPTY_TRASH: &str = "sales_team:empty_trash";
    pub const BULK_CREATE: &str = "sales_team:bulk_create";
    pub const UPSERT:      &str = "sales_team:upsert";
}

/// Resource policy for SalesTeam — maps CRUD actions to permission strings.
pub struct SalesTeamPolicy;

#[async_trait]
impl ResourcePolicy<SalesTeam> for SalesTeamPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalesTeam,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalesTeam handlers.
///
/// Wraps `SalesTeamService` and checks `SalesTeamPolicy` before delegating.
pub type SalesTeamGuard = PermissionGuard<SalesTeam>;

/// Service-integrated permission guard for SalesTeam (for use in generated handlers).
pub type SalesTeamServiceGuard = ServicePermissionGuard<SalesTeam, SalesTeamService, SalesTeamPolicy>;

// <<< CUSTOM
// END CUSTOM
