//! Auth configuration for SalesOrder handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalesOrder>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalesOrderService;
use crate::domain::entity::SalesOrder;

/// Permission string constants for SalesOrder operations.
pub mod permissions {
    pub const LIST:        &str = "sales_order:list";
    pub const READ:        &str = "sales_order:read";
    pub const CREATE:      &str = "sales_order:create";
    pub const UPDATE:      &str = "sales_order:update";
    pub const DELETE:      &str = "sales_order:delete";
    pub const RESTORE:     &str = "sales_order:restore";
    pub const TRASH:       &str = "sales_order:trash";
    pub const EMPTY_TRASH: &str = "sales_order:empty_trash";
    pub const BULK_CREATE: &str = "sales_order:bulk_create";
    pub const UPSERT:      &str = "sales_order:upsert";
}

/// Resource policy for SalesOrder — maps CRUD actions to permission strings.
pub struct SalesOrderPolicy;

#[async_trait]
impl ResourcePolicy<SalesOrder> for SalesOrderPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalesOrder,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalesOrder handlers.
///
/// Wraps `SalesOrderService` and checks `SalesOrderPolicy` before delegating.
pub type SalesOrderGuard = PermissionGuard<SalesOrder>;

/// Service-integrated permission guard for SalesOrder (for use in generated handlers).
pub type SalesOrderServiceGuard = ServicePermissionGuard<SalesOrder, SalesOrderService, SalesOrderPolicy>;

// <<< CUSTOM
// END CUSTOM
