//! Auth configuration for SalesPersonAllocation handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Implements `ResourcePolicy<SalesPersonAllocation>` with entity-specific permission
//! string constants. Guard middleware logic lives in backbone-auth.

use backbone_auth::{ResourcePolicy, ResourceAction, PermissionGuard, ServicePermissionGuard};
use async_trait::async_trait;

use crate::application::service::SalesPersonAllocationService;
use crate::domain::entity::SalesPersonAllocation;

/// Permission string constants for SalesPersonAllocation operations.
pub mod permissions {
    pub const LIST:        &str = "sales_person_allocation:list";
    pub const READ:        &str = "sales_person_allocation:read";
    pub const CREATE:      &str = "sales_person_allocation:create";
    pub const UPDATE:      &str = "sales_person_allocation:update";
    pub const DELETE:      &str = "sales_person_allocation:delete";
    pub const RESTORE:     &str = "sales_person_allocation:restore";
    pub const TRASH:       &str = "sales_person_allocation:trash";
    pub const EMPTY_TRASH: &str = "sales_person_allocation:empty_trash";
    pub const BULK_CREATE: &str = "sales_person_allocation:bulk_create";
    pub const UPSERT:      &str = "sales_person_allocation:upsert";
}

/// Resource policy for SalesPersonAllocation — maps CRUD actions to permission strings.
pub struct SalesPersonAllocationPolicy;

#[async_trait]
impl ResourcePolicy<SalesPersonAllocation> for SalesPersonAllocationPolicy {
    async fn can(
        &self,
        action: ResourceAction,
        _entity: &SalesPersonAllocation,
        ctx: &backbone_auth::middleware::AuthContext,
    ) -> bool {
        let required = match action {
            ResourceAction::Read | ResourceAction::List => permissions::READ,
            ResourceAction::Create => permissions::CREATE,
            ResourceAction::Update | ResourceAction::Patch => permissions::UPDATE,
            ResourceAction::Delete | ResourceAction::HardDelete => permissions::DELETE,
            ResourceAction::Restore => permissions::RESTORE,
            ResourceAction::Custom(_) => return false,
        };
        ctx.permissions.iter().any(|p| p == required)
    }
}

/// Permission guard for SalesPersonAllocation handlers.
///
/// Wraps `SalesPersonAllocationService` and checks `SalesPersonAllocationPolicy` before delegating.
pub type SalesPersonAllocationGuard = PermissionGuard<SalesPersonAllocation>;

/// Service-integrated permission guard for SalesPersonAllocation (for use in generated handlers).
pub type SalesPersonAllocationServiceGuard = ServicePermissionGuard<SalesPersonAllocation, SalesPersonAllocationService, SalesPersonAllocationPolicy>;

// <<< CUSTOM
// END CUSTOM
