//! Integration Test Implementations
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Contains CRUD API tests for all entities.

pub mod crud_test_base;

pub mod quotation_api_test;
pub mod quotation_item_api_test;
pub mod sales_invoice_api_test;
pub mod sales_invoice_item_api_test;
pub mod sales_order_api_test;
pub mod sales_order_item_api_test;
pub mod sales_team_api_test;
pub mod sales_person_allocation_api_test;

// Re-exports for convenience
pub use quotation_api_test::*;
pub use quotation_item_api_test::*;
pub use sales_invoice_api_test::*;
pub use sales_invoice_item_api_test::*;
pub use sales_order_api_test::*;
pub use sales_order_item_api_test::*;
pub use sales_team_api_test::*;
pub use sales_person_allocation_api_test::*;
