//! Quotation API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the Quotation CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// QUOTATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for Quotation
pub struct QuotationTestData;

impl TestDataGenerator for QuotationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "quotation_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "customer_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "quotation_date": Utc::now().format("%Y-%m-%d").to_string(),
            "valid_until": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subtotal": 0,
            "tax_rate": 0,
            "tax_amount": 0,
            "total": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "quotation_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "customer_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "quotation_date": Utc::now().format("%Y-%m-%d").to_string(),
            "valid_until": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subtotal": 0,
            "tax_rate": 0,
            "tax_amount": 0,
            "total": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// QUOTATION API TEST
// ============================================================================

/// Quotation API test suite
pub struct QuotationApiTest {
    inner: GenericCrudTest<QuotationTestData>,
}

impl QuotationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/quotations", "Quotation");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, QuotationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for QuotationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_quotation_crud() {
        let mut test = QuotationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add Quotation specific tests here
// <<< CUSTOM TESTS END >>>
