//! QuotationItem API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the QuotationItem CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// QUOTATIONITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for QuotationItem
pub struct QuotationItemTestData;

impl TestDataGenerator for QuotationItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "quotation_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "line_discount": 0,
            "line_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "quotation_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "line_discount": 0,
            "line_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/quotations", &super::quotation_api_test::QuotationTestData).await {
            deps.push(("quotation_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// QUOTATIONITEM API TEST
// ============================================================================

/// QuotationItem API test suite
pub struct QuotationItemApiTest {
    inner: GenericCrudTest<QuotationItemTestData>,
}

impl QuotationItemApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/quotation_items", "QuotationItem");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, QuotationItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for QuotationItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_quotation_item_crud() {
        let mut test = QuotationItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add QuotationItem specific tests here
// <<< CUSTOM TESTS END >>>
