//! SalesInvoiceItem API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalesInvoiceItem CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALESINVOICEITEM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalesInvoiceItem
pub struct SalesInvoiceItemTestData;

impl TestDataGenerator for SalesInvoiceItemTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "invoice_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "sales_order_item_id": null,
            "revenue_account_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "line_discount": 0,
            "line_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "invoice_id": Uuid::new_v4().to_string(),
            "item_id": Uuid::new_v4().to_string(),
            "sales_order_item_id": null,
            "revenue_account_id": Uuid::new_v4().to_string(),
            "description": null,
            "quantity": 0,
            "unit_price": 0,
            "line_discount": 0,
            "line_amount": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/sales_invoices", &super::sales_invoice_api_test::SalesInvoiceTestData).await {
            deps.push(("invoice_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SALESINVOICEITEM API TEST
// ============================================================================

/// SalesInvoiceItem API test suite
pub struct SalesInvoiceItemApiTest {
    inner: GenericCrudTest<SalesInvoiceItemTestData>,
}

impl SalesInvoiceItemApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/sales_invoice_items", "SalesInvoiceItem");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalesInvoiceItemTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalesInvoiceItemApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sales_invoice_item_crud() {
        let mut test = SalesInvoiceItemApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalesInvoiceItem specific tests here
// <<< CUSTOM TESTS END >>>
