//! SalesOrder API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalesOrder CRUD API endpoints.

use chrono::Utc;
use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALESORDER TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalesOrder
pub struct SalesOrderTestData;

impl TestDataGenerator for SalesOrderTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "order_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "quotation_id": null,
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "customer_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "order_date": Utc::now().format("%Y-%m-%d").to_string(),
            "delivery_date": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subtotal": 0,
            "tax_rate": 0,
            "tax_amount": 0,
            "total": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "order_number": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "quotation_id": null,
            "company_id": Uuid::new_v4().to_string(),
            "branch_id": null,
            "customer_id": Uuid::new_v4().to_string(),
            "status": "draft",
            "order_date": Utc::now().format("%Y-%m-%d").to_string(),
            "delivery_date": null,
            "currency": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "subtotal": 0,
            "tax_rate": 0,
            "tax_amount": 0,
            "total": 0,
            "notes": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SALESORDER API TEST
// ============================================================================

/// SalesOrder API test suite
pub struct SalesOrderApiTest {
    inner: GenericCrudTest<SalesOrderTestData>,
}

impl SalesOrderApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/sales_orders", "SalesOrder");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalesOrderTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalesOrderApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sales_order_crud() {
        let mut test = SalesOrderApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalesOrder specific tests here
// <<< CUSTOM TESTS END >>>
