//! SalesTeam API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalesTeam CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALESTEAM TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalesTeam
pub struct SalesTeamTestData;

impl TestDataGenerator for SalesTeamTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "company_id": Uuid::new_v4().to_string(),
            "name": format!("Test {}", Uuid::new_v4().to_string().split('-').next().unwrap()),
            "description": null,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }
}

// ============================================================================
// SALESTEAM API TEST
// ============================================================================

/// SalesTeam API test suite
pub struct SalesTeamApiTest {
    inner: GenericCrudTest<SalesTeamTestData>,
}

impl SalesTeamApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/sales_teams", "SalesTeam");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalesTeamTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalesTeamApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sales_team_crud() {
        let mut test = SalesTeamApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalesTeam specific tests here
// <<< CUSTOM TESTS END >>>
