//! SalesPersonAllocation API Integration Tests
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Tests the SalesPersonAllocation CRUD API endpoints.

use serde_json::{json, Value};
use uuid::Uuid;

use super::crud_test_base::{CrudTestConfig, GenericCrudTest, TestDataGenerator};
use crate::integration::framework::ApiTest;
use crate::integration::helpers::CommonUtils;

// ============================================================================
// SALESPERSONALLOCATION TEST DATA GENERATOR
// ============================================================================

/// Test data generator for SalesPersonAllocation
pub struct SalesPersonAllocationTestData;

impl TestDataGenerator for SalesPersonAllocationTestData {
    fn generate_create_payload(&self, _utils: &CommonUtils) -> Value {
        json!({
            "id": Uuid::new_v4().to_string(),
            "order_id": Uuid::new_v4().to_string(),
            "sales_person_id": Uuid::new_v4().to_string(),
            "sales_team_id": null,
            "allocated_pct": 0,
            "metadata": json!({}),
        })
    }

    fn generate_update_payload(&self, id: &str, _utils: &CommonUtils) -> Value {
        json!({
            "id": id,
            "order_id": Uuid::new_v4().to_string(),
            "sales_person_id": Uuid::new_v4().to_string(),
            "sales_team_id": null,
            "allocated_pct": 0,
            "metadata": json!({}),
        })
    }

    fn generate_invalid_payload(&self) -> Value {
        json!({
            // Missing required fields
        })
    }

    async fn seed_dependencies(&self, api: &ApiTest) -> Vec<(String, String)> {
        let mut deps: Vec<(String, String)> = Vec::new();
        if let Some(id) = super::crud_test_base::create_and_get_id(api, "/api/v1/sales_orders", &super::sales_order_api_test::SalesOrderTestData).await {
            deps.push(("order_id".to_string(), id));
        }
        deps
    }
}

// ============================================================================
// SALESPERSONALLOCATION API TEST
// ============================================================================

/// SalesPersonAllocation API test suite
pub struct SalesPersonAllocationApiTest {
    inner: GenericCrudTest<SalesPersonAllocationTestData>,
}

impl SalesPersonAllocationApiTest {
    pub fn new() -> Self {
        let mut config = CrudTestConfig::new("/api/v1/sales_person_allocations", "SalesPersonAllocation");
        config.supports_soft_delete = true;
        Self {
            inner: GenericCrudTest::new(config, SalesPersonAllocationTestData),
        }
    }

    pub async fn run_all(&mut self) -> Vec<crate::integration::framework::TestResult> {
        self.inner.run_all().await
    }
}

impl Default for SalesPersonAllocationApiTest {
    fn default() -> Self {
        Self::new()
    }
}

// ============================================================================
// TESTS
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_sales_person_allocation_crud() {
        let mut test = SalesPersonAllocationApiTest::new();
        let results = test.run_all().await;

        for result in &results {
            println!("{:?}", result);
        }

        // Check all tests passed
        let failed: Vec<_> = results.iter().filter(|r| !r.success).collect();
        assert!(failed.is_empty(), "Some tests failed: {:?}", failed);
    }
}

// ============================================================================
// CUSTOM TESTS
// ============================================================================

// <<< CUSTOM TESTS START >>>
// Add SalesPersonAllocation specific tests here
// <<< CUSTOM TESTS END >>>
