//! Selling Module Handlers
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides:
//! - AppState dependency injection container
//! - Custom handler integration points

use std::sync::Arc;

// Import all services
use crate::application::service::DeliveryCarrierService;
use crate::application::service::ExpenseReinvoiceLinkService;
use crate::application::service::QuotationService;
use crate::application::service::QuotationItemService;
use crate::application::service::QuotationTemplateService;
use crate::application::service::SalesOrderService;
use crate::application::service::SalesOrderItemService;
use crate::application::service::SalesTeamService;
use crate::application::service::SalesPersonAllocationService;

/// Application state for dependency injection.
///
/// This struct holds references to all module services
/// and is passed to HTTP handlers via Axum's State extractor.
///
/// # Example
///
/// ```ignore
/// use axum::extract::State;
///
/// async fn custom_handler(
///     State(state): State<AppState>,
/// ) -> impl IntoResponse {
///     // Access services via state
/// }
/// ```
#[derive(Clone)]
pub struct AppState {
    /// DeliveryCarrier service
    pub delivery_carrier_service: Arc<DeliveryCarrierService>,
    /// ExpenseReinvoiceLink service
    pub expense_reinvoice_link_service: Arc<ExpenseReinvoiceLinkService>,
    /// Quotation service
    pub quotation_service: Arc<QuotationService>,
    /// QuotationItem service
    pub quotation_item_service: Arc<QuotationItemService>,
    /// QuotationTemplate service
    pub quotation_template_service: Arc<QuotationTemplateService>,
    /// SalesOrder service
    pub sales_order_service: Arc<SalesOrderService>,
    /// SalesOrderItem service
    pub sales_order_item_service: Arc<SalesOrderItemService>,
    /// SalesTeam service
    pub sales_team_service: Arc<SalesTeamService>,
    /// SalesPersonAllocation service
    pub sales_person_allocation_service: Arc<SalesPersonAllocationService>,
}

impl AppState {
    /// Create a new AppState with all services.
    pub fn new(
        delivery_carrier_service: Arc<DeliveryCarrierService>,
        expense_reinvoice_link_service: Arc<ExpenseReinvoiceLinkService>,
        quotation_service: Arc<QuotationService>,
        quotation_item_service: Arc<QuotationItemService>,
        quotation_template_service: Arc<QuotationTemplateService>,
        sales_order_service: Arc<SalesOrderService>,
        sales_order_item_service: Arc<SalesOrderItemService>,
        sales_team_service: Arc<SalesTeamService>,
        sales_person_allocation_service: Arc<SalesPersonAllocationService>
    ) -> Self {
        Self {
            delivery_carrier_service,
            expense_reinvoice_link_service,
            quotation_service,
            quotation_item_service,
            quotation_template_service,
            sales_order_service,
            sales_order_item_service,
            sales_team_service,
            sales_person_allocation_service,
        }
    }

    /// Create AppState from module instance.
    pub fn from_module(module: &crate::SellingModule) -> Self {
        Self {
            delivery_carrier_service: module.delivery_carrier_service.clone(),
            expense_reinvoice_link_service: module.expense_reinvoice_link_service.clone(),
            quotation_service: module.quotation_service.clone(),
            quotation_item_service: module.quotation_item_service.clone(),
            quotation_template_service: module.quotation_template_service.clone(),
            sales_order_service: module.sales_order_service.clone(),
            sales_order_item_service: module.sales_order_item_service.clone(),
            sales_team_service: module.sales_team_service.clone(),
            sales_person_allocation_service: module.sales_person_allocation_service.clone(),
        }
    }
}

/// Builder for AppState.
///
/// Allows incremental construction of AppState.
#[derive(Default)]
pub struct AppStateBuilder {
    delivery_carrier_service: Option<Arc<DeliveryCarrierService>>,
    expense_reinvoice_link_service: Option<Arc<ExpenseReinvoiceLinkService>>,
    quotation_service: Option<Arc<QuotationService>>,
    quotation_item_service: Option<Arc<QuotationItemService>>,
    quotation_template_service: Option<Arc<QuotationTemplateService>>,
    sales_order_service: Option<Arc<SalesOrderService>>,
    sales_order_item_service: Option<Arc<SalesOrderItemService>>,
    sales_team_service: Option<Arc<SalesTeamService>>,
    sales_person_allocation_service: Option<Arc<SalesPersonAllocationService>>,
}

impl AppStateBuilder {
    /// Create a new builder.
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the DeliveryCarrier service.
    pub fn with_delivery_carrier_service(mut self, service: Arc<DeliveryCarrierService>) -> Self {
        self.delivery_carrier_service = Some(service);
        self
    }

    /// Set the ExpenseReinvoiceLink service.
    pub fn with_expense_reinvoice_link_service(mut self, service: Arc<ExpenseReinvoiceLinkService>) -> Self {
        self.expense_reinvoice_link_service = Some(service);
        self
    }

    /// Set the Quotation service.
    pub fn with_quotation_service(mut self, service: Arc<QuotationService>) -> Self {
        self.quotation_service = Some(service);
        self
    }

    /// Set the QuotationItem service.
    pub fn with_quotation_item_service(mut self, service: Arc<QuotationItemService>) -> Self {
        self.quotation_item_service = Some(service);
        self
    }

    /// Set the QuotationTemplate service.
    pub fn with_quotation_template_service(mut self, service: Arc<QuotationTemplateService>) -> Self {
        self.quotation_template_service = Some(service);
        self
    }

    /// Set the SalesOrder service.
    pub fn with_sales_order_service(mut self, service: Arc<SalesOrderService>) -> Self {
        self.sales_order_service = Some(service);
        self
    }

    /// Set the SalesOrderItem service.
    pub fn with_sales_order_item_service(mut self, service: Arc<SalesOrderItemService>) -> Self {
        self.sales_order_item_service = Some(service);
        self
    }

    /// Set the SalesTeam service.
    pub fn with_sales_team_service(mut self, service: Arc<SalesTeamService>) -> Self {
        self.sales_team_service = Some(service);
        self
    }

    /// Set the SalesPersonAllocation service.
    pub fn with_sales_person_allocation_service(mut self, service: Arc<SalesPersonAllocationService>) -> Self {
        self.sales_person_allocation_service = Some(service);
        self
    }

    /// Build the AppState.
    ///
    /// # Panics
    ///
    /// Panics if any required service is not set.
    pub fn build(self) -> AppState {
        AppState {
            delivery_carrier_service: self.delivery_carrier_service.expect("delivery_carrier_service is required"),
            expense_reinvoice_link_service: self.expense_reinvoice_link_service.expect("expense_reinvoice_link_service is required"),
            quotation_service: self.quotation_service.expect("quotation_service is required"),
            quotation_item_service: self.quotation_item_service.expect("quotation_item_service is required"),
            quotation_template_service: self.quotation_template_service.expect("quotation_template_service is required"),
            sales_order_service: self.sales_order_service.expect("sales_order_service is required"),
            sales_order_item_service: self.sales_order_item_service.expect("sales_order_item_service is required"),
            sales_team_service: self.sales_team_service.expect("sales_team_service is required"),
            sales_person_allocation_service: self.sales_person_allocation_service.expect("sales_person_allocation_service is required"),
        }
    }
}
