//! OrderToCash flow implementation
//!
//! Generated by metaphor-schema
//!
//! A customer accepts a quotation; it converts to a sales order; the order is confirmed and billed;
//! the invoice's revenue posts to the GL and the order's billed watermarks advance to completion.

use serde::{Deserialize, Serialize};
use std::sync::Arc;
use chrono;
use backbone_core::flow::{WorkflowStep, WorkflowContext};

/// Error type for flow execution
#[derive(Debug, Clone, thiserror::Error)]
pub enum FlowError {
    #[error("No current step to execute")]
    NoCurrentStep,

    #[error("Step execution failed: {0}")]
    StepFailed(String),

    #[error("Condition evaluation failed: {0}")]
    ConditionFailed(String),

    #[error("Compensation failed: {0}")]
    CompensationFailed(String),

    #[error("Flow timed out")]
    Timeout,

    #[error("Flow cancelled")]
    Cancelled,

    #[error("Invalid state transition: {from} -> {to}")]
    InvalidTransition { from: String, to: String },
}

/// Execution status for OrderToCash flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderToCashFlowStatus {
    /// Flow is pending execution
    Pending,
    /// Flow is currently running
    Running,
    /// Flow is waiting for an event or condition
    Waiting,
    /// Flow completed successfully
    Completed,
    /// Flow failed
    Failed,
    /// Flow was cancelled
    Cancelled,
    /// Flow is compensating (rolling back)
    Compensating,
}

/// Steps in OrderToCash flow
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum OrderToCashFlowStep {
    /// convert_to_order
    ConvertToOrder,
    /// confirm_order
    ConfirmOrder,
    /// raise_invoice
    RaiseInvoice,
    /// post_revenue
    PostRevenue,
    /// done
    Done,
    /// post_failed
    PostFailed,
    /// rejected
    Rejected,
}

/// Instance of OrderToCash flow execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OrderToCashFlowInstance {
    /// Unique instance ID
    pub id: String,
    /// Current status
    pub status: OrderToCashFlowStatus,
    /// Current step
    pub current_step: Option<OrderToCashFlowStep>,
    /// Flow context (variables)
    pub context: serde_json::Value,
    /// Completed steps
    pub completed_steps: Vec<OrderToCashFlowStep>,
    /// Error if failed
    pub error: Option<String>,
    /// Created timestamp
    pub created_at: chrono::DateTime<chrono::Utc>,
    /// Updated timestamp
    pub updated_at: chrono::DateTime<chrono::Utc>,
}

impl OrderToCashFlowInstance {
    /// Create a new flow instance
    pub fn new(id: impl Into<String>) -> Self {
        let now = chrono::Utc::now();
        Self {
            id: id.into(),
            status: OrderToCashFlowStatus::Pending,
            current_step: None,
            context: serde_json::json!({}),
            completed_steps: Vec::new(),
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    /// Check if flow is complete
    pub fn is_complete(&self) -> bool {
        matches!(
            self.status,
            OrderToCashFlowStatus::Completed | OrderToCashFlowStatus::Failed | OrderToCashFlowStatus::Cancelled
        )
    }

    /// Check if flow is running
    pub fn is_running(&self) -> bool {
        matches!(
            self.status,
            OrderToCashFlowStatus::Running | OrderToCashFlowStatus::Waiting
        )
    }

    /// Set a context variable
    pub fn set_context(&mut self, key: &str, value: serde_json::Value) {
        if let serde_json::Value::Object(ref mut map) = self.context {
            map.insert(key.to_string(), value);
        }
        self.updated_at = chrono::Utc::now();
    }

    /// Get a context variable
    pub fn get_context(&self, key: &str) -> Option<&serde_json::Value> {
        if let serde_json::Value::Object(ref map) = self.context {
            map.get(key)
        } else {
            None
        }
    }
}

// Phase 1: FlowInstance satisfies backbone_core::flow::WorkflowContext.
// The entity() accessor requires the entity to be carried in the instance;
// add `pub entity: OrderToCash` in the // <<< CUSTOM section and remove the todo!.
#[allow(unused_variables)]
impl WorkflowContext<OrderToCashFlowInstance> for OrderToCashFlowInstance {
    fn entity(&self) -> &OrderToCashFlowInstance { self }
    fn set_var(&mut self, key: &str, value: serde_json::Value) {
        self.set_context(key, value);
    }
    fn get_var(&self, key: &str) -> Option<&serde_json::Value> {
        self.get_context(key)
    }
}

/// Step handler trait for OrderToCash flow
#[async_trait::async_trait]
pub trait OrderToCashStepHandler: Send + Sync {
    /// Handle convert_to_order step
    async fn handle_convert_to_order(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<Option<OrderToCashFlowStep>, FlowError>;

    /// Handle confirm_order step
    async fn handle_confirm_order(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<Option<OrderToCashFlowStep>, FlowError>;

    /// Handle raise_invoice step
    async fn handle_raise_invoice(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<Option<OrderToCashFlowStep>, FlowError>;

    /// Handle post_revenue step
    async fn handle_post_revenue(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<Option<OrderToCashFlowStep>, FlowError>;

    /// Handle terminal step done
    async fn handle_done(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step post_failed
    async fn handle_post_failed(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<(), FlowError>;

    /// Handle terminal step rejected
    async fn handle_rejected(
        &self,
        instance: &mut OrderToCashFlowInstance,
    ) -> Result<(), FlowError>;

}

/// Executor for OrderToCash flow
pub struct OrderToCashFlowExecutor<H: OrderToCashStepHandler> {
    handler: Arc<H>,
}

impl<H: OrderToCashStepHandler> OrderToCashFlowExecutor<H> {
    /// Create a new flow executor
    pub fn new(handler: Arc<H>) -> Self {
        Self { handler }
    }

    /// Start a new flow instance
    pub async fn start(&self, instance_id: impl Into<String>) -> Result<OrderToCashFlowInstance, FlowError> {
        let mut instance = OrderToCashFlowInstance::new(instance_id);
        instance.status = OrderToCashFlowStatus::Running;
        instance.current_step = Some(OrderToCashFlowStep::ConvertToOrder);
        Ok(instance)
    }

    /// Execute the current step
    pub async fn execute_step(&self, instance: &mut OrderToCashFlowInstance) -> Result<(), FlowError> {
        let current_step = match instance.current_step {
            Some(step) => step,
            None => return Err(FlowError::NoCurrentStep),
        };

        let next_step = match current_step {
            OrderToCashFlowStep::ConvertToOrder => {
                self.handler.handle_convert_to_order(instance).await?
            }
            OrderToCashFlowStep::ConfirmOrder => {
                self.handler.handle_confirm_order(instance).await?
            }
            OrderToCashFlowStep::RaiseInvoice => {
                self.handler.handle_raise_invoice(instance).await?
            }
            OrderToCashFlowStep::PostRevenue => {
                self.handler.handle_post_revenue(instance).await?
            }
            OrderToCashFlowStep::Done => {
                self.handler.handle_done(instance).await?;
                None // Terminal step
            }
            OrderToCashFlowStep::PostFailed => {
                self.handler.handle_post_failed(instance).await?;
                None // Terminal step
            }
            OrderToCashFlowStep::Rejected => {
                self.handler.handle_rejected(instance).await?;
                None // Terminal step
            }
        };

        // Mark current step as completed
        instance.completed_steps.push(current_step);

        // Move to next step
        match next_step {
            Some(next) => {
                instance.current_step = Some(next);
            }
            None => {
                instance.current_step = None;
                instance.status = OrderToCashFlowStatus::Completed;
            }
        }

        instance.updated_at = chrono::Utc::now();
        Ok(())
    }

    /// Run the flow to completion
    pub async fn run(&self, instance: &mut OrderToCashFlowInstance) -> Result<(), FlowError> {
        while !instance.is_complete() && instance.status != OrderToCashFlowStatus::Waiting {
            self.execute_step(instance).await?;
        }
        Ok(())
    }

    /// Cancel the flow
    pub fn cancel(&self, instance: &mut OrderToCashFlowInstance) {
        instance.status = OrderToCashFlowStatus::Cancelled;
        instance.updated_at = chrono::Utc::now();
    }

    /// Mark flow as failed
    pub fn fail(&self, instance: &mut OrderToCashFlowInstance, error: impl Into<String>) {
        instance.status = OrderToCashFlowStatus::Failed;
        instance.error = Some(error.into());
        instance.updated_at = chrono::Utc::now();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_flow_instance_creation() {
        let instance = OrderToCashFlowInstance::new("test-1");
        assert_eq!(instance.id, "test-1");
        assert_eq!(instance.status, OrderToCashFlowStatus::Pending);
        assert!(!instance.is_complete());
    }

    #[test]
    fn test_flow_context() {
        let mut instance = OrderToCashFlowInstance::new("test-2");
        instance.set_context("key", serde_json::json!("value"));
        let value = instance.get_context("key");
        assert_eq!(value, Some(&serde_json::json!("value")));
    }

    #[test]
    fn test_flow_status_transitions() {
        let mut instance = OrderToCashFlowInstance::new("test-3");
        assert!(!instance.is_running());

        instance.status = OrderToCashFlowStatus::Running;
        assert!(instance.is_running());
        assert!(!instance.is_complete());

        instance.status = OrderToCashFlowStatus::Completed;
        assert!(instance.is_complete());
        assert!(!instance.is_running());
    }
}