//! HTTP route configuration
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module provides consolidated Axum route configuration using backbone-core's
//! BackboneCrudHandler for all 12 standard Backbone CRUD endpoints per entity.

use axum::Router;
use std::sync::Arc;

use super::{
    quotation_handler::create_quotation_routes,
    quotation_item_handler::create_quotation_item_routes,
    sales_invoice_handler::create_sales_invoice_routes,
    sales_invoice_item_handler::create_sales_invoice_item_routes,
    sales_order_handler::create_sales_order_routes,
    sales_order_item_handler::create_sales_order_item_routes,
    sales_team_handler::create_sales_team_routes,
    sales_person_allocation_handler::create_sales_person_allocation_routes,
};

use crate::application::service::{
    QuotationService,
    QuotationItemService,
    SalesInvoiceService,
    SalesInvoiceItemService,
    SalesOrderService,
    SalesOrderItemService,
    SalesTeamService,
    SalesPersonAllocationService,
};

/// Services collection for all CRUD endpoints
pub struct HttpServices {
    pub quotation: Arc<QuotationService>,
    pub quotation_item: Arc<QuotationItemService>,
    pub sales_invoice: Arc<SalesInvoiceService>,
    pub sales_invoice_item: Arc<SalesInvoiceItemService>,
    pub sales_order: Arc<SalesOrderService>,
    pub sales_order_item: Arc<SalesOrderItemService>,
    pub sales_team: Arc<SalesTeamService>,
    pub sales_person_allocation: Arc<SalesPersonAllocationService>,
}

/// Configure all HTTP routes for this module using Axum and BackboneCrudHandler.
///
/// Each entity gets 12 standard Backbone CRUD endpoints:
/// 1. GET /api/v1/{collection} - List with pagination
/// 2. POST /api/v1/{collection} - Create
/// 3. GET /api/v1/{collection}/:id - Get by ID
/// 4. PUT /api/v1/{collection}/:id - Full update
/// 5. PATCH /api/v1/{collection}/:id - Partial update
/// 6. DELETE /api/v1/{collection}/:id - Soft delete
/// 7. POST /api/v1/{collection}/bulk - Bulk create
/// 8. POST /api/v1/{collection}/upsert - Upsert
/// 9. GET /api/v1/{collection}/trash - List deleted
/// 10. POST /api/v1/{collection}/:id/restore - Restore
/// 11. DELETE /api/v1/{collection}/empty - Empty trash
/// 12. GET /api/v1/{collection}/:id/deleted - Get deleted by ID
pub fn configure_routes(services: HttpServices) -> Router {
    Router::new()
        // Quotation routes (12 Backbone endpoints)
        .merge(create_quotation_routes(services.quotation))
        // QuotationItem routes (12 Backbone endpoints)
        .merge(create_quotation_item_routes(services.quotation_item))
        // SalesInvoice routes (12 Backbone endpoints)
        .merge(create_sales_invoice_routes(services.sales_invoice))
        // SalesInvoiceItem routes (12 Backbone endpoints)
        .merge(create_sales_invoice_item_routes(services.sales_invoice_item))
        // SalesOrder routes (12 Backbone endpoints)
        .merge(create_sales_order_routes(services.sales_order))
        // SalesOrderItem routes (12 Backbone endpoints)
        .merge(create_sales_order_item_routes(services.sales_order_item))
        // SalesTeam routes (12 Backbone endpoints)
        .merge(create_sales_team_routes(services.sales_team))
        // SalesPersonAllocation routes (12 Backbone endpoints)
        .merge(create_sales_person_allocation_routes(services.sales_person_allocation))
}

/// Create an individual entity's routes (for modular configuration)
pub mod individual {
    use super::*;

    pub fn quotation_routes(service: Arc<QuotationService>) -> Router {
        create_quotation_routes(service)
    }

    pub fn quotation_item_routes(service: Arc<QuotationItemService>) -> Router {
        create_quotation_item_routes(service)
    }

    pub fn sales_invoice_routes(service: Arc<SalesInvoiceService>) -> Router {
        create_sales_invoice_routes(service)
    }

    pub fn sales_invoice_item_routes(service: Arc<SalesInvoiceItemService>) -> Router {
        create_sales_invoice_item_routes(service)
    }

    pub fn sales_order_routes(service: Arc<SalesOrderService>) -> Router {
        create_sales_order_routes(service)
    }

    pub fn sales_order_item_routes(service: Arc<SalesOrderItemService>) -> Router {
        create_sales_order_item_routes(service)
    }

    pub fn sales_team_routes(service: Arc<SalesTeamService>) -> Router {
        create_sales_team_routes(service)
    }

    pub fn sales_person_allocation_routes(service: Arc<SalesPersonAllocationService>) -> Router {
        create_sales_person_allocation_routes(service)
    }

}
