//! Public events for Selling module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These events are published by this module for other modules to subscribe to.
//! Events are the primary mechanism for cross-module communication.

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};

use super::types::*;

// ============================================================================
// DELIVERYCARRIER EVENTS
// ============================================================================

/// Event published when a DeliveryCarrier is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryCarrierCreatedEvent {
    pub id: DeliveryCarrierId,
    pub data: DeliveryCarrierDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DeliveryCarrier is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryCarrierUpdatedEvent {
    pub id: DeliveryCarrierId,
    pub data: DeliveryCarrierDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a DeliveryCarrier is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryCarrierDeletedEvent {
    pub id: DeliveryCarrierId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// EXPENSEREINVOICELINK EVENTS
// ============================================================================

/// Event published when a ExpenseReinvoiceLink is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkCreatedEvent {
    pub id: ExpenseReinvoiceLinkId,
    pub data: ExpenseReinvoiceLinkDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpenseReinvoiceLink is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkUpdatedEvent {
    pub id: ExpenseReinvoiceLinkId,
    pub data: ExpenseReinvoiceLinkDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a ExpenseReinvoiceLink is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkDeletedEvent {
    pub id: ExpenseReinvoiceLinkId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUOTATION EVENTS
// ============================================================================

/// Event published when a Quotation is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationCreatedEvent {
    pub id: QuotationId,
    pub data: QuotationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Quotation is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationUpdatedEvent {
    pub id: QuotationId,
    pub data: QuotationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a Quotation is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationDeletedEvent {
    pub id: QuotationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUOTATIONITEM EVENTS
// ============================================================================

/// Event published when a QuotationItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationItemCreatedEvent {
    pub id: QuotationItemId,
    pub data: QuotationItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QuotationItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationItemUpdatedEvent {
    pub id: QuotationItemId,
    pub data: QuotationItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QuotationItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationItemDeletedEvent {
    pub id: QuotationItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// QUOTATIONTEMPLATE EVENTS
// ============================================================================

/// Event published when a QuotationTemplate is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationTemplateCreatedEvent {
    pub id: QuotationTemplateId,
    pub data: QuotationTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QuotationTemplate is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationTemplateUpdatedEvent {
    pub id: QuotationTemplateId,
    pub data: QuotationTemplateDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a QuotationTemplate is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationTemplateDeletedEvent {
    pub id: QuotationTemplateId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SALESORDER EVENTS
// ============================================================================

/// Event published when a SalesOrder is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderCreatedEvent {
    pub id: SalesOrderId,
    pub data: SalesOrderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesOrder is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderUpdatedEvent {
    pub id: SalesOrderId,
    pub data: SalesOrderDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesOrder is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderDeletedEvent {
    pub id: SalesOrderId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SALESORDERITEM EVENTS
// ============================================================================

/// Event published when a SalesOrderItem is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderItemCreatedEvent {
    pub id: SalesOrderItemId,
    pub data: SalesOrderItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesOrderItem is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderItemUpdatedEvent {
    pub id: SalesOrderItemId,
    pub data: SalesOrderItemDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesOrderItem is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderItemDeletedEvent {
    pub id: SalesOrderItemId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SALESTEAM EVENTS
// ============================================================================

/// Event published when a SalesTeam is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesTeamCreatedEvent {
    pub id: SalesTeamId,
    pub data: SalesTeamDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesTeam is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesTeamUpdatedEvent {
    pub id: SalesTeamId,
    pub data: SalesTeamDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesTeam is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesTeamDeletedEvent {
    pub id: SalesTeamId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// SALESPERSONALLOCATION EVENTS
// ============================================================================

/// Event published when a SalesPersonAllocation is created
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesPersonAllocationCreatedEvent {
    pub id: SalesPersonAllocationId,
    pub data: SalesPersonAllocationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesPersonAllocation is updated
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesPersonAllocationUpdatedEvent {
    pub id: SalesPersonAllocationId,
    pub data: SalesPersonAllocationDto,
    pub occurred_at: DateTime<Utc>,
}

/// Event published when a SalesPersonAllocation is deleted
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesPersonAllocationDeletedEvent {
    pub id: SalesPersonAllocationId,
    pub occurred_at: DateTime<Utc>,
}

// ============================================================================
// MODULE EVENT ENUM
// ============================================================================

/// All events published by Selling module
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum SellingEvent {
    DeliveryCarrierCreated(DeliveryCarrierCreatedEvent),
    DeliveryCarrierUpdated(DeliveryCarrierUpdatedEvent),
    DeliveryCarrierDeleted(DeliveryCarrierDeletedEvent),
    ExpenseReinvoiceLinkCreated(ExpenseReinvoiceLinkCreatedEvent),
    ExpenseReinvoiceLinkUpdated(ExpenseReinvoiceLinkUpdatedEvent),
    ExpenseReinvoiceLinkDeleted(ExpenseReinvoiceLinkDeletedEvent),
    QuotationCreated(QuotationCreatedEvent),
    QuotationUpdated(QuotationUpdatedEvent),
    QuotationDeleted(QuotationDeletedEvent),
    QuotationItemCreated(QuotationItemCreatedEvent),
    QuotationItemUpdated(QuotationItemUpdatedEvent),
    QuotationItemDeleted(QuotationItemDeletedEvent),
    QuotationTemplateCreated(QuotationTemplateCreatedEvent),
    QuotationTemplateUpdated(QuotationTemplateUpdatedEvent),
    QuotationTemplateDeleted(QuotationTemplateDeletedEvent),
    SalesOrderCreated(SalesOrderCreatedEvent),
    SalesOrderUpdated(SalesOrderUpdatedEvent),
    SalesOrderDeleted(SalesOrderDeletedEvent),
    SalesOrderItemCreated(SalesOrderItemCreatedEvent),
    SalesOrderItemUpdated(SalesOrderItemUpdatedEvent),
    SalesOrderItemDeleted(SalesOrderItemDeletedEvent),
    SalesTeamCreated(SalesTeamCreatedEvent),
    SalesTeamUpdated(SalesTeamUpdatedEvent),
    SalesTeamDeleted(SalesTeamDeletedEvent),
    SalesPersonAllocationCreated(SalesPersonAllocationCreatedEvent),
    SalesPersonAllocationUpdated(SalesPersonAllocationUpdatedEvent),
    SalesPersonAllocationDeleted(SalesPersonAllocationDeletedEvent),
}

/// Metadata for module events
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SellingEventMetadata {
    pub module: &'static str,
    pub version: &'static str,
}

impl Default for SellingEventMetadata {
    fn default() -> Self {
        Self {
            module: "selling",
            version: "1.0",
        }
    }
}

// ============================================================================
// CUSTOM EVENTS
// ============================================================================

// <<< CUSTOM EVENTS START >>>
// Add custom public events here
// <<< CUSTOM EVENTS END >>>
