//! Selling Module Exports
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! This module defines the public API that Selling exposes to other modules.
//! Other modules should ONLY depend on types defined here, not internal types.
//!
//! ## Usage from other modules
//!
//! ```text
//! use selling::exports::{DeliveryCarrierDto};
//! ```

mod types;
mod services;
mod events;

// Re-export all public types
pub use types::*;
pub use services::*;
pub use events::*;

// ============================================================================
// EXPORT SUMMARY
// ============================================================================

/// Summary of what this module exports
///
/// ## Public Types
/// - `DeliveryCarrierDto` - Data transfer object for DeliveryCarrier
/// - `DeliveryCarrierSummary` - Summary view of DeliveryCarrier
/// - `DeliveryCarrierId` - Type-safe ID wrapper
/// - `ExpenseReinvoiceLinkDto` - Data transfer object for ExpenseReinvoiceLink
/// - `ExpenseReinvoiceLinkSummary` - Summary view of ExpenseReinvoiceLink
/// - `ExpenseReinvoiceLinkId` - Type-safe ID wrapper
/// - `QuotationDto` - Data transfer object for Quotation
/// - `QuotationSummary` - Summary view of Quotation
/// - `QuotationId` - Type-safe ID wrapper
/// - `QuotationItemDto` - Data transfer object for QuotationItem
/// - `QuotationItemSummary` - Summary view of QuotationItem
/// - `QuotationItemId` - Type-safe ID wrapper
/// - `QuotationTemplateDto` - Data transfer object for QuotationTemplate
/// - `QuotationTemplateSummary` - Summary view of QuotationTemplate
/// - `QuotationTemplateId` - Type-safe ID wrapper
/// - `SalesOrderDto` - Data transfer object for SalesOrder
/// - `SalesOrderSummary` - Summary view of SalesOrder
/// - `SalesOrderId` - Type-safe ID wrapper
/// - `SalesOrderItemDto` - Data transfer object for SalesOrderItem
/// - `SalesOrderItemSummary` - Summary view of SalesOrderItem
/// - `SalesOrderItemId` - Type-safe ID wrapper
/// - `SalesTeamDto` - Data transfer object for SalesTeam
/// - `SalesTeamSummary` - Summary view of SalesTeam
/// - `SalesTeamId` - Type-safe ID wrapper
/// - `SalesPersonAllocationDto` - Data transfer object for SalesPersonAllocation
/// - `SalesPersonAllocationSummary` - Summary view of SalesPersonAllocation
/// - `SalesPersonAllocationId` - Type-safe ID wrapper
///
/// ## Public Events
/// - `DeliveryCarrierCreatedEvent` - Published when DeliveryCarrier is created
/// - `DeliveryCarrierUpdatedEvent` - Published when DeliveryCarrier is updated
/// - `DeliveryCarrierDeletedEvent` - Published when DeliveryCarrier is deleted
/// - `ExpenseReinvoiceLinkCreatedEvent` - Published when ExpenseReinvoiceLink is created
/// - `ExpenseReinvoiceLinkUpdatedEvent` - Published when ExpenseReinvoiceLink is updated
/// - `ExpenseReinvoiceLinkDeletedEvent` - Published when ExpenseReinvoiceLink is deleted
/// - `QuotationCreatedEvent` - Published when Quotation is created
/// - `QuotationUpdatedEvent` - Published when Quotation is updated
/// - `QuotationDeletedEvent` - Published when Quotation is deleted
/// - `QuotationItemCreatedEvent` - Published when QuotationItem is created
/// - `QuotationItemUpdatedEvent` - Published when QuotationItem is updated
/// - `QuotationItemDeletedEvent` - Published when QuotationItem is deleted
/// - `QuotationTemplateCreatedEvent` - Published when QuotationTemplate is created
/// - `QuotationTemplateUpdatedEvent` - Published when QuotationTemplate is updated
/// - `QuotationTemplateDeletedEvent` - Published when QuotationTemplate is deleted
/// - `SalesOrderCreatedEvent` - Published when SalesOrder is created
/// - `SalesOrderUpdatedEvent` - Published when SalesOrder is updated
/// - `SalesOrderDeletedEvent` - Published when SalesOrder is deleted
/// - `SalesOrderItemCreatedEvent` - Published when SalesOrderItem is created
/// - `SalesOrderItemUpdatedEvent` - Published when SalesOrderItem is updated
/// - `SalesOrderItemDeletedEvent` - Published when SalesOrderItem is deleted
/// - `SalesTeamCreatedEvent` - Published when SalesTeam is created
/// - `SalesTeamUpdatedEvent` - Published when SalesTeam is updated
/// - `SalesTeamDeletedEvent` - Published when SalesTeam is deleted
/// - `SalesPersonAllocationCreatedEvent` - Published when SalesPersonAllocation is created
/// - `SalesPersonAllocationUpdatedEvent` - Published when SalesPersonAllocation is updated
/// - `SalesPersonAllocationDeletedEvent` - Published when SalesPersonAllocation is deleted
pub struct ExportSummary;
