//! Public types for Selling module
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! These DTOs are the ONLY types other modules should use.
//! They are decoupled from internal domain entities.

use serde::{Deserialize, Serialize};
use uuid::Uuid;
use chrono::{DateTime, Utc, NaiveDate};
use rust_decimal::Decimal;
use crate::domain::entity::*;

// ============================================================================
// DELIVERYCARRIER TYPES
// ============================================================================

/// Type-safe ID for DeliveryCarrier
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct DeliveryCarrierId(pub Uuid);

impl DeliveryCarrierId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for DeliveryCarrierId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<DeliveryCarrierId> for Uuid {
    fn from(id: DeliveryCarrierId) -> Self {
        id.0
    }
}

/// Data transfer object for DeliveryCarrier
///
/// This is the public representation of DeliveryCarrier for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryCarrierDto {
    pub id: DeliveryCarrierId,
    pub company_id: Uuid,
    pub name: String,
    pub active: bool,
    pub tracking_url_template: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of DeliveryCarrier for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryCarrierSummary {
    pub id: DeliveryCarrierId,
    pub name: String,
}

/// Reference to DeliveryCarrier for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeliveryCarrierRef {
    pub id: DeliveryCarrierId,
}

// ============================================================================
// EXPENSEREINVOICELINK TYPES
// ============================================================================

/// Type-safe ID for ExpenseReinvoiceLink
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkId(pub Uuid);

impl ExpenseReinvoiceLinkId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for ExpenseReinvoiceLinkId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<ExpenseReinvoiceLinkId> for Uuid {
    fn from(id: ExpenseReinvoiceLinkId) -> Self {
        id.0
    }
}

/// Data transfer object for ExpenseReinvoiceLink
///
/// This is the public representation of ExpenseReinvoiceLink for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkDto {
    pub id: ExpenseReinvoiceLinkId,
    pub company_id: Uuid,
    pub order_id: Uuid,
    pub expense_id: Uuid,
    pub amount: Decimal,
    pub state: ExpenseReinvoiceState,
    pub metadata: serde_json::Value,
}

/// Summary view of ExpenseReinvoiceLink for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkSummary {
    pub id: ExpenseReinvoiceLinkId,
}

/// Reference to ExpenseReinvoiceLink for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExpenseReinvoiceLinkRef {
    pub id: ExpenseReinvoiceLinkId,
}

// ============================================================================
// QUOTATION TYPES
// ============================================================================

/// Type-safe ID for Quotation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuotationId(pub Uuid);

impl QuotationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuotationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuotationId> for Uuid {
    fn from(id: QuotationId) -> Self {
        id.0
    }
}

/// Data transfer object for Quotation
///
/// This is the public representation of Quotation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationDto {
    pub id: QuotationId,
    pub quotation_number: String,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub status: QuotationStatus,
    pub quotation_date: NaiveDate,
    pub valid_until: Option<NaiveDate>,
    pub currency: String,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<String>,
    pub opportunity_id: Option<Uuid>,
    pub status_reason: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of Quotation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationSummary {
    pub id: QuotationId,
    pub status: QuotationStatus,
}

/// Reference to Quotation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationRef {
    pub id: QuotationId,
}

// ============================================================================
// QUOTATIONITEM TYPES
// ============================================================================

/// Type-safe ID for QuotationItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuotationItemId(pub Uuid);

impl QuotationItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuotationItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuotationItemId> for Uuid {
    fn from(id: QuotationItemId) -> Self {
        id.0
    }
}

/// Data transfer object for QuotationItem
///
/// This is the public representation of QuotationItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationItemDto {
    pub id: QuotationItemId,
    pub quotation_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_discount: Decimal,
    pub line_amount: Decimal,
    pub invoice_policy: InvoicePolicy,
    pub is_downpayment: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of QuotationItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationItemSummary {
    pub id: QuotationItemId,
}

/// Reference to QuotationItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationItemRef {
    pub id: QuotationItemId,
}

// ============================================================================
// QUOTATIONTEMPLATE TYPES
// ============================================================================

/// Type-safe ID for QuotationTemplate
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct QuotationTemplateId(pub Uuid);

impl QuotationTemplateId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for QuotationTemplateId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<QuotationTemplateId> for Uuid {
    fn from(id: QuotationTemplateId) -> Self {
        id.0
    }
}

/// Data transfer object for QuotationTemplate
///
/// This is the public representation of QuotationTemplate for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationTemplateDto {
    pub id: QuotationTemplateId,
    pub company_id: Uuid,
    pub name: String,
    pub validity_days: i32,
    pub default_notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of QuotationTemplate for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationTemplateSummary {
    pub id: QuotationTemplateId,
    pub name: String,
}

/// Reference to QuotationTemplate for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct QuotationTemplateRef {
    pub id: QuotationTemplateId,
}

// ============================================================================
// SALESORDER TYPES
// ============================================================================

/// Type-safe ID for SalesOrder
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SalesOrderId(pub Uuid);

impl SalesOrderId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SalesOrderId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SalesOrderId> for Uuid {
    fn from(id: SalesOrderId) -> Self {
        id.0
    }
}

/// Data transfer object for SalesOrder
///
/// This is the public representation of SalesOrder for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderDto {
    pub id: SalesOrderId,
    pub order_number: String,
    pub quotation_id: Option<Uuid>,
    pub delivery_carrier_id: Option<Uuid>,
    pub tracking_ref: Option<String>,
    pub company_id: Uuid,
    pub branch_id: Option<Uuid>,
    pub customer_id: Uuid,
    pub status: SalesOrderStatus,
    pub order_date: NaiveDate,
    pub delivery_date: Option<NaiveDate>,
    pub currency: String,
    pub subtotal: Decimal,
    pub tax_rate: Decimal,
    pub tax_amount: Decimal,
    pub total: Decimal,
    pub notes: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of SalesOrder for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderSummary {
    pub id: SalesOrderId,
    pub status: SalesOrderStatus,
}

/// Reference to SalesOrder for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderRef {
    pub id: SalesOrderId,
}

// ============================================================================
// SALESORDERITEM TYPES
// ============================================================================

/// Type-safe ID for SalesOrderItem
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SalesOrderItemId(pub Uuid);

impl SalesOrderItemId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SalesOrderItemId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SalesOrderItemId> for Uuid {
    fn from(id: SalesOrderItemId) -> Self {
        id.0
    }
}

/// Data transfer object for SalesOrderItem
///
/// This is the public representation of SalesOrderItem for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderItemDto {
    pub id: SalesOrderItemId,
    pub order_id: Uuid,
    pub company_id: Uuid,
    pub item_id: Uuid,
    pub description: Option<String>,
    pub quantity: Decimal,
    pub unit_price: Decimal,
    pub line_discount: Decimal,
    pub line_amount: Decimal,
    pub unit_cost: Option<Decimal>,
    pub billed_qty: Decimal,
    pub delivered_qty: Decimal,
    pub invoice_policy: InvoicePolicy,
    pub is_downpayment: bool,
    pub metadata: serde_json::Value,
}

/// Summary view of SalesOrderItem for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderItemSummary {
    pub id: SalesOrderItemId,
}

/// Reference to SalesOrderItem for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesOrderItemRef {
    pub id: SalesOrderItemId,
}

// ============================================================================
// SALESTEAM TYPES
// ============================================================================

/// Type-safe ID for SalesTeam
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SalesTeamId(pub Uuid);

impl SalesTeamId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SalesTeamId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SalesTeamId> for Uuid {
    fn from(id: SalesTeamId) -> Self {
        id.0
    }
}

/// Data transfer object for SalesTeam
///
/// This is the public representation of SalesTeam for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesTeamDto {
    pub id: SalesTeamId,
    pub company_id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub metadata: serde_json::Value,
}

/// Summary view of SalesTeam for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesTeamSummary {
    pub id: SalesTeamId,
    pub name: String,
}

/// Reference to SalesTeam for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesTeamRef {
    pub id: SalesTeamId,
}

// ============================================================================
// SALESPERSONALLOCATION TYPES
// ============================================================================

/// Type-safe ID for SalesPersonAllocation
///
/// Use this instead of raw Uuid for type safety across modules.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct SalesPersonAllocationId(pub Uuid);

impl SalesPersonAllocationId {
    pub fn new(id: Uuid) -> Self {
        Self(id)
    }

    pub fn into_inner(self) -> Uuid {
        self.0
    }
}

impl From<Uuid> for SalesPersonAllocationId {
    fn from(id: Uuid) -> Self {
        Self(id)
    }
}

impl From<SalesPersonAllocationId> for Uuid {
    fn from(id: SalesPersonAllocationId) -> Self {
        id.0
    }
}

/// Data transfer object for SalesPersonAllocation
///
/// This is the public representation of SalesPersonAllocation for other modules.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesPersonAllocationDto {
    pub id: SalesPersonAllocationId,
    pub order_id: Uuid,
    pub company_id: Uuid,
    pub sales_person_id: Uuid,
    pub sales_team_id: Option<Uuid>,
    pub allocated_pct: Decimal,
    pub metadata: serde_json::Value,
}

/// Summary view of SalesPersonAllocation for list displays
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesPersonAllocationSummary {
    pub id: SalesPersonAllocationId,
}

/// Reference to SalesPersonAllocation for foreign key relationships
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SalesPersonAllocationRef {
    pub id: SalesPersonAllocationId,
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

// <<< CUSTOM TYPES START >>>
// Add custom public types here
// <<< CUSTOM TYPES END >>>
