//! Selling Module
//!
//! Generated by metaphor-schema. Enhanced with runtime implementations.
//!
//! This module provides:
//! - Domain entities and repositories
//! - Application services
//! - HTTP and gRPC handlers
//! - Route configuration
//! - State machine enforcement
//! - Validation rules runtime
//! - RBAC middleware
//! - Trigger execution system
//! - Computed fields
//! - Workflow orchestrator

#![recursion_limit = "1024"]
#![allow(unused_imports)]

// Generated modules
pub mod domain;
pub mod infrastructure;
pub mod application;
pub mod presentation;
pub mod seeders;

// Re-exports for convenience - Domain entities
pub use domain::entity::*;

// Re-exports - Infrastructure
pub use infrastructure::persistence::*;

// Re-exports - Application services
pub use application::service::QuotationService;
pub use application::service::QuotationItemService;
pub use application::service::SalesInvoiceService;
pub use application::service::SalesInvoiceItemService;
pub use application::service::SalesOrderService;
pub use application::service::SalesOrderItemService;
pub use application::service::SalesTeamService;
pub use application::service::SalesPersonAllocationService;

// Re-exports - Workflows
pub use application::workflows::*;

use std::sync::Arc;
use axum::Router;
use sqlx::PgPool;

/// Selling module configuration
///
/// Use the builder pattern to configure and register this module:
///
/// ```text
/// let selling = SellingModule::builder()
///     .with_database(pool.clone())
///     .build()?;
///
/// // Unguarded full CRUD (trusted/admin); compose a guarded router for production.
/// let router = selling.all_crud_routes();
/// ```
pub struct SellingModule {
    pub quotation_service: Arc<QuotationService>,
    pub quotation_item_service: Arc<QuotationItemService>,
    pub sales_invoice_service: Arc<SalesInvoiceService>,
    pub sales_invoice_item_service: Arc<SalesInvoiceItemService>,
    pub sales_order_service: Arc<SalesOrderService>,
    pub sales_order_item_service: Arc<SalesOrderItemService>,
    pub sales_team_service: Arc<SalesTeamService>,
    pub sales_person_allocation_service: Arc<SalesPersonAllocationService>,
}

impl SellingModule {
    /// Create a new module builder
    pub fn builder() -> SellingModuleBuilder {
        SellingModuleBuilder::new()
    }

    /// Mount ALL generated CRUD endpoints (12 per entity) with NO domain
    /// validation — the fully **unguarded** surface. A well-formed request can
    /// create invalid rows or soft-delete a referenced master out from under its
    /// dependents. Prefer a guarded composition (read + validated writes) for any
    /// real deployment; use this only in trusted/admin/seeding contexts.
    pub fn all_crud_routes(&self) -> Router {
        use presentation::http::{
            create_quotation_routes,
            create_quotation_item_routes,
            create_sales_invoice_routes,
            create_sales_invoice_item_routes,
            create_sales_order_routes,
            create_sales_order_item_routes,
            create_sales_team_routes,
            create_sales_person_allocation_routes,
        };

        Router::new()
            .merge(create_quotation_routes(self.quotation_service.clone()))
            .merge(create_quotation_item_routes(self.quotation_item_service.clone()))
            .merge(create_sales_invoice_routes(self.sales_invoice_service.clone()))
            .merge(create_sales_invoice_item_routes(self.sales_invoice_item_service.clone()))
            .merge(create_sales_order_routes(self.sales_order_service.clone()))
            .merge(create_sales_order_item_routes(self.sales_order_item_service.clone()))
            .merge(create_sales_team_routes(self.sales_team_service.clone()))
            .merge(create_sales_person_allocation_routes(self.sales_person_allocation_service.clone()))
    }

    /// Deprecated alias for [`Self::all_crud_routes`]. `routes()` reads like
    /// "the routes" but mounts UNVALIDATED generic CRUD on every entity — a naive
    /// mount exposes unguarded writes. Compose a guarded router (read + validated
    /// writes) for production, or call `all_crud_routes()` to opt into the full
    /// unguarded surface explicitly.
    #[deprecated(note = "mounts unvalidated generic CRUD on every entity; compose a guarded router for production, or call all_crud_routes() for the intentional full/unguarded surface")]
    pub fn routes(&self) -> Router {
        self.all_crud_routes()
    }
}

/// Builder for SellingModule
pub struct SellingModuleBuilder {
    db_pool: Option<PgPool>,
}

impl SellingModuleBuilder {
    /// Create a new builder
    pub fn new() -> Self {
        Self {
            db_pool: None,
        }
    }

    /// Set the database connection pool
    pub fn with_database(mut self, pool: PgPool) -> Self {
        self.db_pool = Some(pool);
        self
    }

    // <<< CUSTOM - custom builder methods
    // END CUSTOM

    /// Build the module with configured dependencies
    pub fn build(self) -> anyhow::Result<SellingModule> {
        let db_pool = self.db_pool
            .ok_or_else(|| anyhow::anyhow!("Database pool not configured"))?;

        // Quotation service
        let quotation_repository = Arc::new(QuotationRepository::new(db_pool.clone()));
        let quotation_service = Arc::new(QuotationService::with_repository(quotation_repository.clone()));

        // QuotationItem service
        let quotation_item_repository = Arc::new(QuotationItemRepository::new(db_pool.clone()));
        let quotation_item_service = Arc::new(QuotationItemService::with_repository(quotation_item_repository.clone()));

        // SalesInvoice service
        let sales_invoice_repository = Arc::new(SalesInvoiceRepository::new(db_pool.clone()));
        let sales_invoice_service = Arc::new(SalesInvoiceService::with_repository(sales_invoice_repository.clone()));

        // SalesInvoiceItem service
        let sales_invoice_item_repository = Arc::new(SalesInvoiceItemRepository::new(db_pool.clone()));
        let sales_invoice_item_service = Arc::new(SalesInvoiceItemService::with_repository(sales_invoice_item_repository.clone()));

        // SalesOrder service
        let sales_order_repository = Arc::new(SalesOrderRepository::new(db_pool.clone()));
        let sales_order_service = Arc::new(SalesOrderService::with_repository(sales_order_repository.clone()));

        // SalesOrderItem service
        let sales_order_item_repository = Arc::new(SalesOrderItemRepository::new(db_pool.clone()));
        let sales_order_item_service = Arc::new(SalesOrderItemService::with_repository(sales_order_item_repository.clone()));

        // SalesTeam service
        let sales_team_repository = Arc::new(SalesTeamRepository::new(db_pool.clone()));
        let sales_team_service = Arc::new(SalesTeamService::with_repository(sales_team_repository.clone()));

        // SalesPersonAllocation service
        let sales_person_allocation_repository = Arc::new(SalesPersonAllocationRepository::new(db_pool.clone()));
        let sales_person_allocation_service = Arc::new(SalesPersonAllocationService::with_repository(sales_person_allocation_repository.clone()));

        // <<< CUSTOM
        // END CUSTOM

        Ok(SellingModule {
            quotation_service,
            quotation_item_service,
            sales_invoice_service,
            sales_invoice_item_service,
            sales_order_service,
            sales_order_item_service,
            sales_team_service,
            sales_person_allocation_service,
            // <<< CUSTOM
            // END CUSTOM
        })
    }
}

impl Default for SellingModuleBuilder {
    fn default() -> Self {
        Self::new()
    }
}
