//! Application use cases
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each entity contributes 5 type aliases (create, update, get, delete, list).

pub mod base;
pub use base::{UseCaseError, UseCaseResult, UseCaseHooks};

pub mod quotation_usecases;
pub mod quotation_item_usecases;
pub mod sales_invoice_usecases;
pub mod sales_invoice_item_usecases;
pub mod sales_order_usecases;
pub mod sales_order_item_usecases;
pub mod sales_team_usecases;
pub mod sales_person_allocation_usecases;

pub use quotation_usecases::{
    CreateQuotationUseCase, UpdateQuotationUseCase, GetQuotationUseCase,
    DeleteQuotationUseCase, ListQuotationUseCase,
};
pub use quotation_item_usecases::{
    CreateQuotationItemUseCase, UpdateQuotationItemUseCase, GetQuotationItemUseCase,
    DeleteQuotationItemUseCase, ListQuotationItemUseCase,
};
pub use sales_invoice_usecases::{
    CreateSalesInvoiceUseCase, UpdateSalesInvoiceUseCase, GetSalesInvoiceUseCase,
    DeleteSalesInvoiceUseCase, ListSalesInvoiceUseCase,
};
pub use sales_invoice_item_usecases::{
    CreateSalesInvoiceItemUseCase, UpdateSalesInvoiceItemUseCase, GetSalesInvoiceItemUseCase,
    DeleteSalesInvoiceItemUseCase, ListSalesInvoiceItemUseCase,
};
pub use sales_order_usecases::{
    CreateSalesOrderUseCase, UpdateSalesOrderUseCase, GetSalesOrderUseCase,
    DeleteSalesOrderUseCase, ListSalesOrderUseCase,
};
pub use sales_order_item_usecases::{
    CreateSalesOrderItemUseCase, UpdateSalesOrderItemUseCase, GetSalesOrderItemUseCase,
    DeleteSalesOrderItemUseCase, ListSalesOrderItemUseCase,
};
pub use sales_team_usecases::{
    CreateSalesTeamUseCase, UpdateSalesTeamUseCase, GetSalesTeamUseCase,
    DeleteSalesTeamUseCase, ListSalesTeamUseCase,
};
pub use sales_person_allocation_usecases::{
    CreateSalesPersonAllocationUseCase, UpdateSalesPersonAllocationUseCase, GetSalesPersonAllocationUseCase,
    DeleteSalesPersonAllocationUseCase, ListSalesPersonAllocationUseCase,
};

// <<< CUSTOM
// END CUSTOM
