//! Use case type aliases for SalesOrderItem aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalesOrderItemDto, UpdateSalesOrderItemDto};
use crate::application::service::SalesOrderItemService;
use crate::domain::entity::SalesOrderItem;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalesOrderItemUseCase = CreateUseCase<SalesOrderItem, CreateSalesOrderItemDto, SalesOrderItemService>;
pub type UpdateSalesOrderItemUseCase = UpdateUseCase<SalesOrderItem, UpdateSalesOrderItemDto, SalesOrderItemService>;
pub type GetSalesOrderItemUseCase    = GetUseCase<SalesOrderItem, SalesOrderItemService>;
pub type DeleteSalesOrderItemUseCase = DeleteUseCase<SalesOrderItem, SalesOrderItemService>;
pub type ListSalesOrderItemUseCase   = ListUseCase<SalesOrderItem, SalesOrderItemService>;

// <<< CUSTOM
// END CUSTOM
