//! Use case type aliases for SalesPersonAllocation aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalesPersonAllocationDto, UpdateSalesPersonAllocationDto};
use crate::application::service::SalesPersonAllocationService;
use crate::domain::entity::SalesPersonAllocation;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalesPersonAllocationUseCase = CreateUseCase<SalesPersonAllocation, CreateSalesPersonAllocationDto, SalesPersonAllocationService>;
pub type UpdateSalesPersonAllocationUseCase = UpdateUseCase<SalesPersonAllocation, UpdateSalesPersonAllocationDto, SalesPersonAllocationService>;
pub type GetSalesPersonAllocationUseCase    = GetUseCase<SalesPersonAllocation, SalesPersonAllocationService>;
pub type DeleteSalesPersonAllocationUseCase = DeleteUseCase<SalesPersonAllocation, SalesPersonAllocationService>;
pub type ListSalesPersonAllocationUseCase   = ListUseCase<SalesPersonAllocation, SalesPersonAllocationService>;

// <<< CUSTOM
// END CUSTOM
