//! Use case type aliases for SalesInvoice aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalesInvoiceDto, UpdateSalesInvoiceDto};
use crate::application::service::SalesInvoiceService;
use crate::domain::entity::SalesInvoice;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalesInvoiceUseCase = CreateUseCase<SalesInvoice, CreateSalesInvoiceDto, SalesInvoiceService>;
pub type UpdateSalesInvoiceUseCase = UpdateUseCase<SalesInvoice, UpdateSalesInvoiceDto, SalesInvoiceService>;
pub type GetSalesInvoiceUseCase    = GetUseCase<SalesInvoice, SalesInvoiceService>;
pub type DeleteSalesInvoiceUseCase = DeleteUseCase<SalesInvoice, SalesInvoiceService>;
pub type ListSalesInvoiceUseCase   = ListUseCase<SalesInvoice, SalesInvoiceService>;

// <<< CUSTOM
// END CUSTOM
