//! Use case type aliases for SalesOrder aggregate
//!
//! Generated by metaphor-schema. Do not edit manually.
//!
//! Each alias delegates to the matching generic use case in backbone-core.
//! Custom pre/post hooks go in `UseCaseHooks` implementations (// <<< CUSTOM).

use backbone_core::{
    CreateUseCase, UpdateUseCase, GetUseCase, DeleteUseCase, ListUseCase,
};

use crate::presentation::dto::{CreateSalesOrderDto, UpdateSalesOrderDto};
use crate::application::service::SalesOrderService;
use crate::domain::entity::SalesOrder;

// ─── Use case type aliases ───────────────────────────────────────────────────

pub type CreateSalesOrderUseCase = CreateUseCase<SalesOrder, CreateSalesOrderDto, SalesOrderService>;
pub type UpdateSalesOrderUseCase = UpdateUseCase<SalesOrder, UpdateSalesOrderDto, SalesOrderService>;
pub type GetSalesOrderUseCase    = GetUseCase<SalesOrder, SalesOrderService>;
pub type DeleteSalesOrderUseCase = DeleteUseCase<SalesOrder, SalesOrderService>;
pub type ListSalesOrderUseCase   = ListUseCase<SalesOrder, SalesOrderService>;

// <<< CUSTOM
// END CUSTOM
